- lapack/lapack.go
- lapack/testlapack/doc.go
- mathext/doc.go
- optimize/convex/lp/doc.go
> Add remaining canonical import paths

- .travis.yml
- .travis/check-generate.sh
- graph/encoding/dot/decode.go
- lapack/native/appengine_test.go
- lapack/native/lapack_test.go
- matrix/gendoc.go
- stat/appengine_test.go
- stat/pca_test.go
* Add completish set of tests (from "github.com/gonum/matrix").
* Fix single failure.
> travis: fix build

- blas/native/general_double.go
- blas/native/general_single.go
- blas/native/level1double.go
- blas/native/level1single.go
- blas/native/level2double.go
- blas/native/level2single.go
- blas/native/native.go
- blas/testblas/common.go
- blas/testblas/dgemm.go
- blas/testblas/dgemv.go
- blas/testblas/dger.go
- blas/testblas/dtbsv.go
I started with blas but I plan to continue to clean things also in other packages.
> blas: clean up things pointed out by megacheck

- graph/graphs/gen/duplication.go
@vladimir-ch @mewmew Please take a look.
> graph/graphs/gen: allow dst to determine first ID number

- graph/encoding/dot/decode.go
@mewmew Please take a look.
Minor doc tweak and reducing block indentation.
> graph/endcoding/dot: tidy up decode code/docs

- matrix/mat64/cholesky.go
- matrix/mat64/dense_arithmetic.go
- matrix/mat64/eigen.go
- matrix/mat64/lq.go
- matrix/mat64/lu.go
- matrix/mat64/matrix.go
- matrix/mat64/pool.go
- matrix/mat64/qr.go
- matrix/mat64/solve.go
- matrix/mat64/svd.go
- matrix/mat64/triangular.go
> matrix/mat64: use pools for []float64 and []int where possible

- graph/encoding/dot/decode.go
- graph/encoding/dot/decode_test.go
Fixes #57.
@mewmew Please take a look.
Working on this has prompted some thinking. There is a discordance between the interfaces provided for marshaling versus unmarshaling. It would be nice if we could harmonise them - this would be API breaking.
> graph/encoding/dot: allow unmarshaling of global attributes

- graph/encoding/dot/decode.go
- graph/encoding/dot/decode_test.go
> graph/encoding/dot: allow unmarshalling of DOT IDs

- floats/floats.go
- floats/parse_example_test.go
> floats: add ParseWithNA

- mat/cholesky.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/doc.go
- mat/eigen.go
- mat/errors.go
- mat/gsvd.go
- mat/inner.go
- mat/io.go
- mat/lu.go
- mat/matrix.go
- mat/shadow.go
- mat/svd.go
- mat/symmetric.go
- mat/triangular.go
- mat/vector.go
Noticed some missed changes in strings and comment when I updated the godoc registry.
> mat: s/mat64/mat/g

- lapack/gonum/dlasq4.go
See https://github.com/Reference-LAPACK/lapack/issues/158 for this
change done in the reference LAPACK.
> lapack/gonum: remove unused assignment to local variable in Dlasq4

- graph/topo/johnson_cycles_test.go
> graph/topo: remove unused field

- .travis.yml
- .travis/check-generate.sh
> travis: fix nits

- graph/encoding/dot/dot_test.go
- graph/path/dijkstra_test.go
- graph/path/floydwarshall_test.go
- graph/path/johnson_apsp_test.go
- lapack/testlapack/general.go
- stat/distuv/general_test.go
- stat/distuv/laplace.go
- stat/distuv/uniform.go
- stat/samplemv/sample_test.go
- stat/samplemv/samplemv.go
> all: simplify code identified by gosimple

- stat/cca_example_test.go
- stat/cca_test.go
- stat/pca_cca.go
- stat/pca_example_test.go
- stat/pca_test.go
This is a replay of gonum/stat#170
Updates #4.
> stat: append To suffix to extraction methods

- stat/distuv/exponential.go
- stat/distuv/general_test.go
- stat/distuv/norm.go
Updates gonum/stat#179.
Updates #4.
> stat/distuv: move destination to first position

- blas/gonum/dgemm.go
- blas/gonum/sgemm.go
- mat/dense_test.go
> blas/gonum: panic with more informative messages

- mat/cholesky.go
- mat/eigen.go
- mat/gsvd.go
- mat/hogsvd.go
- mat/qr.go
- mat/svd.go
See gonum/matrix#446.
Closes #105.
> mat: remove outdated attributions to Jama code

- .travis.yml
After suggestion for gonum/plot by @Kunde21 in https://github.com/gonum/plot/pull/349#issuecomment-297923393/
> travis: add testing for go tip allowing failure

- blas/gonum/internal/math32/math_test.go
> blas/gonum/internal/math32: deflake test

- floats/floats_test.go
This takes the table from `TestRoundEven` and changes the relevant want fields. Changed that differ between the two are
```
x: 454.4445, prec: 3
x: 454.44445, prec: 4
x: 0.425, prec: 2
x: 123.4245, prec: 3
x: 454.45, prec: 1
x: 454.445, prec: 2
x: 500, prec: -3
```
Fixes #114.
These tests are simpler and (as I discovered a couple of days ago - `strconv.FormatFloat` uses [round half to even](https://play.golang.org/p/Vwt2MZFrI_)) actually correct.
> floats: deflake Round test

- mat/cholesky.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/doc.go
- mat/io.go
- mat/product.go
- mat/symmetric.go
- mat/triangular.go
- mat/vector.go
- stat/pca_cca.go
> mat: add IsZero method to resetable types

- mat/band.go
- mat/band_test.go
> mat: fix lint and vet errors

- mat/index_bound_checks.go
- mat/index_no_bound_checks.go
- mat/symband.go
- mat/symband_test.go
> mat: add symmetric band types

- graph/topo/paton_cycles.go
- graph/topo/paton_cycles_test.go
@mewmew @vladimir-ch Please take a look.
Depends on #70.
Fixes gonum/graph#197.
> graph/topo: add undirected cycles routine

- .travis.yml
- .travis/check-generate.sh
- graph/encoding/dot/decode.go
- graph/formats/dot/ast/ast.go
- graph/formats/dot/dot.go
- graph/formats/dot/internal/dot.bnf
- graph/formats/dot/internal/lexer/lexer.go
- graph/formats/dot/internal/lexer/transitiontable.go
- graph/formats/dot/internal/parser/actiontable.go
- graph/formats/dot/internal/parser/gototable.go
- graph/formats/dot/internal/parser/parser.go
- graph/formats/dot/internal/parser/productionstable.go
- graph/formats/dot/makeinternal.bash
- graph/formats/dot/sem.go
Added code generation check to ensure the correct changes are happening.
Due to changes in gocc, code needed to be regenerated to pass. I'm not sure I like this.
Closes #24.
Closes #115.
> graph/formats/dot: rename Kind* => *Kind

- blas/gonum/cmplx.go
- blas/gonum/gonum.go
- blas/gonum/level1cmplx128.go
- blas/gonum/level1cmplx128_test.go
- blas/testblas/common.go
- blas/testblas/zaxpy.go
Starting to slowly add complex BLAS routines.
> blas/gonum: add Zaxpy

- AUTHORS
- CONTRIBUTORS
- stat/distuv/triangle.go
- stat/distuv/triangle_test.go
This adds a triangle distribution to the package, which is useful for business simulations when there is limited sample data available on input variables.
> add triangle distribution and associated tests

- AUTHORS
- CONTRIBUTORS
Submitted PR #370 to gonum/plot and as requested added name to authors and contributors.
Thanks!
> Added self as A+C to gonum

- stat/sampleuv/weighted.go
> stat/sampleuv: set src appropriately in NewWeighted.

- mat/cholesky.go
- mat/cholesky_test.go
- mat/hogsvd.go
> mat: export Dense.solveTwoChol

- mat/lq.go
- mat/lu.go
- mat/matrix.go
- mat/matrix_test.go
- mat/qr.go
> mat: add Cond method to factorising types

- blas/blas32/conv_symmetric_test.go
- blas/blas32/conv_test.go
- blas/blas64/conv_symmetric_test.go
- blas/blas64/conv_test.go
- blas/cblas128/conv_hermitian_test.go
- blas/cblas128/conv_symmetric_test.go
- blas/cblas128/conv_test.go
- blas/cblas64/conv_hermitian_test.go
- blas/cblas64/conv_test.go
@vladimir-ch Please take a look.
Closes #173.
> blas: rename test check function equal*=>same*

- mat/cholesky.go
- mat/errors.go
- mat/lq.go
- mat/lu.go
- mat/qr.go
Are we ok with the utf8 symbol usage?
> mat: clarify implementation comments about condition number calculation

- .travis.yml
- graph/formats/dot/internal/errors/errors.go
- graph/formats/dot/internal/lexer/acttab.go
- graph/formats/dot/internal/lexer/lexer.go
- graph/formats/dot/internal/parser/parser.go
- graph/formats/dot/internal/token/token.go
> graph/formats/dot/internal: update gocc version to cfc6e12

- README.md
> README: add installation and tags docs

- graph/encoding/dot/decode.go
- graph/encoding/dot/decode_test.go
- graph/encoding/encoding.go
- graph/encoding/graphql/decode_test.go
- graph/graph.go
- graph/path/internal/testgraphs/shortest.go
- graph/simple/directed.go
- graph/simple/undirected.go
Also rename graph.EdgeSetter to graph.EdgeAdder.
Fixes #56.
> graph: move NewEdge method from encoding.Builder to graph.EdgeAdder

- internal/asm/c128/dscalinc_amd64.s
- internal/asm/c128/dscalunitary_amd64.s
- internal/asm/c128/scal.go
- internal/asm/c128/scalUnitary_amd64.s
- internal/asm/c128/scalinc_amd64.s
- internal/asm/c128/stubs_amd64.go
- internal/asm/c128/stubs_noasm.go
- internal/asm/c128/stubs_test.go
- internal/asm/c128/util_test.go
Combining due to code similarity.  I can add the `To` variants if they're needed.
> asm/c128: Added [d]scalinc and [d]scalunitary

- AUTHORS
- CONTRIBUTORS
- diff/fd/jacobian.go
- mat/dense.go
- mat/dense_test.go
- mat/hogsvd.go
- mat/list_test.go
- mat/matrix.go
- mat/matrix_test.go
- mat/symmetric.go
- mat/vector.go
- mat/vector_test.go
Generalised ColView and RowView methods to return Vector rather than VecDense and changed Dot() function to use Vector.
> Generalise vector methods

- blas/gonum/level2double.go
- blas/gonum/level2single.go
- blas/testblas/common.go
- blas/testblas/dger.go
Fixes #224 
Added regression test and changed calculation to standardize NaN propagation in Dger.
> blas/gonum:  Fixing NaN popagation in Dger. 

- mat/cholesky.go
- mat/cholesky_example_test.go
- mat/cholesky_test.go
- stat/distmat/wishart.go
- stat/distmv/normal_test.go
> mat: change cholesky.To to cholesky.ToSym

- AUTHORS
- CONTRIBUTORS
- stat/stat_test.go
- stat/statmat_test.go
> Unexport Panics testing helper. It was exported unnecessarily.

- blas/gonum/cmplx.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/zhemv.go
> blas/gonum: add Zhemv

- mat/cholesky.go
> mat: don't confuse notions of zero

- AUTHORS
- CONTRIBUTORS
- mat/dense_arithmetic_test.go
- mat/dense_example_test.go
Instead of adding all examples at once, I just added a few to see if anyone has comments before working on the rest.
> mat: added a few godoc examples for Dense methods

- mat/dense_example_test.go
a few more examples for the godoc - Mul, Exp, Pow, and Scale methods.
> mat: added godoc examples for dense mul/exp/pow/scale

- stat/sampleuv/withoutreplacement.go
> stat/sampleuv: add missing return

- blas/gonum/dtrmvbench_test.go
- blas/gonum/level2cmplx128_bench_test.go
- graph/path/control_flow_bench_test.go
- internal/asm/c128/benchDot_test.go
- internal/asm/c64/benchDot_test.go
- internal/asm/f32/benchDot_test.go
- internal/asm/f64/benchAxpy_test.go
- internal/asm/f64/benchScal_test.go
- lapack/gonum/bench_test.go
- lapack/testlapack/dgeev_bench.go
> all: remove go1.7 build constraints

- AUTHORS
- CONTRIBUTORS
As requested by @kortschak on https://github.com/gonum/plot/pull/414
> add Francesc Campoy and source{d} to A+C

- floats/floats.go
- stat/distuv/norm.go
- stat/stat.go
Change due to golang/go@08f19bbde1b01227fdc2fa2d326e4029bb74dd96.
> all: run Go tip gofmt -s

- mat/cholesky.go
> mat: fix docs and error check in Cholesky.ExtendVecSym

- floats/floats.go
- floats/floats_test.go
Addresses https://github.com/gonum/gonum/pull/50#issuecomment-306936995.
> floats: add functions for handling NaN payloads

- blas/gonum/cmplx.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/ztrmv.go
> blas: add Ztrmv

- graph/network/diffusion.go
- graph/network/diffusion_test.go
- graph/network/network_test.go
@btracey @vladimir-ch Please take a look.
> graph/network: add heat diffusion propagation function

- optimize/cmaes.go
- optimize/cmaes_test.go
- optimize/global.go
- optimize/termination.go
Fixes https://github.com/gonum/optimize/issues/180
> optimize: Add CMA-ES Cholesky global optimization method

- graph/topo/2sat_example_test.go
Systems in example checked with minisat.
> graph/topo: add 2-sat example

- AUTHORS
- CONTRIBUTORS
- stat/distuv/poisson.go
- stat/distuv/poisson_test.go
From @sbinet  PR #259, I've made the following updates:
- add non-integer Prob test cases
- add CDF test cases
- fix CDF to use upper incomplete gamma function
The test case fails for the CDF due to tolerance issues. I'm still resolving that issue.
> implement Poisson based on PR #259

- stat/distuv/poisson.go
- stat/distuv/poisson_test.go
> stat/distuv: use golang.org/x/exp/rand

- blas/testblas/common.go
- blas/testblas/ztrsv.go
Motivated by https://github.com/gonum/gonum/pull/322#discussion_r155117999
> blas/testblas: split zEqualApprox into 2 functions

- blas/gonum/cmplx.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/zhemv.go
- blas/testblas/zhpmv.go
> blas/gonum: add Zhpmv

- mathext/digamma.go
- optimize/cmaes_test.go
> all: run gofmt -s

- AUTHORS
- CONTRIBUTORS
- stat/stat.go
- stat/stat_test.go
Hey,
I'm really interested by gonum so I wanted to start with a little PR to implement Kendall correlation. I not there hasn't been any issue asking for it but I need it for one of my projects and I though I might as well make a PR.
> stat: implement Kendall correlation

- mat/index_bound_checks.go
- mat/index_no_bound_checks.go
- mat/vector.go
I found this lying around due to another PR. I didn't remember writing it, but on thinking I vaguely remember having some discussion with @btracey about some things that appear here, so I'm sending it with a view to clarifying that. I imagine I was planning on adding this as a prelude to attacking more of #167.
Updates #167.
> mat: add vector helpers

- stat/distuv/uniform_test.go
Created test file for Uniform random variables. The test file was based off of the ChiSquared test file.
> Stat uniform tests

- stat/distmat/wishart.go
- stat/distmv/dirichlet.go
- stat/distmv/normal.go
- stat/distuv/bernoulli.go
- stat/distuv/beta.go
- stat/distuv/beta_test.go
- stat/distuv/exponential.go
- stat/distuv/f.go
- stat/distuv/gamma.go
- stat/distuv/gamma_test.go
- stat/distuv/laplace.go
- stat/distuv/lognormal.go
- stat/distuv/norm.go
- stat/distuv/poisson.go
- stat/distuv/triangle.go
- stat/distuv/triangle_test.go
- stat/distuv/uniform.go
- stat/distuv/weibull.go
Fixes original gonum/stat #147
> stat/all: Change all Source to Src

- stat/distmv/studentst.go
> stat/distmv: add Nu function to Student's T

- graph/doc.go
> graph: remove out-of-date documentation

- mat/io_test.go
- mat/vector.go
- mat/vector_test.go
> mat: generalise basic arithmetic vector operations

- mat/list_test.go
- mat/matrix_test.go
- mat/solve_test.go
- mat/vector_test.go
> mat: relax list test type restrictions for Vector parameters

- stat/statmat.go
> stat: generalise Mehalanobis vector parameters

- mat/inner.go
> mat: generalise Inner vector parameters

- mat/cholesky.go
- mat/lq.go
- mat/lu.go
- mat/qr.go
- mat/solve.go
- mat/solve_test.go
> mat: generalise SolveVec vector parameters

- graph/simple/directed.go
- graph/simple/undirected.go
- graph/simple/weighted_directed.go
- graph/simple/weighted_undirected.go
> simple: fix nil edge returns

- blas/gonum/doc.go
- lapack/gonum/dlarft.go
- lapack/gonum/doc.go
- mat/lq.go
- mat/lu.go
- mat/qr.go
- mat/solve.go
- unit/doc.go
- unit/unittype.go
> blas,lapack,mat,unit: remove "Please" from documentation

- mat/inner.go
> mat: clean up Inner parameter naming

- mat/vector.go
> mat: handle vector transposes better

- mat/cholesky.go
- mat/dense_arithmetic.go
- mat/dense_test.go
- mat/list_test.go
- mat/lu.go
- mat/symmetric.go
- mat/symmetric_test.go
- mat/vector_test.go
> mat: generalise outer and rank update vector parameters

- lapack/gonum/appengine_test.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dgeev.go
> lapack: loosen Dgeev test case tolerance

- stat/distmv/uniform.go
> stat/distmv: use custom source in Uniform.Rand when available

- graph/internal/uid/uid.go
- graph/multi/directed.go
- graph/multi/directed_test.go
- graph/multi/doc.go
- graph/multi/multi.go
- graph/multi/undirected.go
- graph/multi/undirected_test.go
- graph/multi/weighted_directed.go
- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected.go
- graph/multi/weighted_undirected_test.go
- graph/simple/directed.go
- graph/simple/simple.go
- graph/simple/undirected.go
- graph/simple/weighted_directed.go
- graph/simple/weighted_undirected.go
Note that dates are old since the code is largely cribbed from simple.
Closes #342.
> graph: add multigraph implementation

- graph/graphs/gen/batagelj_brandes.go
- graph/graphs/gen/batagelj_brandes_test.go
> gen: add multigraph power-law generators

- stat/roc.go
> stat: fix ROC for uniform cases

- floats/floats.go
- floats/floats_test.go
> floats: fix Same for NaN/N

- .github/ISSUE_TEMPLATE
> github: direct questions to gonum-dev

- .travis.yml
> travis: add go-1.10.x

- graph/graph.go
- graph/graph_test.go
> graph: fix undirected to directed copy behaviour

- mat/cholesky.go
- mat/lq.go
- mat/lu.go
- mat/qr.go
- mat/solve.go
> mat: harmonise parameter naming and documentation

- blas/gonum/level1double.go
- blas/gonum/level1single.go
> blas/gonum: use p.Flag in rotm more carefully

- blas/gonum/cmplx.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/ztpsv.go
> blas/gonum: add Ztpsv

- blas/gonum/level1double.go
- blas/gonum/level1single.go
Sorry, I missed these in the original PR.
> blas/gonum: clean up unnecessary indentation

- blas/gonum/cmplx.go
- blas/gonum/gonum.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/common.go
- blas/testblas/zgbmv.go
> blas/gonum: add Zgbmv

- blas/gonum/level2double.go
- blas/gonum/level2single.go
- blas/testblas/dgbmv.go
> blas/gonum: fix bad bound on column index in Dgbmv

- AUTHORS
- CONTRIBUTORS
> New Contributor @TacoVox

- blas/gonum/cmplx.go
- blas/gonum/gonum.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/common.go
- blas/testblas/zhbmv.go
> blas/gonum: add Zhbmv

- stat/distuv/general.go
- stat/distuv/gumbel.go
- stat/distuv/gumbel_test.go
> stat/distuv: Add Gumbel distribution

- AUTHORS
- CONTRIBUTORS
- graph/encoding/dot/encode.go
- graph/encoding/dot/encode_test.go
- graph/encoding/dot/example_test.go
> encoding/dot: fix ports on undirected graphs

- fourier/internal/fftpack/fftpack_test.go
> fftpack: fix import

- blas/gonum/level2cmplx128.go
> blas/gonum: run gofmt -s

- blas/gonum/cmplx.go
- blas/gonum/gonum.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/ztbmv.go
Updates #184 
I don't understand how it happened that Zhbmv was not gofmted and that is was not detected.
> blas/gonum: add Ztbmv

- AUTHORS
- CONTRIBUTORS
As discussed in https://github.com/gonum/hdf5/pull/15
> A+C: add gustafj

- blas/gonum/cmplx.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2cmplx128_test.go
- blas/testblas/ztbmv.go
- blas/testblas/ztbsv.go
> blas/gonum: add Ztbsv

- graph/graph.go
- graph/multi/directed.go
- graph/multi/directed_test.go
- graph/multi/undirected.go
- graph/multi/undirected_test.go
- graph/multi/weighted_directed.go
- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected.go
- graph/multi/weighted_undirected_test.go
- graph/multigraph.go
- graph/path/control_flow_bench_test.go
- graph/simple/dense_directed_matrix.go
- graph/simple/dense_undirected_matrix.go
- graph/simple/densegraph_test.go
- graph/simple/directed.go
- graph/simple/directed_test.go
- graph/simple/undirected.go
- graph/simple/undirected_test.go
- graph/simple/weighted_directed.go
- graph/simple/weighted_directed_test.go
- graph/simple/weighted_undirected.go
- graph/simple/weighted_undirected_test.go
> graph: use int64 for node, edge and line removal indexing

- blas/testblas/zgbmv.go
- blas/testblas/zhbmv.go
- blas/testblas/ztbmv.go
- blas/testblas/ztbsv.go
- blas/testblas/ztpsv.go
- blas/testblas/ztrsv.go
Prompted by comment https://github.com/gonum/gonum/pull/465#discussion_r186274052
> blas/testblas: document implementation of some L2 complex tests

- graph/path/johnson_apsp.go
> graph/path: tighten use of johnsonWeightAdjuster

- stat/appengine_test.go
- stat/pca_test.go
> stat: handle non-unique results in test for PC

- mat/eigen_test.go
> mat: test that SymEigen eigenvalues are in ascending order

- mat/eigen.go
> mat: note that EigenSym orders values ascending

- .travis.yml
- README.md
> README: explicitly state version support policy

- mat/dense.go
- mat/dense_arithmetic.go
- mat/shadow.go
- mat/symmetric.go
- mat/triangular.go
> mat: improve mat element shadowing detection

- stat/distuv/statdist.go
- stat/distuv/statdist_test.go
> stat/distuv: Add KL divergences for Normal and Beta distributions

- stat/distuv/statdist.go
> stat/distuv: change KL comment spelling and distance to divergence

- stat/distmv/statdist.go
- stat/distmv/statdist_test.go
> stat/distmv: Add KL divergence for two Dirichlet distributions

- stat/distuv/beta.go
- stat/distuv/beta_test.go
> stat/distuv: Add Entropy function for Beta distribution

- lapack/gonum/dtrevc3.go
> lapack/gonum: fix doc comment for Dtrevc3

- stat/stat.go
> stat: fix panic message

- blas/gonum/doc.go
- fourier/internal/fftpack/doc.go
- graph/formats/dot/internal/errors/doc.go
- graph/formats/dot/internal/lexer/doc.go
- graph/formats/dot/internal/parser/doc.go
- graph/formats/dot/internal/token/doc.go
- graph/formats/dot/internal/util/doc.go
- graph/path/a_star_test.go
- graph/path/dynamic/dstarlite_test.go
- graph/path/dynamic/dumper_test.go
- graph/path/internal/testgraphs/doc.go
- graph/path/internal/testgraphs/grid.go
- graph/path/internal/testgraphs/grid_test.go
- graph/path/internal/testgraphs/limited.go
- graph/path/internal/testgraphs/limited_test.go
- lapack/doc.go
- lapack/lapack.go
- mathext/internal/amos/doc.go
- mathext/internal/gonum/doc.go
> all: fix up godoc rendering of package lists

- lapack/testlapack/dlaqr23.go
> lapack/testlapack: add implementation comments to Dlaqr23 test

- lapack/testlapack/dlanv2.go
> lapack/testlapack: add implementation comments to Dlanv2 test

- lapack/testlapack/dlarfx.go
> lapack/testlapack: add implementation comment to Dlarfx test

- lapack/testlapack/dlaln2.go
> lapack/testlapack: add implementation comments to Dlaln2 test

- go.mod
> gonum: add initial vgo support

- graph/encoding/dot/decode.go
> graph/encoding/dot: add attributes for edge chains

- AUTHORS
- CONTRIBUTORS
> add me to A+C

- .travis.yml
> travis: add Go1.11.x, drop Go1.8.x

- stat/stat_example_test.go
> stat: add example for LinearRegression

- CONTRIBUTING.md
> doc: fix links to repositories

- mat/format_test.go
This fixes the formatting issues that have been causing go:master to fail.
> mat: avoid hard coding expected output that depends on weak promises

- graph/undirect.go
> graph: fix doc for Undirect*.Node

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/proposal.md
- .github/ISSUE_TEMPLATE/question.md
> github: extend issues templates

- blas/blas.go
- blas/testblas/dgemv.go
> blas: change matrix description types to byte

- AUTHORS
- CONTRIBUTORS
- graph/encoding/dot/doc.go
> [fix] graph/encoding/dot: fix link to dot documentation (dead link to the PDF file)

- AUTHORS
- mat/diagonal.go
- mat/diagonal_test.go
- mat/errors.go
- mat/index_bound_checks.go
- mat/index_no_bound_checks.go
- mat/list_test.go
- mat/symband.go
- mat/symband_test.go
- optimize/cmaes.go
- stat/pca_test.go
> mat: Add Diagonal interface and DiagDense type

- AUTHORS
- CONTRIBUTORS
> A + C: add Vincent Thiery

- stat/distmv/studentst.go
- stat/distmv/uniform.go
- stat/distuv/interfaces.go
- stat/distuv/statdist.go
- stat/distuv/weibull.go
- stat/roc.go
- stat/samplemv/halton.go
- stat/samplemv/metropolishastings.go
- stat/sampleuv/sample.go
- stat/stat_test.go
Fixing the warnings that `golint` highlights in the `stat` package
> Fix golint warnings in stat package

- mat/eigen_example_test.go
> mat: add examples for Eigen and EigenSym

- AUTHORS
- CONTRIBUTORS
> A+C: add Alexander Egurnov

- AUTHORS
- CONTRIBUTORS
- stat/distuv/laplace.go
- stat/distuv/laplace_test.go
Fixed issue when weights are nil.
Fix Fit function
This PR closes #638 closes #639
> stat/distuv: fix Laplace.Fit

- unit/doc.go
- unit/generate_unit.go
> unit: move code generation to unit package

- lapack/testlapack/dtrtri.go
> lapack/testlapack: add implementation comments to Dtrtri test

- .travis/test-coverage.sh
- graph/iterator/nodes.go
- graph/multi/directed_test.go
- graph/multi/multi.go
- graph/multi/undirected_test.go
- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected_test.go
- graph/simple/dense_directed_matrix.go
- graph/simple/dense_undirected_matrix.go
- graph/simple/densegraph_test.go
- graph/simple/directed_test.go
- graph/simple/undirected_test.go
- graph/simple/weighted_directed.go
- graph/simple/weighted_directed_test.go
- graph/simple/weighted_undirected_test.go
- graph/testgraph/testcases.go
- graph/testgraph/testgraph.go
> graph/testgraph: add graph implementation exercising package

- mat/symband.go
> mat: add SymBanded type

- lapack/gonum/dlasr.go
- lapack/testlapack/dlasr.go
- lapack/testlapack/dlatrd.go
- lapack/testlapack/dorg2r.go
- lapack/testlapack/dorgtr.go
- lapack/testlapack/dtrti2.go
> lapack/testlapack: add implementation comments to some tests

- mat/diagonal.go
- mat/triband.go
> mat: Clean up TriBand documentation

- mat/band.go
- mat/band_test.go
- mat/dense.go
- mat/dense_test.go
- mat/diagonal.go
- mat/diagonal_test.go
- mat/symband.go
- mat/symband_test.go
- mat/symmetric.go
- mat/symmetric_test.go
- mat/triangular.go
- mat/triangular_test.go
- mat/triband.go
- mat/triband_test.go
> mat: Add DiagView methods to types

- AUTHORS
- CONTRIBUTORS
> Request to add myself to the Author and Contributors list.

- blas/gonum/dgemm.go
- blas/gonum/sgemm.go
> blas: Remove variable copying in dgemm

- graph/encoding/dot/decode_test.go
- graph/encoding/dot/encode.go
> graph/encoding/dot: run go fmt -s

- mat/diagonal.go
- mat/diagonal_test.go
- optimize/cmaes.go
- stat/mds/mds.go
- stat/pca_test.go
> mat: rename NewDiagonal to NewDiagDense

- floats/floats.go
- floats/floats_test.go
> floats: Implement ScaleTo

- optimize/cmaes_test.go
- optimize/functionconvergence.go
- optimize/global.go
- optimize/listsearch_test.go
- optimize/local_example_test.go
- optimize/minimize.go
- optimize/types.go
- optimize/unconstrained_test.go
> optimize: make function converger an interface

- internal/asm/f64/ge_noasm.go
- lapack/gonum/dlauu2.go
- lapack/gonum/dlauum.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dlauu2.go
- lapack/testlapack/dlauum.go
> lapack/gonum: add Dlauu2 and Dlauum

- graph/graph.go
Now it follows the convention of golint, should users
copy the comment for their own concrete implementation.
> graph: update comment of AddNode in NodeAdder interface

- stat/pca_cca.go
The previous comment matched the API that existed previously, but was not updated.
> stat: update doc comment to match current behaviour

- stat/distmv/studentst.go
> stat/distmv: Update Student's T to use Mahalanobis

- mathext/gamma_inc.go
- mathext/gamma_inc_inv.go
- mathext/gamma_inc_test.go
- stat/distuv/chisquared.go
- stat/distuv/gamma.go
- stat/distuv/inversegamma.go
- stat/distuv/poisson.go
> mathext: Rename GammaInc and friends to GammaIncReg

- stat/distuv/bernoulli_test.go
- stat/distuv/beta_test.go
- stat/distuv/binomial_test.go
- stat/distuv/chisquared_test.go
- stat/distuv/distribution_test.go
- stat/distuv/exponential_test.go
- stat/distuv/gamma_test.go
- stat/distuv/inversegamma_test.go
- stat/distuv/laplace_test.go
- stat/distuv/lognormal_test.go
- stat/distuv/norm_test.go
- stat/distuv/poisson_test.go
- stat/distuv/studentst_test.go
- stat/distuv/triangle_test.go
- stat/distuv/uniform_test.go
- stat/distuv/weibull_test.go
Updates the tests to use a consistent form, and adds tests to a few distributions that are missing them.
Fixes #182.
> stat/distuv: canonicalize stat tests

- blas/gonum/cmplx.go
- blas/gonum/level1cmplx128.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level3cmplx128.go
- blas/gonum/level3cmplx128_test.go
- blas/gonum/level3double.go
- blas/gonum/level3single.go
- blas/testblas/common.go
- blas/testblas/dsyrk.go
- blas/testblas/zgemm.go
- blas/testblas/zherk.go
- blas/testblas/zsyrk.go
Also fixes a bug in Dsyrk.
Updates #185 
> blas/gonum: add Zgemm, Zsyrk, and Zherk

- AUTHORS
- CONTRIBUTORS
> A+C: add Christophe Meessen

- blas/gonum/cmplx.go
- blas/gonum/level3cmplx128.go
- blas/gonum/level3cmplx128_test.go
- blas/testblas/zher2k.go
- blas/testblas/zsyr2k.go
> blas/gonum: add Zsyr2k and Zher2k

- graph/path/control_flow_lt.go
- graph/path/control_flow_test.go
> path: use node ID in dominator tree for node retrieval

- graph/path/control_flow_test.go
> graph/path: add dominator tree identity tests

- graph/encoding/dot/decode.go
- graph/encoding/dot/doc.go
- graph/encoding/dot/dot.go
- graph/encoding/dot/encode.go
Minor change in the docs to include the special case and to reduce repetition.
> graph/encoding/dot: refactor quoting docs

- blas/gonum/cmplx.go
- blas/gonum/level3cmplx128.go
- blas/gonum/level3cmplx128_test.go
- blas/gonum/level3double.go
- blas/gonum/level3single.go
- blas/testblas/common.go
- blas/testblas/zhemm.go
- blas/testblas/zsymm.go
> blas/gonum: add Zsymm and Zhemm

- graph/community/bisect_test.go
> graph/community: ensure exact test repeatability for examples

- lapack/gonum/dgetri.go
- lapack/testlapack/dgetri.go
... and extend its test, which uncovered these issues.
This completes the coverage of Dgetri mentioned in #806 .
This also shows that testing with various workspace sizes definitely makes sense.
> lapack/gonum: fix workspace usage bugs in Dgetri

- lapack/gonum/dgelqf.go
- lapack/gonum/dgeqrf.go
- lapack/testlapack/dgelqf.go
- lapack/testlapack/dgeqrf.go
- lapack/testlapack/dgetri.go
- lapack/testlapack/general.go
After a _quick_ grep I _think_ there shouldn't be more issues with `ldwork`.
> lapack/gonum: fix ldwork in Dgelqf and Dgeqrf

- diff/fd/laplacian_test.go
- floats/floats_test.go
- graph/network/diffusion_test.go
- stat/distuv/binomial.go
> all: fix mispellings

- graph/formats/gexf12/gexf_test.go
- graph/network/hits.go
- lapack/gonum/dbdsqr.go
- lapack/gonum/dlasq2.go
- lapack/gonum/dtrevc3.go
- mat/product_test.go
I have left cephes and amos as is.
> all: remove ineffectual assignments

- mat/band.go
- mat/band_test.go
- mat/dense.go
- mat/dense_test.go
- mat/diagonal.go
- mat/diagonal_test.go
- mat/symband.go
- mat/symband_test.go
- mat/symmetric.go
- mat/symmetric_test.go
- mat/triangular.go
- mat/triangular_test.go
- mat/triband.go
- mat/triband_test.go
- mat/vector.go
- mat/vector_test.go
> mat: Add Zero method to reset values of matrices

- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected_test.go
> graph/multi: remove redundant nil guards

- graph/multi/directed_test.go
- graph/multi/undirected.go
- graph/multi/undirected_test.go
- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected.go
- graph/multi/weighted_undirected_test.go
- graph/simple/densegraph_test.go
- graph/simple/directed_test.go
- graph/simple/undirected_test.go
- graph/simple/weighted_directed_test.go
- graph/simple/weighted_undirected_test.go
- graph/testgraph/testgraph.go
- graph/testgraph/testgraph_test.go
> graph/{multi,simple,testgraph}: add graph mutation tests

- stat/distuv/weibull.go
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
> stat/distuv: fix duplicated assignment

- mat/band_test.go
- mat/dense_test.go
- mat/diagonal_test.go
- mat/symband_test.go
- mat/symmetric_test.go
- mat/triangular_test.go
- mat/triband_test.go
- mat/vector_test.go
> mat: run gofmt -s -w

- mat/svd.go
> mat: update documentation for SVD

- mat/cholesky.go
> mat: check validity in Cholesky.Cond

- bound/bound.go
- bound/doc.go
- stat/distmv/statdist.go
- stat/distmv/statdist_test.go
- stat/distmv/uniform.go
- stat/distmv/uniform_test.go
- stat/samplemv/sample_test.go
> bound: add Bound package and type

- mat/cdense.go
- mat/cdense_test.go
- mat/cmatrix.go
- mat/index_bound_checks.go
- mat/index_no_bound_checks.go
> mat: Add CDense type and basic methods

- blas/gonum/dgemm.go
- blas/gonum/gemv.go
- blas/gonum/level1double_ddot.go
- blas/gonum/level1single_dsdot.go
- blas/gonum/level1single_sdot.go
- blas/gonum/level1single_sdsdot.go
- blas/gonum/level2cmplx128.go
- blas/gonum/level2double.go
- blas/gonum/level2single.go
- blas/gonum/level3cmplx128.go
- blas/gonum/level3double.go
- blas/gonum/level3single.go
- blas/gonum/sgemm.go
- blas/gonum/single_precision.bash
Also, avoid unnecessary use of ...To routines.
> blas/gonum: slice arguments to exact length

- README.md
> README: use the correct semver terminology for version numbering

- mat/eigen.go
> mat: Fix Eigen documentation

- mat/eigen.go
> mat: update documentation for Eigen

- num/dual/dual.go
- num/dualquat/dual.go
- num/hyperdual/hyperdual.go
- num/quat/quat.go
- num/quat/quat_test.go
> num: add field names to Go syntax printing of types

- num/dual/dual.go
- num/dual/dual_test.go
- num/dualquat/dual.go
- num/dualquat/dual_test.go
- num/hyperdual/hyperdual.go
- num/hyperdual/hyperdual_test.go
- num/quat/quat.go
- num/quat/quat_test.go
A nice example of why even trivial code wants tests.
> num: add %+v support to Format method, extend tests and fix found bug

- graph/internal/set/set.go
- graph/internal/set/set_test.go
There are issues here that I'm not happy with, but I'm not sure how to deal with them. I will leave them for now since this is internal.
> graph/internal/set: improve test coverage and docs

- graph/graph_test.go
- graph/nodes_edges_test.go
> graph: improve slicer help function coverage

- .travis.yml
- appveyor.yml
- num/dual/dual.go
- num/dualquat/dual.go
- num/hyperdual/hyperdual.go
- num/quat/quat.go
> ci: update supported versions

- CONDUCT.md
This merely exists to make sure automated tools (for example [here](https://github.com/gonum/gonum/community)) and cursory glances of the repo see that we care about this kind of thing.
I have retained the optimistic name and refrained from using the prescriptive term "Code".
This needs a quorum of approvers. I don't know how big.
> CONDUCT: add a CONDUCT document

- CONDUCT.md
- CONTRIBUTING.md
> CONTRIBUTING: link to CONDUCT.md rather than repeating

- doc.go
- version.go
> gonum: add Version query function

- AUTHORS
- CONTRIBUTORS
> A+C: add Kirill Motkov

- num/dualquat/dual_example_test.go
> dualquat: fix example documentation

- graph/formats/dot/testdata/Makefile
> graph/formats/dot/testdata: don't clone the full history

- .travis.yml
- graph/formats/dot/internal/errors/errors.go
- graph/formats/dot/internal/parser/parser.go
> graph/formats/dot,travis: update gocc version

- graph/flow/control_flow_bench_test.go
- graph/flow/control_flow_lt.go
- graph/flow/control_flow_slt.go
- graph/flow/control_flow_test.go
- graph/flow/doc.go
This PR does the initial movement from #796. It is happening here so we can get the API breakage done now, allowing the additions to come later at a more relaxed pace.
> graph/flow: new package for (control) flow analysis

- graph/graph.go
> graph: use src edges in dst graph

- graph/community/k_communities.go
- graph/graphs/gen/batagelj_brandes_test.go
- graph/internal/set/set.go
- graph/internal/set/set_test.go
- graph/multi/directed_test.go
- graph/multi/undirected_test.go
- graph/multi/weighted_directed_test.go
- graph/multi/weighted_undirected_test.go
- graph/simple/densegraph_test.go
- graph/simple/directed_test.go
- graph/simple/undirected_test.go
- graph/simple/weighted_directed_test.go
- graph/simple/weighted_undirected_test.go
- graph/testgraph/testgraph.go
- graph/topo/bron_kerbosch.go
- graph/topo/clique_graph.go
> graph/internal/set: make Nodes creation a function

- mat/dense_test.go
> mat: fix test for changes in Go runtime

- unit/unittype.go
I found the absence of these irritating when I was working on the recent changes.
> unit: add dimension and value accessor methods

- .travis/install-gocc.sh
> travis: remove gocc go.mod work around

- .github/ISSUE_TEMPLATE/bug_report.md
> github: ask for module version information

- mat/consts.go
- mat/eigen.go
- mat/eigen_example_test.go
- mat/eigen_test.go
- mat/gsvd.go
- mat/hogsvd.go
- mat/svd.go
> mat: change factorization inputs to use bit types

- mat/cholesky.go
> mat: conform receiver name to convention

- mat/lq.go
- mat/lu.go
- mat/qr.go
> mat: panic informatively with unfactorised values for LQ, LU and QR

- lapack/gonum/lapack_test.go
- lapack/testlapack/dgesvd.go
> lapack/testlapack: make DgesvdTest take a tolerance parameter

- stat/distuv/triangle.go
- stat/distuv/triangle_test.go
> stat/distuv: use NewTriangle to set random source

- .travis.yml
> travis: move import checks before tests

- mat/band.go
- mat/diagonal.go
- mat/matrix_test.go
- mat/symband.go
- mat/triband.go
Please take a look.  Similar to https://github.com/gonum/gonum/issues/938.
> mat: tracer for band types

- mat/cholesky.go
> mat: make Cholesky.SetFromU take a Triangular

- stat/distmv/dirichlet.go
- stat/distmv/general_test.go
- stat/distmv/normal.go
- stat/distmv/normal_test.go
- stat/distmv/normalbench_test.go
- stat/distmv/studentst.go
- stat/distmv/studentst_test.go
- stat/samplemv/sample_test.go
- stat/statmat.go
- stat/statmat_test.go
> stat,stat/distmv: don't allocate matrix on nil input

- AUTHORS
- CONTRIBUTORS
- bound/bound.go
- bound/bound_test.go
Add Intersection helper API for bound package
Updates: #939
> bound: Add Intersection helper for bound package

- appveyor.yml
> appveyor: add go1.12 version tests

- diff/fd/hessian.go
- diff/fd/hessian_test.go
- optimize/functions/functions.go
- optimize/linesearcher_test.go
- optimize/minimize.go
- optimize/types.go
> diff/fd,optimize: don't allocate matrix on nil input to fd.Hessian and use mat.SymDense in optimize

- .travis.yml
- .travis/script.d/check-generate.sh
- .travis/script.d/deps.sh
> travis: check for needed changes in go.mod and go.sum

- optimize/types.go
> optimize: fix doc comments for Grad and Hess fields of Problem

- spatial/kdtree/kdtree_test.go
- spatial/kdtree/medians.go
> kdtree: clean up benchmarks, docs and partitioning routines

- num/dualcmplx/doc.go
- num/dualcmplx/dual.go
- num/dualcmplx/dual_example_test.go
- num/dualcmplx/dual_simple_example_test.go
- num/dualcmplx/dual_test.go
> num/dualcmplx: package for dual complex maths

- lapack/gonum/lapack.go
> lapack/gonum: add TODO for dlamchE and dlamchS literals

- AUTHORS
- CONTRIBUTORS
Per request from @kortschak related to [HDF5 wrapper PR](https://github.com/gonum/hdf5/pull/50) I added my name to both `AUTHORS` and `CONTRIBUTORS`
> A+C: add Delaney Gillilan

- .github/ISSUE_TEMPLATE/bug_report.md
> github: add note about using play.golang.org

- spatial/vptree/doc.go
- spatial/vptree/vptree.go
- spatial/vptree/vptree_simple_example_test.go
- spatial/vptree/vptree_test.go
- spatial/vptree/vptree_user_type_example_test.go
> spatial/vptree: new package for vantage point tree NN search

- mat/dense_arithmetic.go
This is a clean up which will help (with #987) allow fast paths for general `RawVectorer` types.
> mat: replace sequential conditional assertions with type switch

- mat/shadow.go
> mat: check RawVectorers for shadowing and special case unit increments

- mat/vector_example_test.go
> mat: add user vector type example

- mat/dense_arithmetic.go
- mat/inner.go
- mat/symmetric.go
If I've missed any please let me know.
Fixes #388.
> mat: relax restrictions on vector orientation

- unit/unittype.go
> unit: fix typo

- mat/dense.go
- mat/dense_test.go
- mat/eigen.go
- mat/hogsvd.go
- mat/list_test.go
- mat/lq.go
- mat/lq_test.go
- mat/lu_test.go
- mat/matrix.go
- mat/product_test.go
- mat/qr.go
- mat/qr_test.go
- optimize/convex/lp/simplex_test.go
- stat/cca_example_test.go
- stat/statmat.go
> mat: rename Cloner=>ClonerFrom and Clone=>CloneFrom

- lapack/gonum/dlange.go
- lapack/gonum/dpbtf2.go
- lapack/gonum/dpbtrf.go
- lapack/gonum/ilaenv.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dpbtf2.go
- lapack/testlapack/dpbtrf.go
- lapack/testlapack/general.go
> lapack/gonum: add Dpbtrf

- lapack/gonum/dpbtf2.go
- lapack/gonum/dpbtrs.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dpbtf2.go
- lapack/testlapack/dpbtrf.go
- lapack/testlapack/dpbtrs.go
- lapack/testlapack/general.go
> lapack/gonum: add Dpbtrs

- go.mod
After discussion [here](https://groups.google.com/d/topic/golang-nuts/JNVpE6ONzPU/discussion) this seems to be correct.
> modules: fix expected language version directive

- stat/combin/combin_example_test.go
> stat/combin: add example for Combinations

- mat/symmetric.go
- mat/triangular.go
> mat: set caps when raw matrix is set

- stat/stat.go
> stat: fix spelling and punctuation in stat.go

- .travis.yml
- .travis/script.d/test-coverage.sh
I'm so glad we support Windows.
> travis: make conditional test coverage analysis work again

- mat/dense.go
- mat/dense_arithmetic.go
- mat/symmetric.go
- mat/vector.go
This leaves one remaining use in TriDense but that case is a bit more complicated
> mat: replace untranspose with untransposeExtract

- lapack/gonum/dpbcon.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dpbcon.go
> lapack/gonum: add Dpbcon

- mat/io.go
- mat/io_test.go
> mat: move sizeInt64 to testing file to quieten unused

- mat/lq.go
- mat/qr.go
Fix comment and make code format consistent with QR.
> mat: clarify LQ

- mat/matrix.go
> mat: panic with the advertised value for invalid norm order

- mat/dense_test.go
> mat: fix benchmark typo

- lapack/gonum/dcombssq.go
- lapack/gonum/dlansb.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dcombssq.go
- lapack/testlapack/dlansb.go
- lapack/testlapack/dlassq.go
- lapack/testlapack/dpbcon.go
> lapack/gonum: add Dlansb

- lapack/gonum/dlange.go
- lapack/gonum/dlansy.go
- lapack/gonum/dlantr.go
> lapack/gonum: use Dcombssq (and Dlassq) in Dlange, Dlansy, Dlantr

- lapack/gonum/dlantr.go
- lapack/testlapack/dlantr.go
- lapack/testlapack/dtrcon.go
- lapack/testlapack/dtrtri.go
> lapack/{gonum,testlapack}: fix Dlantr for unit lower triangular matrices, rework tests for Dtrcon and Dlantr

- stat/combin/combin.go
- stat/combin/combin_test.go
> combin: Change Cartesian to deal with indices

- blas/blas32/conv.go
- blas/blas64/conv.go
- blas/cblas128/conv.go
- blas/cblas64/conv.go
> blas: fix copy paste error

- graph/path/bench_test.go
> graph/path: clean up AStar benchmarks with subtests

- graph/path/johnson_apsp.go
> graph/path: use the type system to differentiate behaviours

- mat/vector.go
This was missed in a8659125a966ededbf81ce1953b1927eff4ecfca.
> mat: remove redundant check constructions

- mat/list_test.go
- mat/pool.go
> mat: fix staticcheck lint

- graph/multi/directed.go
- graph/multi/undirected.go
- graph/multi/weighted_directed.go
- graph/multi/weighted_undirected.go
- spatial/kdtree/points.go
> all: gofmt -s

- graph/internal/set/set_test.go
- graph/layout/layout_test.go
- lapack/gonum/dpbtrs.go
- mat/io_test.go
- optimize/bfgs.go
- optimize/cg.go
- stat/distuv/inversegamma.go
> all: address issues identified by golangci-lint

- stat/combin/combin.go
- stat/combin/combin_test.go
- stat/combin/combinations_example_test.go
> combin: Add helpers for dealing with permutations

- mat/band.go
- mat/cdense.go
- mat/cholesky.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/diagonal.go
- mat/doc.go
- mat/eigen.go
- mat/errors.go
- mat/gsvd.go
- mat/hogsvd.go
- mat/io.go
- mat/lq.go
- mat/lu.go
- mat/matrix.go
- mat/product.go
- mat/qr.go
- mat/solve.go
- mat/svd.go
- mat/symband.go
- mat/symmetric.go
- mat/triangular.go
- mat/triband.go
- mat/vector.go
> mat: Expose ReuseAs method to help resizing

- AUTHORS
- CONTRIBUTORS
Hi, this PR is for adding me to the A+C.
> A+C: add Yucheng Zhu

- mat/cdense.go
- mat/cholesky.go
- mat/cholesky_example_test.go
- mat/cholesky_test.go
- mat/dense.go
- mat/eigen.go
- mat/eigen_example_test.go
- mat/eigen_test.go
- mat/gsvd.go
- mat/gsvd_example_test.go
- mat/gsvd_test.go
- mat/hogsvd.go
- mat/hogsvd_example_test.go
- mat/hogsvd_test.go
- mat/lq.go
- mat/lq_test.go
- mat/lu.go
- mat/lu_test.go
- mat/qr.go
- mat/qr_test.go
- mat/svd.go
- mat/svd_test.go
- mat/symmetric.go
- mat/triangular.go
- mat/vector.go
- stat/pca_cca.go
While here, fix enough to compile.
Updates #1081.
> mat: Change methods to accept empty instead of nil matrices

- optimize/gradientdescent.go
> optimize: remove redundant return

- mat/cholesky.go
- stat/distmat/wishart.go
> mat: make SetFromU panic on non-empty size mismatch

- mat/shadow.go
- mat/vector.go
> mat: add fastpath for SymBandDense to VecDense.MulVec

- integrate/trapezoidal.go
> integrate: fix doc comment for Trapezoidal

- AUTHORS
- CONTRIBUTORS
> A+C: add Nils Wogatzky

- graph/layout/isomap.go
- stat/cca_example_test.go
- stat/cca_test.go
- stat/mds/mds.go
- stat/mds/mds_test.go
- stat/pca_cca.go
- stat/pca_example_test.go
- stat/pca_test.go
> stat/*: Update functions to take empty matrices

- optimize/lbfgs.go
- optimize/neldermead.go
- optimize/newton.go
> optimize: remove redundant returns

- integrate/simpsons.go
- integrate/simpsons_test.go
This pull request (carried on from #1100) is a Simpson's method implementation for #400.
> integrate: add simpson's rule

- AUTHORS
- CONTRIBUTORS
I've added myself to AUTHORS and CONTRIBUTORS to merge #1107 .
> A+C: add Nathan Edwards

- .travis.yml
> travis: run both Go versions on osx and windows

- stat/combin/combin.go
- stat/combin/combin_test.go
- stat/combin/combinations_example_test.go
this fixes #308 according to the existing generator API.
Fixes #308.
> stats/combin: add CartesianGenerator

- README.md
> README: fix wording for Go version and OS support

- graph/encoding/dot/encode.go
> graph/encoding/dot: remove linty cruft

- mat/dense_example_test.go
> mat: use returned err for example code

- integrate/romberg.go
- integrate/romberg_test.go
- integrate/simpsons.go
- integrate/simpsons_test.go
- integrate/testquad/testquad.go
- integrate/trapezoidal.go
- integrate/trapezoidal_test.go
> integrate: rework tests, clean up docs and code

- README.md
> gonum: add release schedule

- integrate/simpsons.go
- integrate/simpsons_test.go
> integrate: small cleanup in Simpsons

- unit/unit_test.go
- unit/unittype.go
> unit: don't panic when multiplying dimless with dimensioned Uniter

- stat/combin/combin.go
- stat/combin/combin_test.go
- stat/combin/combinations_example_test.go
> combin: Cartesian fixes

- stat/combin/combin.go
> stat/combin: fix incorrect bound

- graph/topo/topo.go
- graph/topo/topo_test.go
> graph/topo: add Equal test for graph topology equality comparison

- graph/community/louvain_directed_test.go
- graph/community/louvain_undirected_test.go
This removes lint found by golangci.
> graph/community: remove lint

- graph/product/doc.go
- graph/product/product.go
- graph/product/product_example_test.go
- graph/product/product_test.go
> graph/product: new package for constructing graph products

- graph/product/doc.go
- graph/product/product.go
- graph/product/product_example_test.go
> graph/product: improve documentation

- graph/complement.go
- graph/complement_test.go
- graph/export_test.go
- graph/undirect.go
- graph/undirect_test.go
> graph: add capacity to produce graph complement

- internal/asm/f64/sum_amd64.s
This won't completely fix #79, but the other complaints are being fixed in vet, so this is as much as we can do.
Fixes #79.
> internal/asm/f64: fix vet issue

- num/dual/dual.go
- num/dual/dual_test.go
- num/dualcmplx/dual.go
- num/dualcmplx/dual_test.go
- num/dualquat/dual.go
- num/dualquat/dual_test.go
- num/hyperdual/hyperdual.go
- num/hyperdual/hyperdual_test.go
Lint identified by golangci-lint.
The remaining two issues in this part of the tree are false positives.
> num: clean up lint

- unit/unit_test.go
> unit: clean up lint

- mat/cholesky_test.go
- mat/dense_arithmetic.go
- mat/io_test.go
- mat/list_test.go
- mat/lq_test.go
- mat/qr_test.go
- mat/solve_test.go
- mat/symmetric.go
- mat/symmetric_test.go
- mat/triangular.go
There's still a fair bit here, but I am just going to leave it for now.
> mat: clean up lint

- optimize/convex/lp/simplex_test.go
- optimize/guessandcheck_test.go
- optimize/newton.go
> optimize: clean up lint

- spatial/barneshut/galaxy_example_test.go
> spatial/barneshut: clean up lint

- lapack/testlapack/dlahr2.go
- lapack/testlapack/dlaqr5.go
- lapack/testlapack/fortran.go
- lapack/testlapack/general.go
> testlapack: clean up lint

- graph/network/diffusion.go
- graph/network/diffusion_test.go
- graph/spectral/doc.go
- graph/spectral/laplacian.go
- graph/spectral/laplacian_test.go
Initial commit to this is just a move of the Laplacian type from network. This is intended to make room for more of this kind of thing and make it more discoverable than it was where it was previously.
> spectral: new package for spectral graph analysis

- graph/product/product.go
- graph/product/product_ext_example_test.go
- graph/product/product_test.go
ISTM this is too open to test in a more specific way.
> graph/product: add extended modular product function

- unit/absorbedradioactivedose_test.go
- unit/acceleration_test.go
- unit/angle_test.go
- unit/area_test.go
- unit/capacitance_test.go
- unit/charge_test.go
- unit/conductance_test.go
- unit/current_test.go
- unit/energy_test.go
- unit/equivalentradioactivedose_test.go
- unit/force_test.go
- unit/frequency_test.go
- unit/generate_unit.go
- unit/inductance_test.go
- unit/length_test.go
- unit/luminousintensity_test.go
- unit/magneticflux_test.go
- unit/magneticfluxdensity_test.go
- unit/mass_test.go
- unit/mole_test.go
- unit/power_test.go
- unit/pressure_test.go
- unit/radioactivity_test.go
- unit/resistance_test.go
- unit/temperature_test.go
- unit/time_test.go
- unit/torque_test.go
- unit/velocity_test.go
- unit/voltage_test.go
- unit/volume_test.go
> unit: cover unit conversion code

- stat/cca_example_test.go
- stat/distmv/normal.go
- stat/distmv/normal_test.go
- stat/distmv/statdist.go
- stat/distmv/statdist_test.go
- stat/distmv/studentst_test.go
- stat/distmv/uniform_test.go
- stat/sampleuv/example_rate_test.go
- stat/spatial/spatial_areal_example_test.go
> stat: clean up lint

- stat/card/card.go
- stat/card/card_test.go
- stat/card/hll32.go
- stat/card/hll64.go
> stat/card: fix rho functions

- mat/matrix.go
- mat/vector.go
> mat: add VecDense and RawVectorer cases to untransposeExtract

- mat/eigen.go
- mathext/internal/cephes/cephes.go
- mathext/internal/cephes/igam.go
- mathext/internal/cephes/igami.go
- mathext/internal/cephes/incbeta.go
- mathext/internal/cephes/ndtri.go
- mathext/internal/cephes/zeta.go
- optimize/convex/lp/simplex.go
- optimize/errors.go
- optimize/functions/doc.go
- stat/combin/combin.go
- stat/distmat/general.go
- stat/distmv/general.go
- stat/distmv/normal.go
- stat/distuv/general.go
- stat/distuv/laplace.go
- stat/samplemv/metropolishastings.go
- stat/samplemv/samplemv.go
- stat/sampleuv/sample.go
This was discussed in a PR in stat a fair while back.
> all: remove redundant bad prefix and make panic strings const

- lapack/testlapack/dsterf.go
> lapack/testlapack: clean up DsterfTest

- graph/path/dijkstra_test.go
- graph/path/shortest.go
> graph/path: make sure absent nodes are returned with the correct ID

- lapack/testlapack/dlasq1.go
- lapack/testlapack/dsterf.go
> lapack/testlapack: rework test for Dlasq1

- stat/card/card_test.go
- stat/card/hll32.go
- stat/card/hll64.go
> stat/card: add sketch serialisation

- mat/dense_arithmetic.go
- mat/dense_test.go
> mat: add Kronecker product function

- mat/cholesky_test.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/gsvd.go
- mat/symmetric.go
- mat/symmetric_test.go
> mat: provide internal slice methods that return the concrete types

- mathext/prng/prng_di_unimi.go
> mathext/prng: fix copy/paste typo

- CONTRIBUTING.md
> docs: fix link to LICENSE file

- internal/math32/sqrt_amd64.s
> internal/math32: clean up asm includes and build constraints

- internal/asm/f32/dot_test.go
- internal/asm/f32/ge_test.go
- internal/asm/f32/l2norm_test.go
- internal/asm/f32/stubs_test.go
- internal/asm/f32/util_test.go
- internal/asm/f64/asm_test.go
- internal/asm/f64/axpy_test.go
- internal/asm/f64/benchAxpy_test.go
- internal/asm/f64/benchScal_test.go
- internal/asm/f64/bench_other_test.go
- internal/asm/f64/dot_test.go
- internal/asm/f64/ge_test.go
- internal/asm/f64/gemv_test.go
- internal/asm/f64/l2norm_test.go
- internal/asm/f64/scal_test.go
- internal/asm/f64/stubs_test.go
See https://github.com/gonum/gonum/pull/1217#issuecomment-573459719.
> asm: clean up tolerant testing

- stat/roc.go
- stat/roc_test.go
- stat/stat_example_test.go
- stat/statmat_test.go
Please take a look (check test log since these are currently allowed failures).
Updates #1218.
> stat: fix failures on arm64

- lapack/testlapack/dgeev.go
- lapack/testlapack/dlaln2.go
- lapack/testlapack/dlansb.go
- lapack/testlapack/dlascl.go
> testlapack: adjust some tolerances

- AUTHORS
- CONTRIBUTORS
> A+C: update name/contact

- lapack/gonum/dgeev.go
- lapack/testlapack/dgeev.go
> testlapack: rework eigenvector checks in DgeevTest and adjust tolerances

- lapack/gonum/dlarf.go
- lapack/testlapack/dlarf.go
>  lapack/gonum: clean up Dlarf and its docs, and rework its test

- lapack/gonum/dtrevc3.go
- lapack/testlapack/dgeev.go
- lapack/testlapack/dtrevc3.go
- lapack/testlapack/dtrexc.go
- lapack/testlapack/general.go
> lapack/gonum,testlapack: fix bug in Dtrevc3 and rework its test

- lapack/gonum/dlanv2.go
> lapack/gonum: fix Dlanv2

- optimize/minimize.go
> optimize: fix typo

- optimize/minimize.go
> optimize: avoid unnecessary allocations for Gradient and Hessian

- optimize/minimize.go
> optimize: add doc comments for Location fields

- AUTHORS
- CONTRIBUTORS
> A+C: add Andrei Blinnikov to authors and contributors #1230

- optimize/listsearch.go
> optimize: fix doc comment typo

- optimize/unconstrained_test.go
> optimize: relax gradient tolerance for BFGS test

- optimize/backtracking.go
- optimize/bfgs.go
- optimize/bisection.go
- optimize/cg.go
- optimize/cmaes.go
- optimize/functionconvergence.go
- optimize/gradientdescent.go
- optimize/lbfgs.go
- optimize/morethuente.go
- optimize/newton.go
- optimize/printer.go
- optimize/stepsizers.go
> optimize: explicitly state interface satisfaction of types

- lapack/gonum/dlaset.go
> lapack: set strictly lower triangle in Dlaset

- optimize/functions/functions.go
> optimize/functions: fix BrownBadlyScaled for BFGS and LBFGS tests

- optimize/functions/functions.go
> optimize/functions: fix ExtendedRosenbrock for BFGS test

- lapack/testlapack/dgebak.go
- lapack/testlapack/dgebal.go
- lapack/testlapack/dgecon.go
- lapack/testlapack/dgeev.go
- lapack/testlapack/dhseqr.go
- lapack/testlapack/dlaln2.go
- lapack/testlapack/dlarfx.go
- lapack/testlapack/dlaset.go
- lapack/testlapack/dlatrs.go
- lapack/testlapack/dormhr.go
- lapack/testlapack/dsytrd.go
> testlapack: print byte constants as chars

- .travis.yml
- .travis/script.d/test-coverage.sh
> travis: require arm64 tests to pass

- README.md
> README: note supported architectures

- .travis.yml
- appveyor.yml
- go.mod
- lapack/gonum/lapack.go
- lapack/testlapack/general.go
> all: update for go1.14 release

- mat/matrix.go
> mat: document that Trace will use a Tracer's implementation

- mathext/internal/amos/amos_test.go
> mathext/internal/amos: use consistent random source

- num/dual/dual_example_test.go
- num/hyperdual/hyperdual_example_test.go
> num/dual: fix Number example

- mat/vector.go
> mat: add MutableVector interface

- mat/band.go
- mat/symband.go
- mat/vector.go
- optimize/bfgs.go
> mat: rename CloneVec to CloneFromVec

- mat/triangular.go
- mat/triangular_test.go
> mat: add TriDense.SliceTri

- AUTHORS
- CONTRIBUTORS
- README.md
closes #1274
Seeing how the badge looks next to the "Issues" heading
> add TODOs badge to "Issues" section of README

- mat/cholesky_test.go
- mat/dense_test.go
- mat/inner_test.go
- mat/list_test.go
- mat/lq_test.go
- mat/lu_test.go
- mat/mul_test.go
- mat/pool_test.go
- mat/product_test.go
- mat/qr_test.go
- mat/solve_test.go
- mat/svd_test.go
- mat/symmetric_test.go
- mat/triangular_test.go
- mat/vector_test.go
See https://github.com/gonum/gonum/pull/1288#issuecomment-599844471
> mat: don't use global rand state

- floats/floats.go
> floats: fix typo in Same documentation

- .travis/script.d/test-coverage.sh
- internal/testrand/extreme.go
- internal/testrand/extreme_test.go
- internal/testrand/extremes.go
- internal/testrand/rand.go
Testing package that allows seed randomization and setting a bias for extreme and nan values.
> internal/testrand: random package for testing

- lapack/lapack.go
- lapack/lapack64/lapack64.go
Preparation for adding BandCholesky.
> lapack64: add Pbtrf, Pbtrs, Lansb

- blas/gonum/level3cmplx128.go
- blas/gonum/level3cmplx64.go
- blas/gonum/level3float32.go
- blas/gonum/level3float64.go
- blas/testblas/common.go
- blas/testblas/dsymm.go
- blas/testblas/dsyr2k.go
- blas/testblas/zhemm.go
- blas/testblas/zsymm.go
- blas/testblas/zsyrk.go
- mat/list_test.go
Updates #1293 (there may be other cases of this that the mat tests have not found).
> blas/gonum,mat: handle NaN in destination matrices

- spatial/r3/vector.go
- spatial/r3/vector_test.go
> spatial/r3: Vec API

- spatial/r2/vector.go
- spatial/r2/vector_test.go
> R2 vec api

- AUTHORS
- CONTRIBUTORS
See https://go-review.googlesource.com/c/tools/+/226285 regarding use of the accent.
> A+C: fix typo in Renee French's name

- AUTHORS
- CONTRIBUTORS
As requested per pull request for gonum/hdf5 change
> A+C: add Jon Richards

- mat/svd.go
- mat/svd_test.go
> mat: fix typo in SVD VTo check

- mat/format.go
- mat/format_example_test.go
- mat/format_test.go
~WIP: Needs tests.~
Updates #740.
> mat: provide mechanism to output Python and MATLAB syntax

- mathext/internal/amos/amos_fortran_test.go
- mathext/internal/amos/amoslib/fortran.go
> amoslib: remove stale TODO and document package

- .travis/script.d/check-generate.sh
> travis: reset tree before the generate check

- .travis/script.d/deps.sh
golangci-lint now has a recommended source install.
> travis: install golangci-lint from source

- CONTRIBUTORS
A+C: add Roman Werpachowski
AUTHORS file already contains my employer (DeepMind Technologies).
> A+C: add Roman Werpachowski

- stat/distuv/categorical_test.go
This change modifies the stat/distuv package in Gonum to:
- improve test coverage for Categorical distribution
- add benchmarks for Rand function on Categorical
> stat/distuv: Improve test coverage for Categorical distribution

- stat/distuv/chisquared.go
- stat/distuv/chisquared_test.go
This change modifies Gonum to:
- provide 100% test coverage to `ChiSquared`
- fix `Mode` method on this struct
> stat/distuv: ChiSquared test improvements & fix for Mode

- stat/distuv/interfaces.go
> stat/distuv: Add documentation to `interfaces.go`

- .github/FUNDING.yml
> github: add FUNDING.yml

- stat/distuv/exponential.go
- stat/distuv/exponential_test.go
- stat/distuv/general_test.go
- stat/distuv/norm.go
- Added tests to `exponential_test.go`
- Factored out some tests to `general_test.go` so that they're used for other distributions which are `ConjugateUpdater`
- fixed `Norm` so that it passes the new tests
> stat/distuv: Improve Exponential test coverage and factor out some tests.

- CONTRIBUTING.md
> CONTRIBUTING: update link to moved patch review article

- stat/distuv/distribution_test.go
- stat/distuv/f.go
- stat/distuv/f_test.go
Also added a function `checkMode` to `distribution_test.go` which compares the analytic and estimated mode.
> stat/distuv: provide complete test coverage for F distribution

- stat/distuv/gamma_test.go
- stat/distuv/gumbel_test.go
- stat/distuv/inversegamma_test.go
- stat/distuv/laplace_test.go
- stat/distuv/lognormal.go
- stat/distuv/lognormal_test.go
- stat/distuv/norm_test.go
- stat/distuv/pareto_test.go
- stat/distuv/studentst_test.go
- stat/distuv/triangle_test.go
- stat/distuv/weibull.go
- stat/distuv/weibull_test.go
1. Adds tests for Mode function where missing.
2. Fixes a bug in lognormal Mode.
3. Fixes a bug in Weibull Mode.
> stat/distuv: Add missing tests for Mode and fix bugs in some implementations

- graph/path/shortest.go
> graph/path: clean up Shortest

- stat/distuv/categorical_test.go
- stat/distuv/gamma_test.go
> stat/distuv: run tests in parallel

- stat/distuv/gumbel.go
- stat/distuv/gumbel_test.go
> stat/distuv: provide complete Gumbel test coverage and fix its documentation

- mathext/gamma_inc.go
> mathext: provide the correct formula in documentation for GammaIncRegComp

- stat/distuv/inversegamma.go
- stat/distuv/inversegamma_test.go
> stat/distuv: provide complete InverseGamma test coverage

- stat/distuv/general_test.go
- stat/distuv/laplace.go
- stat/distuv/laplace_test.go
- stat/distuv/triangle.go
- stat/distuv/triangle_test.go
- stat/distuv/uniform.go
- stat/distuv/uniform_test.go
Also tests and fix Laplace Score.
> stat/distuv: add Score method to Triangle and Uniform

- mat/solve.go
> mat: clarify docs for Dense.Solve and VecDense.SolveVec

- stat/distuv/lognormal_test.go
> stat/distuv: provide complete test coverage for LogNormal distribution

- graph/path/bellman_ford_moore.go
> graph/path: fix comments in BellmanFordFrom

- graph/path/a_star_test.go
- graph/path/bellman_ford_moore_test.go
- graph/path/dijkstra_test.go
> graph/path: fix error messages

- stat/distuv/pareto.go
- stat/distuv/pareto_test.go
Also fixes a bug in Pareto ExKurtosis, simplifies the implementation of Pareto Survival and improves the accuracy of Pareto CDF for x ~= xM.
> stat/distuv: provide complete test coverage for Pareto distribution and implement Pareto Quantile function

- graph/path/internal/testgraphs/shortest.go
> graph/path/internal: add more negative cycle cases

- stat/distuv/studentst.go
- stat/distuv/studentst_test.go
> stat/distuv: fix a bug in StudentsT.Variance and provide full test coverage

- dsp/window/doc.go
> dsp/window: add comment explaining origin of documentation

- stat/distuv/statdist.go
- stat/distuv/statdist_test.go
> stat/distuv: provide full test coverage for statdist.go and increase numerical accuracy of Hellinger distance

- .github/workflows/golangci-lint.yml
> ci: update golangci-lint version to latest

- graph/path/dynamic/dstarlite.go
> graph/path/dynamic: update linting

- mat/svd.go
This updates the documentation as promised in #1316.
> mat: update docs for SVD.SolveTo and SVD.SolveVecTo

- graph/path/bellman_ford_moore.go
- graph/path/shortest.go
> graph/path: add doc comments for unexported path construction methods

- stat/distuv/alphastable.go
- stat/distuv/alphastable_test.go
Implements sampling from a general alpha-stable distribution and some basic distribution properties when possible.
> stat/distuv: add AlphaStable distribution

- stat/distuv/triangle_test.go
> stat/distuv: full test coverage for Triangle distribution

- stat/distuv/weibull.go
- stat/distuv/weibull_test.go
Also completes test coverage for Weibull.
> stat/distuv: fix CDF and score functions for Weibull distribution

- mat/doc.go
> mat: add note about layout and performance

- stat/distmat/permutation.go
- stat/distmat/permutation_test.go
Simple wrapper to generate random permutation matrices build around math/rand/Shuffle.
> stat/distmat: add UniformPermutation

- cmplxs/cmplxs.go
- cmplxs/cmplxs_test.go
> cmplxs: add Real, Imag and Complex functions

- cmplxs/cmplxs.go
- floats/floats.go
> cmplxs,floats: harmonise docs and panic strings

- .travis.yml
- appveyor.yml
- go.mod
- version.go
> ci: bump travis, appveyor and module versions

- lapack/testlapack/dlarf.go
- lapack/testlapack/dlauu2.go
- lapack/testlapack/dlauum.go
- lapack/testlapack/dpotri.go
- lapack/testlapack/dtrevc3.go
- lapack/testlapack/general.go
> testlapack: use helpers to name sub-tests

- stat/distmat/general.go
- stat/distmat/unit_vector.go
- stat/distmat/unit_vector_example_test.go
- stat/distmat/unit_vector_test.go
Adds a UnitVector distribution.  This is a uniform distribution over the surface of a sphere.
> stat/distmat: UnitVector, uniform distribution over surface of n-sphere

- AUTHORS
- CONTRIBUTORS
> A+C: add Brandon Dube

- mat/product_test.go
> mat: fix build for 32-bit architectures

- mat/vector.go
> mat: don't clobber optimisation for TriDense matrix input

- AUTHORS
- CONTRIBUTORS
- dsp/window/window.go
- dsp/window/window_complex.go
- dsp/window/window_test.go
This removes materials which are or may reasonably be believed to be the intellectual property of @brandondube.
> dsp/window: revert tukey

- AUTHORS
- CONTRIBUTORS
> A+C: add Mark Canning

- dsp/fourier/internal/fftpack/cfft.go
> dsp/fourier/internal/fftpack: fix typo

- stat/distuv/gamma.go
The paper cited in the comment for the `a > 1` (now `a >= smallAlphaThresh`) case mentions this approach as a small note on the final page, so there is no need to update the comments.
I also looked into [numpy's](https://github.com/numpy/numpy/blob/9ee262b5bf89e8c866a507e4d62b78532361adc2/numpy/random/src/legacy/legacy-distributions.c#L47) logic for this case, but a) couldn't determine a source for it, except for what appears to be [a more complex variant](https://link.springer.com/article/10.1007/BF02293108) (Algorithm GS), and b) it's *slightly* slower than this method, at least for `a >= 0.2`.
benchstat:
```
name              old time/op  new time/op  delta
GammaRand/case_0  89.4ns ± 5%  90.2ns ± 3%     ~     (p=0.084 n=20+20)
GammaRand/case_1   212ns ± 3%   101ns ± …
```
> stat/distuv: improve Gamma.Rand performances for 0.2 <= alpha < 1

- dsp/fourier/fourier.go
> dsp/fourier: fix typo

- mat/cholesky.go
- mat/doc.go
> mat: fix up docs

- lapack/gonum/dlacpy.go
- lapack/lapack64/lapack64.go
- mat/cdense.go
- mat/cholesky.go
- mat/cholesky_test.go
- mat/dense.go
- mat/errors.go
- mat/symmetric.go
- mat/triangular.go
- mat/triband.go
This is an initial draft for a BandCholesky type. At the moment I've added only the minimal functionality to solve banded systems and to satisfy the Matrix interface. I don't plan to support updates to the matrix as `Cholesky` does. WIP, so there are no tests and no documentation comments.
> mat: add BandCholesky type

- lapack/gonum/lapack_test.go
- lapack/testlapack/dtrtrs.go
- lapack/testlapack/general.go
> testlapack: add test for Dtrtrs

- lapack/gonum/dtbtrs.go
- lapack/gonum/lapack_test.go
- lapack/lapack.go
- lapack/lapack64/lapack64.go
- lapack/testlapack/dtbtrs.go
- lapack/testlapack/general.go
> lapack/gonum: add Dtbtrs

- lapack/gonum/dlanv2.go
- lapack/testlapack/dlanv2.go
See https://github.com/Reference-LAPACK/lapack/pull/445
> lapack/gonum: fix underflow in Dlanv2

- lapack/gonum/dlanv2.go
> lapack/gonum: don't loop unnecessarily in Dlanv2

- CONTRIBUTING.md
- mathext/betainc.go
- stat/distuv/binomial.go
This is a small set of innocuous changes that probably don't warrant a PR each.
For the CONTRIBUTING.md change see #1479.
> all: clean up some small things

- graph/flow/control_flow_bench_test.go
> graph/flow: skip rather than erroring when there is no benchmark data

- mat/matrix_test.go
> mat: avoid linting complaint about non-simplified composite element

- lapack/gonum/dtbtrs.go
Same change as requested in https://github.com/gonum/netlib/pull/77
> lapack/gonum: update docs for Dtbtrs

- AUTHORS
- CONTRIBUTORS
> A+C: add Tamir Hyman

- README.md
> README: specify which compiler we test on and support

- mat/cholesky.go
> mat: document that Condition errors are returned by Cholesky methods

- mat/dense_arithmetic.go
- mat/dense_example_test.go
- mat/dense_test.go
Fixes #1499 .
I also cleaned up the example a bit to use non-diagonal matrices.
> mat: fix Dense.Inverse

- graph/path/bellman_ford_moore.go
- graph/path/shortest.go
> graph/path: fix build for 386

- graph/path/dijkstra.go
> graph/path: fix empty iterator comparison

- graph/nodes_edges.go
> graph: make state of empty less contradictory and provide debugging strings

- .travis.yml
> travis: remove unnecessary graphviz install

- spatial/r2/vector.go
- spatial/r2/vector_test.go
> spatial/r2: implement Rotate

- graph/encoding/dot/decode_test.go
- graph/encoding/dot/encode.go
> graph/encoding/dot: fix line visit marking

- graph/path/disjoint.go
- graph/path/disjoint_test.go
- graph/path/spanning_tree.go
> graph/path: simplify and clean up union-find code and Kruskal

- .github/workflows/ci.yml
- .github/workflows/test-coverage.sh
- .travis/script.d/check-generate.sh
- README.md
> github: add CI action

- AUTHORS
- CONTRIBUTORS
> A+C: add Christopher Waldon

- CONTRIBUTORS
Ref https://github.com/gonum/plot/pull/654
> A+C: add Dan Lorenc

- AUTHORS
- CONTRIBUTORS
> A+C: fix name ordering

- unit/unit_test.go
- unit/unittype.go
> unit: add Copy method and documentation to avoid unexpected sharing

- mat/cdense.go
- mat/cdense_test.go
- mat/cmatrix.go
- mat/pool.go
- mat/shadow_complex.go
> mat: add non-conjugate transpose for complex matrices

- AUTHORS
- CONTRIBUTORS
As requested by @sbinet in https://github.com/gonum/plot/pull/415#issuecomment-747400180.
> A+C: Add Fabian Wickborn

- graph/topo/2sat_example_test.go
> graph/topo: conform example function syntax to pkg.go.dev behaviour

- AUTHORS
- CONTRIBUTORS
> A+C: update email Lyron Winderbaum

- .github/workflows/codecov.yml
This fixes the build; I thought I had got all of the references to moved scripts. I had not.
> ci: fix codecov workflow for changes to script locations

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .travis.yml
- appveyor.yml
> ci: update for go1.16

- stat/roc.go
> stat: bring ROC doc comment into line with logic inversion

- AUTHORS
- CONTRIBUTORS
> Adding myself as contributor - https://github.com/gonum/plot/pull/675

- AUTHORS
- CONTRIBUTORS
Added myself, Rondall Jones, as author of proposed package, ARLS
> Add name to AUTHORS and CONTRIBUTORS

- graph/layout/eades_example_test.go
This example will render a complete graph using the EadesR2 layout.
The intent is to give the programmer an idea of how to approach creating and rendering graphs with Gonum in so many steps.
> graph/layout: Add example for rendering with EadesR2 layout

- AUTHORS
- CONTRIBUTORS
Added myself to CONTRIBUTORS and AUTHORS.
> A+C: add Matthew Connelly

- dsp/fourier/fourier_example_test.go
> dsp/fourier: improve simple examples

- stat/mds/mds.go
> stat/mds: add warning about ED numerical stability

- graph/encoding/dot/encode_test.go
> graph/encoding/dot: add tests for empty graphs

- AUTHORS
- CONTRIBUTORS
> Add myself to A+C

- AUTHORS
- CONTRIBUTORS
> A+C: Update JvA email 

- graph/flow/control_flow_test.go
The background to this is that we regularly see graph/flow/control_flow\*.go files, and occasionally optimize/listsearch.go, in the codecov reports as having changed. This is due to algorithmic randomness that shows up in those files. In the case of graph/flow it is due to map iteration order. So the approach is just to increase the number of times the tests are run to decrease the probability of having a test ensemble that does not hit possible lines at least once.
This PR does not address the effect that we see in optimize/listsearch.go, but I'm unable to see how that comes in. I suspect it's from concurrency racing in the algorithm, but it's low enough frequency that I don't see it when I repeatedly run coverage tests. I'll look again if it continues to be a …
> graph/flow: improve consistency of coverage reports

- graph/graphs/gen/gen.go
- graph/graphs/gen/gen_example_test.go
- graph/graphs/gen/gen_test.go
~~WIP(notests)~~
Updates #1582.
/cc @mattConn
> graph/graphs/gen: add simple graph construction functions

- AUTHORS
- CONTRIBUTORS
- floats/floats.go
- floats/floats_test.go
Please take a look, fixes #1598
> floats: add ArgsortStable function

- mat/band.go
- mat/symband.go
See https://github.com/gonum/gonum/pull/1541#discussion_r610072803.
> mat: don't prevent reuse of allocated backing data

- dsp/window/window.go
- dsp/window/window_complex.go
- dsp/window/window_parametric.go
Trimming to right rule and adding punctuation.
> dsp/window: clean up doc formatting

- stat/roc.go
- stat/roc_example_test.go
- stat/roc_test.go
Tests are light because there is little to test.
/cc @Armadilloa16
> stat: add TOC function

- .github/workflows/codecov.yml
This applies the equivalent changes in #1607 but for codecov.
> codecov: make sure build sees env vars

- AUTHORS
- CONTRIBUTORS
- README.md
> README: fix broken link to most recent Go releases

- mat/list_test.go
- mat/matrix_test.go
- mat/tridiag.go
- mat/tridiag_test.go
One of the tests fails due to floating point noise, so setting a draft status while we check how to best modify the test suite.
> mat: add Tridiag to list_test

- internal/testrand/extreme.go
> internal/extreme: fix random method calls

- mat/band.go
- mat/dense.go
- mat/matrix.go
- mat/matrix_test.go
- mat/symband.go
- mat/symmetric.go
- mat/triangular.go
- mat/triband.go
- mat/tridiag.go
- mat/tridiag_test.go
- mat/vector.go
> mat: add Normer interface and use it in Norm

- mat/diagonal.go
- mat/matrix.go
> mat: add DiagDense.Norm

- mat/matrix.go
> mat: remove unused BandWidther interface

- cmplxs/cmplxs.go
- cmplxs/cmplxs_test.go
> cmplxs: add conjugate multiplies and real scales

- mat/band.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/diagonal.go
- mat/gsvd.go
- mat/hogsvd.go
- mat/io.go
- mat/matrix.go
- mat/symband.go
- mat/symmetric.go
- mat/triangular.go
- mat/triband.go
- mat/tridiag.go
- mat/vector.go
> mat: return ErrZeroLength when size is zero and document it

- lapack/gonum/dlassq.go
- lapack/gonum/lapack.go
- lapack/testlapack/dlassq.go
Updates #1623 
I'm submitting as draft while I clarify the correct values of `dssml` and `dsbig` with the Reference Lapack.
> lapack/gonum: rewrite Dlassq and its test

- .github/workflows/codecov.yml
> codecov: revert experiments

- stat/stat.go
- stat/stat_test.go
> stat: panic when calling CDF or Quantile with empty x

- graph/encoding/dot/encode.go
- graph/encoding/dot/encode_test.go
> graph/encoding/dot: don't panic when an Attributers returns a nil

- mat/band.go
- mat/cdense.go
- mat/cholesky.go
- mat/dense.go
- mat/dense_arithmetic.go
- mat/eigen.go
- mat/hogsvd.go
- mat/lq.go
- mat/lu.go
- mat/pool.go
- mat/pool_test.go
- mat/product.go
- mat/qr.go
- mat/solve.go
- mat/svd.go
- mat/symband.go
- mat/symmetric.go
- mat/triangular.go
- mat/triband.go
- mat/tridiag.go
- mat/vector.go
The pool system grew organically leading to naming that while reasonably obvious, was not the best. This fixes that.
> mat: clean up pool code and helper naming

- graph/formats/rdf/urna.go
> graph/formats/rdf: fail early for dst mismatch

- AUTHORS
- CONTRIBUTORS
Per https://github.com/gonum/plot/pull/685#issuecomment-854440159
> A+C: add Valentin Deleplace

- lapack/gonum/dlaswp.go
See https://github.com/gonum/gonum/pull/1652/files#r646111624
> lapack/gonum: avoid no-op row swap in Dlaswp

- stat/distuv/distribution_test.go
> stat/disuv: make helpers and disambiguate case indexes

- stat/distuv/chi.go
- stat/distuv/chi_test.go
> stat/distuv: add chi distribution

- AUTHORS
- CONTRIBUTORS
Contributors + authors addition of `Patricio Whittingslow <graded.sp@gmail.com>`
> A+C: add Patricio Whittingslow

- graph/formats/rdf/iso_canonical.go
- graph/formats/rdf/iso_canonical_test.go
- graph/formats/rdf/rdf.go
- graph/formats/rdf/urna.go
> graph/formats/rdf: use isBlank and isIRI helpers

- lapack/testlapack/dlasy2.go
> lapack/testlapack: extend test for Dlasy2 to cover rescaling

- lapack/gonum/dgesc2.go
- lapack/gonum/dgetc2.go
- lapack/testlapack/dgesc2.go
- lapack/testlapack/dgetc2.go
- lapack/testlapack/general.go
> lapack/{gonum,testlapack}: clean up Dgetc2 and Dgesc2 and rework their tests

- spatial/vptree/vptree.go
- spatial/vptree/vptree_test.go
> spatial/vptree: fix vantage point selection

- spatial/r2/vector.go
- spatial/r3/vector.go
> spatial/{r2,r3}: fix/clarify doc comments

- stat/stat_example_test.go
> stat: correct slope/offset in ExampleLinearRegression

- AUTHORS
- CONTRIBUTORS
> A+C: add Will Tekulve

- AUTHORS
- CONTRIBUTORS
> A+C: add Yasuhiro Matsumoto

- mat/cholesky.go
> mat: Fix typo

- mat/qr.go
> mat: remove blank line

- graph/formats/rdf/iso_canonical.go
- graph/topo/topo.go
- lapack/gonum/dlasq2.go
- mat/diagonal.go
- mat/symmetric.go
- stat/combin/combin.go
> all: remove or clarify repeated words in comments

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .travis.yml
- appveyor.yml
> ci: update for go1.17

- diff/fd/hessian.go
- diff/fd/watson_test.go
- graph/simple/dense_undirected_matrix.go
- mat/basictypes_test.go
- mat/cholesky.go
- mat/cholesky_test.go
- mat/diagonal.go
- mat/eigen.go
- mat/list_test.go
- mat/symband.go
- mat/symmetric.go
- mat/symmetric_test.go
- mat/triangular.go
- optimize/cmaes.go
- optimize/functions/functions.go
- optimize/minimize.go
- stat/distmat/wishart.go
- stat/distmat/wishart_test.go
- stat/distmv/dirichlet.go
- stat/distmv/general_test.go
- stat/distmv/normal.go
- stat/distmv/normal_test.go
- stat/distmv/studentst.go
- stat/mds/mds.go
- stat/samplemv/metropolishastings.go
- stat/statmat.go
- stat/statmat_test.go
> mat: rename Symmetric method to SymmetricDim

- mat/basictypes_test.go
> mat: simplify redundant selector expression

- mat/diagonal.go
> mat: simplify Diagonal interface expression

- lapack/gonum/dorgr2.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dorgr2.go
Please take a look. 
Functionality needed to solve https://github.com/gonum/gonum/issues/1651
> lapack/gonum: add Dorgr2

- .github/FUNDING.yml
> github: remove kortschak from FUNDING.yml

- mat/cholesky.go
- stat/distmv/normal.go
- stat/distmv/studentst.go
> mat,stat: refer to SymmetricDim in docs

- dsp/window/cmd/leakage/leakage.go
> dsp/window/cmd/leakage: add utility command for parameter estimation

- AUTHORS
- CONTRIBUTORS
> A+C: add Jinesi Yelizati

- lapack/gonum/dorgr2.go
- lapack/testlapack/dorgr2.go
> lapack/{gonum,testlapack}: clean up Dorgr2 and its test

- README.md
> README: fix line link syntax

- lapack/gonum/dpstf2.go
- lapack/gonum/errors.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dpstf2.go
> lapack/gonum: add Dpstf2 and its test

- graph/iterator/lines_map.go
- graph/iterator/map.go
- graph/iterator/nodes_map.go
- graph/iterator/nodes_map_safe.go
https://go-review.googlesource.com/c/go/+/321889
Fixes #1728
> graph/iterator: update map iteration to tolerate changes in reflect

- blas/README.md
> blas: update README

- lapack/gonum/dpstrf.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dpstf2.go
- lapack/testlapack/dpstrf.go
> lapack/gonum: add Dpstrf and its test

- graph/iterator/map.go
See https://go-review.googlesource.com/c/go/+/360254
> graph/iterator: avoid stack copies of hiter

- graph/formats/rdf/iso_canonical.go
> graph/formats/rdf: fix typo

- AUTHORS
- CONTRIBUTORS
https://github.com/gonum/gonum/pull/1745#issuecomment-955632472
Adding myself to contributors list
> A+C: add Maxim S

- AUTHORS
- CONTRIBUTORS
Adding myself to contributors list after [comment](https://github.com/gonum/gonum/pull/1752#pullrequestreview-811860127)
> A+C: add Evgeny Savinov

- mat/qr_example_test.go
Fixes #1759.
Signed-off-by: Sebastien Binet <binet@cern.ch>
> mat: add example for polynomial regression with QR factorization

- go.mod
- go.sum
- graph/formats/rdf/graph.go
- graph/formats/rdf/graph_example_test.go
- graph/formats/rdf/graph_export_test.go
- graph/formats/rdf/graph_test.go
- graph/formats/rdf/query.go
- graph/formats/rdf/query_test.go
- graph/formats/rdf/rdf.go
> graph/formats/rdf: add a query language

- lapack/gonum/dpstf2.go
- lapack/gonum/dpstrf.go
- lapack/lapack.go
- lapack/lapack64/lapack64.go
- lapack/gonum: extend docs for Dpstrf and Dpstf2
- lapack/lapack64: add Pstrf
> lapack/lapack64: add Pstrf

- lapack/gonum/dpstf2.go
- lapack/gonum/dpstrf.go
- lapack/lapack64/lapack64.go
> lapack/gonum: clarify ok return from Dpstrf and Dpstf2

- graph/formats/rdf/urna.go
- graph/formats/rdf/urna_test.go
> graph/formats/rdf: add deduplication function

- spatial/r3/mat.go
- spatial/r3/mat_test.go
Please take a look. Resolves #1757
Work on Inverse (could not get it to pass tests):
<details>
```go
func (m *Mat) Inverse(a mat.Matrix) error {
if r, c := a.Dims(); r != 3 || c != 3 {
panic("Mat.Inverse needs 3x3 matrix")
}
const small = 1e-12
D := mat.Det(a)
if math.Abs(D) < small {
return mat.ErrSingular
}
// https://www.wikihow.com/Find-the-Inverse-of-a-3x3-Matrix
for i := 0; i < 3; i++ {
i1, i2 := (i+1)%3, (i+2)%3
for j := 0; j < 3; j++ {
j1, j2 := (j+1)%3, (j+2)%3
det := a.At(i1, j1)*a.At(i2, j2) - a.At(i1, j2)*a.At(i2, j1)
m.Set(j, i, det)
}
}
m.Scale(1/D, m)
return nil
}
func TestInverse(t *testing.T) {
const tol = 1e-11
rnd := rand.New(rand.NewSource(1))
for tc := 0; tc < 20; tc++ {
m := randomMat(rnd)
M := mat.DenseCopyOf(m)
err := M.Inverse(M)
if err != nil {
t.Fatal(err)
}
err …
```
> spatial/r3: add Mat Outer,Det,RotateQuat methods

- go.mod
- go.sum
- spatial/r3/mat.go
- spatial/r3: remove netlib from dependency requirements
- spatial/r3: fix doc comments to start with function name
> spatial/r3: small cleanup

- spatial/r3/mat_test.go
> spatial/r3: rework test for RotationFromQuat

- go.mod
> mod: run go.mod tidy

- lapack/gonum/dlapmr.go
- lapack/gonum/lapack_test.go
- lapack/lapack.go
- lapack/lapack64/lapack64.go
- lapack/testlapack/dlapmr.go
> lapack/gonum: add Dlapmr

- .github/workflows/ci.yml
> ci: install ragel to check rdf codegen

- spatial/r2/box.go
- spatial/r2/box_test.go
- spatial/r2/vector.go
- spatial/r2/vector_test.go
Resolves part of https://github.com/gonum/gonum/issues/1791
> spatial/r2: add Box methods

- spatial/r3/box.go
- spatial/r3/box_test.go
- spatial/r3/vector.go
Resolves part of https://github.com/gonum/gonum/issues/1791
> spatial/r3: add Box methods

- spatial/r2/triangle.go
- spatial/r2/triangle_test.go
Resolves part of https://github.com/gonum/gonum/issues/1791
> spatial/r2: add Triangle

- spatial/r3/icosahedron_example_test.go
- spatial/r3/triangle.go
- spatial/r3/triangle_test.go
> spatial/r3: add Triangle

- AUTHORS
- CONTRIBUTORS
> A+C: add Scott Kiesel

- spatial/r3/vector.go
- spatial/r3/vector_test.go
Resolves part of https://github.com/gonum/gonum/issues/1809#issuecomment-1140334118
> spatial/r3: add Divergence

- spatial/r3/mat.go
- spatial/r3/mat_test.go
Resolves part of https://github.com/gonum/gonum/issues/1809#issuecomment-1140334118
> r3.Mat: add Hessian

- lapack/testlapack/dsterf.go
> lapack/testlapack: allow test loop to continue on failure

- spatial/r3/mat_test.go
- spatial/r3/vector.go
- spatial/r3/vector_test.go
Resolves part of https://github.com/gonum/gonum/issues/1809#issuecomment-1140334118
> spatial/r3: add Gradient

- spatial/r3/mat.go
- spatial/r3/mat_test.go
- spatial/r3/vector_test.go
Resolves part of https://github.com/gonum/gonum/issues/1809#issuecomment-1140334118
> spatial/r3: add Jacobian

- spatial/r3/mat.go
> spatial/r3: add Jacobian layout description to doc comment

- .github/workflows/codecov.yml
> ci: bump codecov go version to go1.19

- AUTHORS
- CONTRIBUTORS
> A+C: add Yunomi

- AUTHORS
- CONTRIBUTORS
> A+C: add Chan Kwan Yin

- AUTHORS
- CONTRIBUTORS
> A+C: add Chong Yeol Nah

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
> ci: update for go1.20

- AUTHORS
- CONTRIBUTORS
> A+C: add Bulat Khasanov

- lapack/gonum/dbdsqr.go
Replays changes done in the Reference in https://github.com/Reference-LAPACK/lapack/pull/832
> lapack/gonum: remove unused variable in Dbdsqr

- lapack/gonum/dlatbs.go
- lapack/gonum/dlatrs.go
- lapack/testlapack/dlatrs.go
Replays changes done in the Reference in https://github.com/Reference-LAPACK/lapack/pull/712
> lapack/gonum: avoid NaN generation in Dlatrs

- lapack/gonum/dlahqr.go
Replays changes done in the Reference in https://github.com/Reference-LAPACK/lapack/pull/478 and https://github.com/Reference-LAPACK/lapack/pull/487
> lapack/gonum: improve exceptional shift in Dlahqr

- AUTHORS
- CONTRIBUTORS
> A+C: add Jes Cok

- graph/formats/gexf12/gexf.go
- graph/formats/rdf/equi_canonical_test.go
- graph/formats/rdf/nquads.rl
- graph/path/dynamic/dumper_test.go
- graph/path/spanning_tree_test.go
- graph/topo/paton_cycles_test.go
- graph/topo/topo_test.go
- lapack/lapack64/lapack64.go
- lapack/testlapack/drscl.go
- lapack/testlapack/dsytrd.go
- mat/dense_test.go
- optimize/convex/lp/simplex.go
- stat/distuv/binomial.go
- stat/distuv/norm.go
- stat/spatial/spatial_areal_example_test.go
- stat/stat_test.go
> all: fix typos

- blas/blas64/blas64_test.go
- blas/gonum/level1float64_test.go
- blas/testblas/level1double.go
This is done for https://github.com/gonum/netlib/pull/92
> blas/testblas: add flag to DrotgTest to skip extreme values

- blas/testblas/level1double.go
For https://github.com/gonum/netlib/pull/92
> blas/testblas: clean up Drotmg test and relax tolerance

- lapack/gonum/dgecon.go
Applying similar changes as the reference in https://github.com/Reference-LAPACK/lapack/pull/765
> lapack/gonum: propagate NaN from Dgecon

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- go.mod
> ci: update for go1.21

- mat/cholesky.go
- mat/cholesky_test.go
This is just a draft for now to discuss and collect feedback.
My doubts are:
1. Should `Factorize` return a bool? And the closely related question, should `PivotedCholesky.SolveTo/SolveVecTo` exist? If the solve routines don't exist, then Factorize doesn't need to return ok. If they exist, then they must panic if ok is false. This gives the ok return a different meaning from the other factorization types: it's not a failure of the factorization, it's just an indicator that the matrix has full rank (that is, positive definite) and can be used for linear solve. However, if one expects that the matrix is only semi-definite, then one should not expect to be able to solve linear systems with it.
2. Should `Factorize` take a tolerance parameter for `Dpstrf` with the same semantics (default …
> mat: add PivotedCholesky

- lapack/gonum/dlanhs.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dlanhs.go
Part of #1651.
Used dlange to validate.
> lapack: add Dlanhs and its test

- AUTHORS
- CONTRIBUTORS
As requested in https://github.com/gonum/gonum/pull/1892
> A+C: add Jordan Stoker

- lapack/gonum/dlanhs.go
- lapack/testlapack/dlanhs.go
> lapack/gonum: clean up Dlanhs and its test

- lapack/gonum/dgghrd.go
- lapack/lapack.go
- lapack/testlapack/dgghrd.go
- lapack/testlapack/general.go
> lapack/gonum: clean up Dgghrd and its test

- lapack/gonum/dgeqp3.go
- lapack/lapack.go
- lapack/lapack64/lapack64.go
> lapack/lapack64: add Geqp3 and clean up docs

- lapack/gonum/dgetf2.go
- lapack/gonum/dgetrf.go
- lapack/lapack64/lapack64.go
- mat/cholesky.go
- mat/cholesky_test.go
- mat/dense.go
- mat/dense_test.go
- mat/lu.go
- mat/lu_test.go
One thing led to another and I ended up touching more code that I expected.
Please take a look, the commits are useful.
Closes #1900
> mat: return U and Pivots from PivotedCholesky

- lapack/gonum/dgetf2.go
- lapack/gonum/dgetrf.go
- lapack/lapack64/lapack64.go
- mat/lu.go
- mat/lu_test.go
> mat: make LU satisfy Matrix

- lapack/gonum/dgels.go
- lapack/gonum/dgeqp3.go
- lapack/gonum/dgeqr2.go
- lapack/gonum/dgeqrf.go
- lapack/gonum/dgesvd.go
- lapack/gonum/dggsvp3.go
- lapack/gonum/dorg2r.go
- lapack/gonum/dorgbr.go
- lapack/gonum/dorgqr.go
- lapack/gonum/dorgtr.go
- lapack/gonum/dorm2r.go
- lapack/lapack64/lapack64.go
- lapack/testlapack/dgeqrf.go
- lapack/testlapack/dlarfb.go
- lapack/testlapack/dlarft.go
- lapack/testlapack/dorg2r.go
- lapack/testlapack/dorgqr.go
> lapack/gonum: require exact length of tau in QR routines

- lapack/gonum/dorgl2.go
- lapack/gonum/dorglq.go
- lapack/lapack.go
- lapack/lapack64/lapack64.go
- mat/lq.go
- mat/lq_test.go
> mat: make LQ satisfy Matrix

- stat/distmv/dirichlet.go
- stat/distmv/distmv.go
- stat/distmv/general.go
- stat/distmv/normal.go
- stat/distmv/normal_test.go
- stat/distmv/studentst.go
- stat/distmv/uniform.go
> stat/distmv: add NormalRandCov

- mat/matrix.go
- mat/solve.go
- mat/triangular.go
- mat/triband.go
- mat/tridiag.go
> mat: delegate to SolveTo method in *Dense.Solve

- mat/eigen.go
- mat/eigen_test.go
> mat: make EigenSym satisfy Matrix

- lapack/gonum/dgecon.go
- lapack/testlapack/dgecon.go
See https://github.com/Reference-LAPACK/lapack/pull/926
> lapack/gonum: handle NaN and Inf input to Dgecon

- lapack/gonum/dptsv.go
- lapack/gonum/dpttrf.go
- lapack/gonum/dpttrs.go
- lapack/gonum/dptts2.go
- lapack/gonum/ilaenv.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dptsv.go
- lapack/testlapack/dpttrf.go
- lapack/testlapack/dpttrs.go
> lapack/gonum: add Dpttrf, Dpttrs and Dptsv

- lapack/gonum/dptcon.go
- lapack/gonum/lapack_test.go
- lapack/testlapack/dptcon.go
- lapack/testlapack/dpttrf.go
- lapack/testlapack/locallapack.go
> lapack/gonum: add Dptcon

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/staticcheck.yml
> ci: update for go1.22

- AUTHORS
- CONTRIBUTORS
Adding myself as an author and contributor as requested in https://github.com/gonum/gonum/pull/1940#pullrequestreview-1926082282.
> A+C: add Jonathan Bluett-Duncan

- floats/floats.go
- floats/floats_test.go
> floats: replace custom reverse logic with slices.Reverse

- spatial/r3/triangle.go
- stat/roc_example_test.go
> chore: remove repetitive words

- AUTHORS
- CONTRIBUTORS
> A+C: add Huang Peng Fei

- dsp/fourier/radix24_test.go
> dsp: replace custom reverse logic with slices.Reverse 

- graph/implicit_example_test.go
The From method incorrectly returned nil for the empty case and node neighbour expansion did not mark visited nodes. Fix these and exercise the corrected path in the test. Also clean up the code structure.
This is a counter proposal to #1967 which does not completely fix the example.
Closes #1967
> graph: clean up and fix implicit graph example

- integrate/quad/hermite.go
- internal/testrand/extreme.go
> all: fix doc comments

- AUTHORS
- CONTRIBUTORS
> A+C: add Kendall Marcus

- AUTHORS
- CONTRIBUTORS
Assuming #1981 is accepted, this PR adds me to AUTHORS and CONTRIBUTORS.
> A+C: add Tom Payne

- AUTHORS
- CONTRIBUTORS
Requested as part of https://github.com/gonum/plot/pull/781
> A+C add Dirk Müller

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- .github/workflows/staticcheck.yml
- go.mod
> ci,mod: update to go1.23

- graph/flow/interval.go
- graph/flow/interval_test.go
Hi,
This is the code for issue #796 allowing finding intervals in flow graphs. I've added some basic testing using an example graph given in C. Cifuentes, "Reverse Compilation Techniques", 1994. This is my first time contributing to an open source project and I look forward to your feedback!
Thanks,
Jack
> graph: add algorithm for finding intervals in flow graphs

- AUTHORS
- CONTRIBUTORS
Contributor update related to #2002
> A+C: add Robert Kleffner

- AUTHORS
- CONTRIBUTORS
Needed by https://github.com/gonum/gonum/pull/2032
> A+C: add Zhan Shan Mao

- .github/PULL_REQUEST_TEMPLATE
> github: add reading check instruction to pr template

- graph/network/distance.go
- graph/network/distance_test.go
> graph/network: add eccentricity measurement

- AUTHORS
- CONTRIBUTORS
> A+C: add Nicolas Peugnet

- graph/network/distance_test.go
This is a follow-up of https://github.com/gonum/gonum/pull/2038
> graph/network: add test for eccentricity with digraphs

- AUTHORS
- CONTRIBUTORS
> A+C: add Andreas Scharf

- .github/workflows/ci.yml
- cmplxs/cmplxs_test.go
- floats/floats_test.go
- go.mod
> all: bump Go-1.25, drop Go-1.23
