gonum/gonum

.travis.yml
gonum.txt
hello.go
hello_test.go

Partial fix for travis failures. The next step is to move cgo-dependent code out into netlib.

gonum: clean away old files and fix-up travis

---

graph/simple/directed.go
graph/simple/simple.go
graph/simple/undirected.go

This is preparation for adding `ID() int` to the `graph.Edge` interface.
@vladimir-ch Please take a look.

graph/simple: factor ID handling out of graph types

---

matrix/mat64/gsvd.go
matrix/mat64/gsvd_example_test.go
matrix/mat64/gsvd_test.go
matrix/mat64/hogsvd.go
matrix/mat64/hogsvd_example_test.go
matrix/mat64/hogsvd_test.go
matrix/mat64/lq.go
matrix/mat64/lq_test.go
matrix/mat64/lu.go
matrix/mat64/lu_test.go
matrix/mat64/qr.go
matrix/mat64/qr_test.go
matrix/mat64/svd.go
matrix/mat64/svd_test.go
stat/pca_cca.go

matrix/mat64,stat: reverse matrix extraction

---

graph/simple/directed.go
graph/simple/simple.go
graph/simple/undirected.go

This does not go the complete way to the kind of implementation referred to in the gonum-dev [thread](https://groups.google.com/d/topic/gonum-dev/twUcG1rEMIU/discussion), but covers a reasonable set of use cases. If we make an `IDSource` interface to use, this would be a good default.
@leoneu Would you please try this in your problematic code and see if it is satisfactory.
@leoneu @vladimir-ch Please take a look.
Updates #32.

graph/simple: do not use intsets.Sparse for ID sets

---

graph/community/louvain_common.go
graph/community/louvain_directed.go
graph/community/louvain_directed_multiplex.go
graph/community/louvain_directed_multiplex_test.go
graph/community/louvain_directed_test.go
graph/community/louvain_test.go
graph/community/louvain_undirected.go
graph/community/louvain_undirected_multiplex.go
graph/community/louvain_undirected_multiplex_test.go
graph/community/louvain_undirected_test.go
graph/encoding/dot/decode.go
graph/encoding/dot/dot_test.go
graph/internal/set/same.go
graph/internal/set/same_appengine.go
graph/internal/set/set.go
graph/topo/tarjan.go
graph/traverse/traverse.go
graph/traverse/traverse_test.go
graph/undirect.go

This is a first step towards allowing `int64` ID values and addresses the simple-to-handle cases.
Another PR for the more hairy community package will follow when I figure out a good approach; the problem is that `intsets.Sparse` iterates via a stateful method, which allows a nice method-based approach to handle subset iteration, versus complete set iteration without filling a complete set for the complete set case. `set.Ints` cannot do this because of limitations with `range`. Suggestions welcomed.
@vladimir-ch @mewmew Please take a look.

graph,graph/{encoding/dot,internal/set,topo,traverse}: remove intsets imports

---

mat/dense.go
mat/matrix.go
mat/symmetric.go
mat/vector.go
optimize/convex/lp/convert.go
optimize/convex/lp/simplex.go
stat/distmv/normal_test.go
stat/samplemv/metropolishastings.go
stat/samplemv/sample_test.go

Fixes #67.
I'm going to come back to `*Vector` when I'm not tired.

mat: remove View* methods and extend semantics of Slice

---

.travis.yml
.travis/check-formatting.sh

The intention of the previous commit touching this was to avoid RED on the log unless there was a problem. That commit did not achieve this goal, so I'm hiding the ANSI codes in a script.

travis: fix formatting again

---

mat/vector.go
mat/vector_test.go

mat: extend Vector slicing sematics to allow slicing up to capacity

---

stat/spatial/spatial.go
stat/spatial/spatial_areal_example_test.go
stat/spatial/spatial_example_test.go
stat/spatial/spatial_test.go

@btracey @vladimir-ch @Armadilloa16 @ReubenBuck Please take a look.
This is commit one of ~~two~~ three. The ~~second~~ final commit will add element-wise weights, after the API is otherwise settled.
Possible considerations are adding a reset method to allow data/locality reuse.

stat/spatial: new package for spatial statistic measures

---

mat/cholesky.go
mat/cholesky_example_test.go
mat/cholesky_test.go
mat/lq.go
mat/lq_test.go
mat/lu.go
mat/lu_test.go
mat/qr.go
mat/qr_test.go
mat/solve.go
optimize/newton.go
stat/distmat/wishart.go
stat/distmv/normal.go
stat/distmv/normal_test.go
stat/distmv/statdist.go
stat/distmv/studentst.go
stat/statmat.go

mat: rewrite extractions and solves as methods on factorising types

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go
graph/graph.go
graph/graphs/gen/duplication.go
graph/simple/directed.go
graph/simple/directed_test.go
graph/simple/undirected.go
graph/simple/undirected_test.go

@mewmew @vladimir-ch @btracey Please take a look.
This is a minimal change. The rationale is explained in the issue, but briefly, by returning a `graph.Node` rather than an `int64`, the destination graph can decide what type of node is added, where previously this was hard coded into the filling function. A good example is in the duplication.go file which generates random duplication graphs.
Fixes #59.

graph: revert NewNodeID -> NewNode

---

graph/graph.go

No behaviour change; package simple graphs still panic for addition of self
edges, as noted in their existing documentation.

graph: change documentation to allow self edges

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go

graph/encoding/dot: fix NewNode use in tests and decoding

---

mathext/ell_carlson.go
mathext/ell_carlson_test.go

Added Carlson's symmetric elliptic integrals RF and RD. Added Legendre's elliptic integrals of the 1st and 2nd kinds.

mathext: add elliptic integrals (Carlson and Legendre).

---

AUTHORS
CONTRIBUTORS
README.md

I've added a badge for [Go Report Card](https://goreportcard.com/) which reports the quality of an open source go project using `gofmt`, `go vet` and so on. 
This allows users to see at a glance how well the source code is formatted.

Add a badge for Go Report Card

---

mat/band.go
mat/matrix.go
mat/matrix_test.go
mat/symband.go
mat/symmetric.go
mat/triangular.go

This is a proposal for an approach to optimising sparse or sparsish matrix accesses raised in https://github.com/gonum/gonum/pull/124#discussion_r126201816
~~Only https://github.com/gonum/gonum/commit/2eb65a280581fdb47fa2714f84b793f652ccbb58 is relevant to this PR and I'll revise the history of the PR when #95 is merged.~~
Depends #95.

mat: add Doer interface and implementations

---

stat/spatial/spatial.go
stat/spatial/spatial_example_test.go
stat/spatial/spatial_test.go

~~Depends #126 if using second approach.~~

stat/spatial: use mat.RowNonZeroDoer

---

blas/blas64/conv.go
blas/blas64/conv_test.go

Reference #138.
This covers the types that are supported in mat and makes no change to the API other than adding the conversion tools. My sense of symmetry says that the row major types should be labelled as such, but I could get over on the basis that we are natively row major and the column major types are for external use.
asm-dependent code can come later as can generation of `float32` and complex equivalents.

blas64: add row/col major conversion methods

---

stat/sampleuv/weighted_test.go

This reduces the test time by about two orders of magnitude, from 20+ secounds to 0.7s

stat/sampleuv: reduce weighted test size.

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go
graph/encoding/dot/encode.go
graph/encoding/dot/encode_test.go
graph/encoding/encoding.go

This is the first of two PRs to harmonise the graph encoding API. The next will change the `Unmarshal` methods to be `SetAttribute`. The API is still in flux.
@vladimir-ch @mewmew Please take a look.

graph/encoding: move basic encoding API into new encoding package

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go
graph/encoding/encoding.go

graph/encoding: rename decoding API in encoding package

---

graph/encoding/graphql/decode.go
graph/encoding/graphql/decode_test.go
graph/encoding/graphql/graphql.go
graph/encoding/graphql/graphs_test.go

graph/encoding/graphql: add new package for decoding GraphQL output

---

stat/roc_example_test.go

A hopefully cleaner version of fix for #176 with a single commit. Please, let me know if this is not exactly what you were hoping to see. If not, a tiny bit of guidance will be kindly appreciated.

stat: Correct names of two functions to reflect proper meaning, which is currently reversed

---

.travis.yml

This CL enables the fast-finish mode for travis.
See:
https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

travis: enable fast-finish

---

graph/graphs/gen/duplication.go

The makes use of the new `graph.EdgeAdder` interface (currently the functionality is degraded because we cannot set the weight here - though do we want to?).
In order to make similar changes to the other random graph generation functions, it looks like we need a way to obtain a node with a given ID.
@mewmew Please take a look.
Depends #200.

graph/graphs/gen: use EdgeAdder for duplication graph

---

AUTHORS
CONTRIBUTORS
floats/floats.go

Commit a60bb67 changed Argsort argument name from "s" to "dst" but forgot to update documentation to reflect that.

floats: Fix Argsort documentation

---

.travis/check-generate.sh

Noticed in #225 that check-generate failures in travis don't show the offending lines.

travis: Print git diff when check-generate fails.

---

graph/community/k_communities.go
graph/community/k_communities_test.go
graph/topo/clique_graph.go
graph/topo/clique_graph_test.go

@mewmew @vladimir-ch Please take a look.
There are likely optimisations in `community.KCliqueCommunities` since we are using `topo.CliqueGraph` which does more work than is absolutely required, but at least for the moment the clarity in the code is worth that additional cost, which is probably significantly less than the unavoidable costs of doing the maximal clique finding in the first place. If it becomes an issue for someone, we can re-address it then.

graph/{topo,community}: add clique graph and k-clique community finding

---

graph/internal/ordered/sort.go
graph/path/shortest.go
graph/topo/bron_kerbosch.go
graph/topo/bron_kerbosch_test.go
graph/topo/paton_cycles_test.go
graph/topo/tarjan.go

This could be done using `VertexOrdering`, but this is marginally more efficient, and probably clearer to read given the naming for its use.
@mewmew Please take a look.

graph/topo: add function to find k-core of undirected graph

---

graph/path/bellman_ford_moore.go
graph/path/negative_cycles_example_test.go
graph/path/shortest.go

@mewmew @vladimir-ch @Noki Please take a look.
I have chosen to use NaN as the weight for negative cycle paths since a linear path that has a -Inf weight would also be found to have a -Inf path weight using the approach in the example. Intuitively also, the weight of the path seems like NaN rather than -Inf.
Fixes #217.

graph/path: allow Shortest to traverse negative cycles

---

graph/topo/bron_kerbosch.go
graph/topo/bron_kerbosch_test.go

graph/topo: rename VertexOrdering => DegeneracyOrdering

---

mat/dense_example_test.go

@btracey @jchatkinson Please take a look.
This makes matrix elements appear as they would if written down, removes superfluous verbiage, and breaks lines so godoc.org does not present a need to scroll horizontally to read comments.
As a note, example test output is trimmed of trailing whitespace, so the final newline is not needed.

mat: tidy up example formatting

---

AUTHORS
CONTRIBUTORS
mathext/digamma.go
mathext/digamma_test.go

Before the Digamma function could be quite slow for large negative
arguments because it had to do use the recurrence relation thousands
of times. This avoids that by instead using the reflection formula. It
also adds some explicit checks for special cases (Inf, NaN, poles).
For example, running the following code:
```go
package main
import (
"fmt"
"time"
"gonum.org/v1/gonum/mathext"
)
func main () {
start := time.Now()
for i := 0; i < 10; i++ {
mathext.Digamma(-1.1111111111e9)
}
fmt.Printf("%s elapsed\n", time.Since(start))
}
```
gives me `40.625090145s elapsed` on master and `8.615µs elapsed` on this branch.

mathext: speed up Digamma for large negative arguments

---

blas/gonum/cmplx.go
blas/gonum/level2cmplx128.go
blas/gonum/level2cmplx128_test.go
blas/testblas/common.go
blas/testblas/zcopy.go
blas/testblas/zher.go
blas/testblas/zher2.go
blas/testblas/zswap.go
blas/testblas/ztrsv.go

I had to fix `zsame` which in turn required modifying tests for `Zher` and `Zher2`. This in turn revealed that their behavior is not as documented when `alpha == 0`. I postpone that to another PR. If you wish I can cut out the commits to a prequel PR.

blas/gonum: add Ztrsv

---

lapack/testlapack/dtrtri.go

This also allows us to tighten the test tolerance.

lapack/testlapack: improve conditioning of test matrices for Dtrtri

---

lapack/testlapack/dggsvd3.go

Tested with `CGO_LDFLAGS="-L/usr/local -lopenblas" go test gonum.org/v1/netlib/lapack/netlib -v -run Dggsvd` locally (fails without this change).

lapack/testlapack: relax tolerance for Dggsvd3

---

graph/community/louvain_common.go
graph/encoding/dot/encode_test.go
graph/graph.go
graph/path/a_star_test.go
graph/simple/simple.go
graph/topo/clique_graph.go
graph/undirect.go

This is a major breaking change in the graph packages.
Updates gonum/graph#109.

graph: change Edge interface to include ID method

---

mat/doc.go
mat/shadow.go
mat/shadow_test.go
mat/symmetric.go
mat/triangular.go

This is eases shadow detection between the complete set of BLAS backing matrix types without combinatoric explosion. The second commit changes the `checkOverlap` method signatures to have all take `blas64.General` and then have conversion calls at the method call sites.
Using the changes here allows shadow detection for all BLAS types, including packed matrices.
Updates #310.

mat: use generalised rectangular shadow check

---

graph/community/louvain_common.go
graph/encoding/dot/encode_test.go
graph/graph.go
graph/path/a_star_test.go
graph/simple/simple.go
graph/topo/clique_graph.go
graph/undirect.go

This reverts commit 1a83fdba7a89a738f20ebb74f6ab0efaf2ebc42c.
Further design discussion leads to a better approach with an additional edge-type interface.
Please take a look. (I'll want two approvals this time).
Updates #342.

Revert "graph: change Edge interface to include ID method"

---

graph/multigraph.go

Note that the copyright date reflects that the file is a modification of graph.go.
Another PR will add a package multigraph which will reflect the non-dense simple package types.
Closes gonum/graph#109.

graph: define multigraph API

---

blas/README.md
lapack/README.md

This fixes confusion around whether CGO-based implementations are required for the gonum BLAS and LAPACK implementations.

blas,lapack: remove reference to CGO installation

---

blas/gonum/level2cmplx128.go
blas/gonum/level2double.go
blas/gonum/level2single.go

You were right, in godoc it appeared only in `Ztpmv`.

blas/gonum: use = instead of := in documentation

---

lapack/testlapack/dlarfg.go

Coverage for `Dlarfg` is complete with this.

lapack/testlapack: fix and extend test for Dlarfg

---

optimize/cmaes.go
optimize/cmaes_test.go
optimize/global.go
optimize/guessandcheck.go
optimize/guessandcheck_test.go
optimize/local.go
optimize/minimize.go
optimize/types.go

The previous implementation of Global was a minefield for incorrectly implementing global optimization methods. It was very difficult to correctly implement methods (both of the provided methods were incorrect), and the resulting code is very ugly. This commit switches to use channels to communicate, allowing a more clear ordering of concurrent code. This also enables better shutdown of methods.
In addition to the main fix of Global, this refactors the two Global methods to use the updated interface, and makes some small improvements that were previously not possible. In addition, there are some small cleanups of Local to better match between the two calls.
If anyone has been curious about what is meant by 'Don't communicate by sharing memory, share memory by communicating' this is it, …

optimize: completely overhaul Global

---

floats/floats.go
floats/floats_test.go

I have not really touched the documentation, but I think that will probably need work too. Comments welcome for that.
Fixes #413.
/cc @aleh-null

floats: fix nearest, span and min/max index behaviours

---

lapack/gonum/dbdsqr.go
lapack/testlapack/dbdsqr.go

A small adjustment made in netlib LAPACK in https://github.com/Reference-LAPACK/lapack/pull/234

lapack/gonum: relax requirement on work length in Dbdsqr

---

.travis.yml
.travis/test-coverage.sh

Travis seems to have been throwing weaker hardware at problems recently, so we have seen many test builds timing out.
This change shards the four different tags we use in testing, and additionally also adds tagged builds to the test coverage. This makes it possible for the tests to complete and has the additional advantage that tagged tests status is easier to see, and tagged coverage is now available.

travis: shard tags over separate builds

---

graph/traverse/traverse.go

This is exploratory and related to some work that was done/discussed a long time ago in gonum/graph but essentially dropped. I think this package probably warrants this change given how generally useful graph traversal is.

traverse: relax requirements for traversal types

---

optimize/functionconvergence.go
optimize/global.go
optimize/guessandcheck_test.go
optimize/local.go
optimize/unconstrained_test.go

This PR starts the process described in #482. It removes the existing Local implementation, replacing with a function that wraps Method to act as a GlobalMethod. This PR also adds a hack to fix an inconsistency with FunctionConverge between Global and Local (and a TODO to make it not a hack in the future). Finally it improves the Global documentation to help with shutdown.

optimize: remove Local implementation and replace with a call to Global

---

lapack/gonum/dgeqrf.go
mat/qr_test.go

lapack/gonum: fix opt work in Dgeqrf for zero-sized matrix

---

mat/dense.go
mat/errors.go
mat/io.go
mat/io_test.go
mat/qr_test.go
mat/symmetric.go
mat/triangular.go
mat/vector.go

I would have liked to add a zero-size check in the construction functions for each of these types. But there are a number of places (particularly in list_test.go) that use calls to `New*(0,...` (list_test can special-case 0 and just return the type, which would be better anyway since we say the zero value is usable). The approach here covers the majority of cases though (note that it does not catch stack and augment with one zero and one non-zero dimensioned input - this is arguably OK).
The io routines do not panic, since the user cannot know prior to reading whether the data are zero.
I'd like to be able to differentiate zero values that the user has made from zero values that we've incorrectly passed into a routine and panic harder in the latter case, but this …

mat: disallow zero dimension results

---

graph/path/a_star.go
graph/path/bellman_ford_moore.go
graph/path/dijkstra.go
graph/path/dijkstra_test.go
graph/path/floydwarshall.go
graph/path/johnson_apsp.go
graph/path/shortest.go
graph/path/weight.go

BellmanFord is more subtle and I need to think about it some more. There is room for optimisation here, but I think overall this is a win in terms of flexibility and in cases where there are large disconnected graphs, a reduction in overall space.
Updates #486

graph/path: allow incremental path building for Dijkstra

---

mathext/digamma_test.go

This makes the tests abs or rel, and fixes an expectation that does not match wolfram-alpha, -1.1111...e9 should give cmplx.Inf(), which math.NaN() is close enough to. I don't know why the 30.49... was there in the tests, but it was only passing because got was NaN.
Closes #306.

mathext: fix test

---

optimize/global.go
optimize/local.go
optimize/minimize.go
optimize/types.go
optimize/unconstrained_test.go

This modifies Settings to allow specifying an initial location and properties of the function (value, gradient, etc.). This allows to work with local optimizers that are seeded with initial settings. This has two fields that must be specified, InitX and InitValues. Ideally this would only be one location, but the difficulty is that the default value of the function is 0. We either must require the user to specify it is set (in this case that InitValues is non-zero), or require the user to change the default value away if it is not set. The former seems much safer.

optimize: Change Settings to allow InitialLocation

---

graph/encoding/dot/decode.go

The git PR rendering of this completely fails the utility test; you must select the blankness in order to be able to see that there is a tab present.

encoding/dot: run gofmt

---

stat/stat.go
stat/stat_test.go

This CL exposes some hidden documentation about stat.CumulantKinds and
refactors the current empirical Quantile into its own function.

stat: refactor Quantile to prepare for more CumulantKinds

---

AUTHORS
CONTRIBUTORS
graph/network/page.go
graph/network/page_test.go

I implemented edge-weighted PageRank algorithms in `graph/network` package.
Although there seems to be no related issue, i hope this PR resolve [one of TODOs](https://github.com/gonum/gonum/blob/master/graph/network/network.go#L6).

Add edge-weighted PageRank algorithms

---

graph/internal/set/same.go
graph/internal/set/same_appengine.go
graph/topo/non_tomita_choice.go
graph/topo/tomita_choice.go
internal/asm/c128/stubs_amd64.go
internal/asm/c128/stubs_noasm.go
internal/asm/c64/stubs_amd64.go
internal/asm/c64/stubs_noasm.go
internal/asm/f32/ge_amd64.go
internal/asm/f32/ge_noasm.go
internal/asm/f32/stubs_amd64.go
internal/asm/f32/stubs_noasm.go
internal/asm/f64/axpy.go
internal/asm/f64/dot.go
internal/asm/f64/ge_amd64.go
internal/asm/f64/ge_noasm.go
internal/asm/f64/scal.go
internal/asm/f64/stubs_amd64.go
internal/asm/f64/stubs_noasm.go
internal/math32/sqrt.go
internal/math32/sqrt_amd64.go
mat/cblas_test.go
mat/index_bound_checks.go
mat/index_no_bound_checks.go
mat/offset.go
mat/offset_appengine.go

I've resisted this for a long time, but it seems that the convention in the Go tree is to have a space between the comment token and the `+build` (I think this is odd given that the `//go:` directives are abutted, but the data are there:
```
~/go [(go1.10.3)*]$ grep -Rl '// +build' | wc -l
936
~/go [(go1.10.3)*]$ grep -Rl '//+build' | wc -l
4
```
This change conforms all the build tag comments to this convention.
Done by `sed -i -e 's|//+build|// +build|' $(grep -l '//+build' -R|grep \.go$)`.

all: conform build tag comment to convention

---

graph/encoding/dot/decode_test.go

graph/encoding/dot: add test for chained edge attributes

---

mat/cblas_test.go

Note that this may segfault when run because of OpenBLAS's thread limits - it's safe to run with GOMAXPROCS=1 or possibly GOMAXPROCS << NUM_CPU.
Fixes #548

mat: fix incorrect netlib import

---

lapack/gonum/dpotrs.go
lapack/gonum/lapack_test.go
lapack/lapack.go
lapack/lapack64/lapack64.go
lapack/testlapack/dpotrs.go
mat/cholesky.go

Not really a necessary addition but I felt like adding something new to our lapack implementation and this looked easy enough to do within my free time constrains. Apart from that, I do think it is good to move as much of the computational stuff to lapack as possible and let `mat` only do the matrix handling around it.

lapack/gonum, mat: add Dpotrs and use it in Cholesky

---

floats/floats.go

Signed-off-by: Francesc Campoy <campoy@golang.org>

floats: use asm version of AddConst when available

---

stat/stat.go
stat/stat_test.go

BenchmarkLinearRegression/n10wtot-8        23.2          23.6          +1.72%
BenchmarkLinearRegression/n10wtot-8        23.7          23.9          +0.84%
BenchmarkLinearRegression/n10wtot-8        23.8          26.6          +11.76%
BenchmarkLinearRegression/n10wtot-8        23.4          25.4          +8.55%
BenchmarkLinearRegression/n10wtot-8        23.5          25.0          +6.38%
BenchmarkLinearRegression/n10wtof-8        120           99.8          -16.83%
BenchmarkLinearRegression/n10wtof-8        125           97.1          -22.32%
BenchmarkLinearRegression/n10wtof-8        122           92.1          -24.51%
BenchmarkLinearRegression/n10wtof-8        120           92.6          -22.83%
BenchmarkLinearRegression/n10wtof-8        122           91.0          -25.41% …

stat: optimize LinearRegression code, providing speedups of 40%

---

blas/blas32/blas32.go
blas/blas64/blas64.go
blas/cblas128/cblas128.go
blas/cblas64/cblas64.go

This was noticed while adapting JuliaLang/Microbenchmarks#27 to the new
Gonum import paths.
This CL somewhat clarifies the correct default implementation (pure-Go)
used by the various blas{32,64} and cblas{64,128} packages.

blas: fix documentation of Use functions

---

blas/blas64/blas64.go
lapack/testlapack/dgebak.go
lapack/testlapack/dgebal.go
lapack/testlapack/dlacn2.go
lapack/testlapack/dorg2l.go
lapack/testlapack/dorgql.go
lapack/testlapack/general.go
lapack/testlapack/matgen.go
mat/cholesky.go
mat/format_test.go

Reorder vector and matrix struct fields to match the order in which BLAS
routines accept them. This makes calls with inline declarations with
unnamed fields consistent with the `blas/gonum` package and so easier to understand.
Taken over from https://github.com/gonum/blas/issues/201

blas/blas64: reorder struct fields

---

lapack/gonum/dgebak.go
lapack/gonum/dgebal.go
lapack/gonum/general.go
lapack/lapack.go
lapack/testlapack/dgebak.go
lapack/testlapack/dgebal.go

`Dgebal` and `Dgebak` are the only remaining functions that use the generic `Job` type. This PR adds a dedicated `BalanceJob` type and removes the `Job` and `Comp` types. This breaks the netlib/lapack packages, a follow-up PR to do the necessary changes there is ready.
Updates #570
Updates https://github.com/gonum/lapack/issues/163
It is only an update because:
1. ~~There is still the generic `Comp` type~~
2. I'm not sure whether we need a dedicated `None` constant for each type. There are `SVDNone` and `GSVDNone` for SVD but no such constants for eigenvalues. It is probably better to add the missing constants so that it is clear which types allow the `None` option. Opinions?
3. I want to review the names; after a quick look (G)SVD jobs use (G)SVD as a prefix, EV jobs use EV as a suffix, …

lapack: add BalanceJob type, remove Job and Comp types

---

AUTHORS
CONTRIBUTORS
stat/distuv/lognormal.go
stat/distuv/lognormal_test.go
stat/distuv/norm.go
stat/distuv/norm_test.go

stat/distuv: more accurate calculation of Normal.CDF and LogNormal.CDF

---

graph/encoding/dot/encode_test.go
graph/encoding/dot/example_test.go
graph/encoding/graphql/decode_test.go
graph/topo/2sat_example_test.go
lapack/testlapack/dgebak.go
lapack/testlapack/dgebal.go
lapack/testlapack/dlacn2.go
lapack/testlapack/dorg2l.go
lapack/testlapack/dorgql.go
lapack/testlapack/general.go
lapack/testlapack/matgen.go
mat/cholesky.go
optimize/linesearcher_test.go
stat/samplemv/sample_test.go

Two cases are left as is because the code is test code and is more readable without a key; it is a `mat.Transpose` literal.
```
$ go vet -composites ./...
stat/spatial/spatial_areal_example_test.go:34: gonum.org/v1/gonum/mat.Transpose composite literal uses unkeyed fields
stat/cca_example_test.go:35: gonum.org/v1/gonum/mat.Transpose composite literal uses unkeyed fields
```

all: quieten vet's complaints about unkeyed composite literals

---

stat/spatial/spatial_example_test.go

This stops vet complaining for stat/spatial. ~~I'm not really happy about the 2sat change, but it is the documented behaviour in testing and vet doesn't like it though godoc will render it.~~

stat/spatial: fix example name suffix

---

README.md

It looks like travis doesn't resolve travis-ci.org anymore, so we add the www. prefix. The link also now points to all the branches rather than current which is most likely to be a PR status, rather than the master which is more relevant to most people.

README: fix travis badge and link

---

graph/multi/directed.go
graph/multi/directed_test.go
graph/multi/undirected.go
graph/multi/undirected_test.go
graph/multi/weighted_directed.go
graph/multi/weighted_directed_test.go
graph/multi/weighted_undirected.go
graph/simple/dense_directed_matrix.go
graph/simple/dense_undirected_matrix.go
graph/simple/densegraph_test.go
graph/simple/directed.go
graph/simple/directed_test.go
graph/simple/simple.go
graph/simple/undirected.go
graph/simple/undirected_test.go
graph/simple/weighted_directed.go
graph/simple/weighted_directed_test.go
graph/simple/weighted_undirected.go
graph/simple/weighted_undirected_test.go

There were a multitude of sins uncovered by looking into a simple fix to the `multi.WeightedUndirectedGraph` type sent by @highway900.
These were missed because the types are not properly tested. This change fixes the problem he found and others that were identified by performing compile time type assignability tests that will stand in for proper testing in the short term.
I have moved the assignability tests into the packages proper to ensure they don't get missed in reading.
Closes #576.

graph/{multi,simple}: ensure implementations satisfy the interfaces they target

---

graph/community/louvain_directed.go
graph/community/louvain_directed_multiplex.go
graph/community/louvain_undirected.go
graph/community/louvain_undirected_multiplex.go
graph/ex/fdpclust/gn.go
graph/graph.go
graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go
graph/multigraph.go
graph/path/dynamic/dstarlite.go
graph/path/internal/testgraphs/grid.go
graph/path/internal/testgraphs/limited.go
graph/path/johnson_apsp.go
graph/simple/dense_directed_matrix.go
graph/simple/dense_undirected_matrix.go
graph/simple/directed.go
graph/simple/undirected.go
graph/simple/weighted_directed.go
graph/simple/weighted_undirected.go
graph/topo/johnson_cycles.go
graph/undirect.go

With the approach to graph node mutation on edge setting the previously existed there was an issue that the edge last used connect a pair of nodes could result in a difference in the nodes being returned by a node query compared to the same node associated with edges returned from an edge query.
This change avoids dealing with that by making it implementation dependent and stating this, and by making all the node-storing graphs we provide mutate the nodes when edges are set.
There are a number of ways to deal with the situation of maintaining consistency between edges and nodes, so I think being open to that is the best approach, and while using `int64` for edges did seem plausible, it became difficult very quickly.
Closes #31.
Fixes gonum/graph#87.
Updates #570.

graph: avoid issues around graph node retrieval subtleties

---

stat/stat.go

When the sum of weights equals 1, the unbiased estimator used to compute the variance is ill-defined. This PR adds some doc to inform the user that a biased estimator should be used instead

Add doc related to sumWeights <= 1 case when computing variance

---

graph/formats/gexf12/gexf.go
graph/formats/gexf12/gexf_test.go
graph/formats/gexf12/testdata/basic.gexf
graph/formats/gexf12/testdata/data.gexf
graph/formats/gexf12/testdata/hierarchy1.gexf
graph/formats/gexf12/testdata/hierarchy4.gexf
graph/formats/gexf12/testdata/phylogeny.gexf
graph/formats/gexf12/testdata/viz.gexf

This was largely written by aqwari.net/xml/cmd/xsdgen working on the XSD files available from the [gephy/gexf specs repository](https://github.com/gephi/gexf/tree/81ba4e7ccdc25631f836fc5caa4ed64ba5300379/specs/1.2draft), with some help; the specs use includes which cause xsdgen to fail, so I manually in-lined the includes.
The generated code was then edited to make optional attributes exist on pointers, to reduce the length of labels to within reasonably normal Go idiom and removing unnecessary namespacing.
The package is versioned since the format appears to arbitrarily be updated.

graph/formats/gexf12: new package for handling GEXF1.2 graph description files

---

graph/multi/directed.go
graph/multi/multi.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go

This fixes some bugs in the multigraph handling of edges from lines and finishes changes that I had intended to go into the iterator PR (the change in container for `graph.*Lines` in the `multi.*Edge` types).
It has also raised an issue of how I have been dealing with empty collections. With the old approach we could always return a `nil` and people could still iterate over it without needing to check for `nil`. This is no longer true. We currently don't specify the `nil`-ness of returns for collections, so this is not terrible, but it might be an idea to tighten that down. I'm raising this here since you can see the impacts with these changes, but I will file an issue (#614).

graph/multi: clean up missed changes and bugs

---

graph/formats/gexf12/gexf.go
graph/formats/gexf12/gexf_test.go

Even with mechanical help I can get XML wrong.
1. Fix `xml:` tag to omitempty for `Attribute`.
2. Fix pointer type for omitable  fields in `Graph`.
3. Make `Attributes` in `Graph` a `[]Attribute` to match the [xsd](https://github.com/gephi/gexf/blob/81ba4e7ccdc25631f836fc5caa4ed64ba5300379/specs/1.2draft/data.xsd#L6-L12) and the [rnc](https://github.com/gephi/gexf/blob/81ba4e7ccdc25631f836fc5caa4ed64ba5300379/specs/1.2draft/data.rnc#L8-L9).

gexf12: fix omitable and unbounded attributes

---

graph/formats/cytoscapejs/cytoscapejs.go
graph/formats/cytoscapejs/cytoscapejs_test.go

Fixes a copy/paste error and makes position generally optional ([optional on init](http://js.cytoscape.org/#notation/elements-json)) and source/target optional on elements (may be a node).

cytoscapejs: fix optional field marshaling and helper type naming

---

stat/stat.go
stat/stat_test.go

This PR adds the support of a new kind of `CumulantKind`: `LinInterp`
The name was suggested [here](https://github.com/gonum/gonum/pull/254/files#r144047424) so I used it.
I also took the liberty to split the test on the `Quantile` function to make the test intention clearer (functional / invalid input checks / invalid cumulant kind)

stat: add support for LinInterp CumulantKind for Quantile

---

graph/encoding/dot/decode_test.go
graph/encoding/dot/encode.go
graph/encoding/dot/encode_test.go
graph/encoding/dot/example_test.go
graph/encoding/graphql/decode_test.go
graph/topo/clique_graph_test.go

Note that prior to this change the order of the prefix and the `strict` keyword was incorrect; if `strict` was `true` and `prefix` was not `""` the output would be `strict <prefix> graph...`.
Closes #625.
/cc @32bitkid

encoding/dot: make all simple graph marshalling strict

---

blas/gonum/errors.go
blas/gonum/gonum.go

Followup from https://github.com/gonum/netlib/pull/44

blas/gonum: move panic strings into separate file

---

graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go
graph/simple/dense_directed_matrix.go
graph/simple/dense_undirected_matrix.go
graph/simple/directed.go
graph/simple/undirected.go
graph/simple/weighted_directed.go
graph/simple/weighted_undirected.go

This helps prevent the kind of errors that I found while doing this; the incomplete fix-up when removing the `Has` method.
Review requires no specific graph experience as it's almost entirely just text reordering.
Updates #616.

graph/{multi,simple}: harmonise code organisation

---

graph/encoding/dot/encode.go

The "strict" keyword mentioned in the documentation does not exist anymore

fix: documentation of Marshal was not accurate

---

mat/diagonal.go

As far as I can see, this is the only addition that is needed to satisfy the linked issue (the `Symmetric` interface is already satisfied by symmetric banded implementation, and there is no single interface for that).
Fixes #610.

mat: make Diagonal satisfy Symmetric

---

mat/diagonal.go

I'm not at all convinced by this. The concrete type already implements the methods. It seems like interface bloat. Are you sure you want this?

mat: add Banded methods to Diagonal

---

mat/diagonal.go
mat/diagonal_test.go
mat/index_bound_checks.go
mat/index_no_bound_checks.go
mat/list_test.go

I'm not really all that happy with the approach in `DiagOf` because of the mixing of view and copy, but the alternatives that I can see are less attractive; have a collection of methods for each raw type, either on `DiagDense` or (less likely) the raw types, or alternatively panicking when a non-raw type is handed in.
Fixes #609.
Updates #213.

mat: add striding to DiagDense and capacity to extract diags from other matrices

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go
graph/encoding/dot/encode.go
graph/encoding/dot/encode_test.go
graph/encoding/encoding.go
graph/internal/ordered/sort.go

This should resolve issue #396, in the way that has been discussed there. This change introduces a new pair of `MarshalMulti()` and `UnmarshalMulti()` functions, both which take `graph.Multigraph`. Please take a look.
There are a couple outstanding questions on this particular implementation:
- The arguments for `Marshal()` have remained unchanged. However, the new function `MarshalMulti()` does not include the `strict` argument, because it doesn't _really_ make any sense in that context. But, I wonder if `Marshal()` should _always_ emit a strict DOT graph, because thats what it really represents. However, that might be too big of a breaking change here.
-  In the `multiprinter.print()` function, I need to iterate lines, which I do via `lines := graph.LinesOf(g.Lines(nid, tid))`, I'm not …

graph/encoding/dot: add multigraph serialization and deserialization support 

---

AUTHORS
CONTRIBUTORS
mat/triangular_test.go

The `m < n` case was repeated twice.
Found using gocritic linter, `dupCase` checker.

fix duplicated switch case

---

graph/encoding/dot/decode.go

This makes it possible to implement the AddNode method of
graph.NodeAdder to track the nodes of a graph by DOT node
ID, as they are added.

encoding/dot: set DOT node ID before adding node to graph

---

mat/cholesky.go
mat/cholesky_test.go

A substitute for the Dlauum attempt. `Cholesky.ToSym` is not super important but with this PR it becomes slightly faster.
```
name                    old time/op  new time/op  delta
CholeskyToSym/n=10-4    2.65µs ± 2%  0.78µs ± 0%  -70.75%  (p=0.029 n=4+4)
CholeskyToSym/n=100-4    329µs ± 1%   124µs ± 0%  -62.33%  (p=0.029 n=4+4)
CholeskyToSym/n=1000-4   241ms ± 2%   175ms ± 0%  -27.34%  (p=0.029 n=4+4)
```

 mat: rewrite Cholesky.ToSym without calling SymOuterK

---

AUTHORS
CONTRIBUTORS
mat/matrix_example_test.go

Added examples in godoc for `mat.Row` and `mat.Col` function calls.
Originally discussed here: https://groups.google.com/d/msg/gonum-dev/20ReoY6VmkU/jcwejOlvCwAJ

mat: add examples for Col and Row

---

lapack/gonum/dpotri.go
lapack/gonum/lapack_test.go
lapack/lapack.go
lapack/lapack64/lapack64.go
lapack/testlapack/dgetri.go
lapack/testlapack/dlarfg.go
lapack/testlapack/dlauu2.go
lapack/testlapack/dpotri.go
lapack/testlapack/dtrti2.go
lapack/testlapack/dtrtri.go
lapack/testlapack/general.go
lapack/testlapack/matgen_test.go
mat/cholesky.go
mat/cholesky_test.go

`Dlauum` has a use after all.
```
name                        old time/op  new time/op  delta
CholeskyInverseTo/n=10-4    10.8µs ± 2%   3.2µs ± 1%  -70.16%  (p=0.008 n=5+5)
CholeskyInverseTo/n=100-4   1.07ms ± 2%  0.51ms ± 2%  -52.06%  (p=0.008 n=5+5)
CholeskyInverseTo/n=1000-4   713ms ± 1%   315ms ± 1%  -55.83%  (p=0.008 n=5+5)
```

lapack/gonum,mat: add Dpotri and use it in Cholesky

---

graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go
graph/encoding/dot/encode.go
graph/encoding/dot/encode_test.go
graph/encoding/graphql/decode_test.go

Add test case for encoding. The decoding test cases already
contained round-trip tests that trigger the unquote if
quoted code path.
Fixes #792.

graph/encoding/dot: (un)quote attributes if needed during (un)marshal

---

.travis.yml
graph/encoding/dot/encode_test.go
graph/encoding/graphql/decode_test.go

I would like to add the same check to the graphql tests, but they currently fail and will do so until the quoting PR is merged. So I'll leave until after that (or you can add it in there - unfortunately we need to just copy/paste this check function).

encoding/dot: ensure that generated DOT is syntactically valid

---

lapack/testlapack/dgecon.go

lapack/testlapack: use testing Logf instead of log.Printf

---

.travis/test-coverage.sh

This reduces the amount of output from running coverage tests, improving readability and reducing log output.

coveralls: don't run coverage tests verbosely

---

.travis.yml

This is an alternative to #800. I have confirmed that per matrix-factor-state caching is done by Travis (documented [here](https://docs.travis-ci.com/user/caching/#caches-and-build-matrices) and confirmed by experimentation). This change thus gives us both caching speed up and an informative display of build success states.

travis: use build caching and don't force complete rebuild

---

blas/testblas/dtrsm.go

This PR rewrites DtrsmTest so that it would have caught the matrix stride bugs fixed in #801.
Also adds one test case to cover the branch for `alpha == 0`.

blas/testblas: rewrite DtrsmTest to test various matrix strides

---

blas/testblas/level1double.go

I missed this in the previous clean up. Also fix the mangled imports.

testblas: use testing Log instead of log.Println

---

graph/path/floydwarshall.go
graph/path/johnson_apsp.go
graph/path/negative_cycles_example_test.go
graph/path/shortest.go

Over the past ... time ... I've been having doubts about my claim for the approach obtaining a complete set of negative cycles in a graph using iterated Bellman-Ford probing. Today I checked it and my concerns were well founded, so I have removed that.
Wanting to have some way of doing this, I added an example using Floyd-Warshall and found that with negative cycles, `AllShortest` will never complete when a negative cycle exists. So I have fixed that by just not providing a mechanism to obtain the path. This is a bit of a dodge, but we can add it later if we want. The additional cost for the `FloydWashall` is an approximate doubling of time when a negative cycle exists. I think this is OK, but could be convinced otherwise (maybe add an option to retain the data for the call, or add a …

graph/path: fix negative cycle handling by AllShortest and FloydWarshall

---

graph/multi/directed_test.go
graph/multi/undirected_test.go
graph/multi/weighted_directed.go
graph/multi/weighted_directed_test.go
graph/multi/weighted_undirected.go
graph/multi/weighted_undirected_test.go
graph/testgraph/testgraph.go

This was found when I was implementing the edge reversal API and testing, but it should be done regardless of that and without the additional overhead of understanding it as well.

graph/{multi,simple,testgraph}: extend edge testing

---

.travis.yml
.travis/check-generate.sh
.travis/install-gocc.sh
go.mod
unit/generate_unit.go

See #838 for background.
This makes some preparatory changes for using Go modules and for the most part works around the changes that transiently happened to travis' behaviour when a go.mod file existed. It did not completely fix that, but that is not longer necessary.

travis: preparatory changes for Go modules in builds

---

num/dualquat/doc.go
num/dualquat/dual.go
num/dualquat/dual_example_test.go
num/dualquat/dual_fike.go
num/dualquat/dual_simple_example_test.go
num/dualquat/dual_test.go
num/quat/conj.go

I have struggled with getting the trig functions to work with these packages and this has prevented me from sending this. Given that the primary use for these types of numbers is to allow 2D and 3D translations and rotations, something that doesn't require trig in this number space, I have decided that discretion is the better part of valor and have removed them. The problems I was facing were compounded (but not entirely caused) by the odd behaviour of "math/cmplx" for some of these functions. If people want trig functions for these, they can file an issue and then I can look at it again (the almost working code is in dualquat-full).
~There is one issue that I am not entirely sure of yet, and I think stems from the commutativity of complex numbers when quaternions are not commutative …

num/dualquat: package for dual quaternion maths

---

AUTHORS
CONTRIBUTORS
integrate/quad/internal/PrintGoSlice.m
integrate/quad/internal/genherm.m

There are just a couple source files that are encoded as  ISO-8859-1 instead of UTF-8.  Let's make them UTF-8, unless there's a reason for them not to be.

Convert two files from ISO-8859-1 to UTF-8

---

appveyor.yml

AppVeyor are taking too long, so comment out the go1.12 line.

appveyor: comment out go1.12 until appveyor update

---

.travis.yml
.travis/check-generate.sh
.travis/install-gocc.sh

At the moment, I am doing a nasty (but now correct) git workaround to get rid of changes to `go.mod`. These changes come about because the go tool finds the latest versions of the pre-installed tools specified in the `before_install` yaml stanza. To get these to install at the appropriate version, we need to be in the gonum/gonum directory so the go tool can see go.mod, but I don't think this is where travis is by the time that stanza is run.
I think in the long run (once modules are supported by all the versions of Go we support), we can `cd gonum/gonum && go get ./...` in `before_install` to get our dependencies.

travis: check that we work with modules

---

graph/community/louvain_common.go
graph/encoding/dot/decode.go
graph/encoding/dot/encode_test.go
graph/encoding/dot/example_test.go
graph/graph.go
graph/iterator/edges_test.go
graph/iterator/lines_test.go
graph/multi/directed_test.go
graph/multi/multi.go
graph/multi/undirected.go
graph/multi/undirected_test.go
graph/multi/weighted_directed_test.go
graph/multi/weighted_undirected.go
graph/multi/weighted_undirected_test.go
graph/multigraph.go
graph/path/a_star_test.go
graph/simple/densegraph_test.go
graph/simple/directed_test.go
graph/simple/simple.go
graph/simple/undirected.go
graph/simple/undirected_test.go
graph/simple/weighted_directed_test.go
graph/simple/weighted_undirected.go
graph/simple/weighted_undirected_test.go
graph/testgraph/testcases.go
graph/testgraph/testgraph.go
graph/topo/clique_graph.go
graph/undirect.go

I'm sending this as a candidate implementation addressing #825. After having sat on this for a while, I'm fairly convinced this is the right thing to do; if fixes unfortunate subtleties and an otherwise insoluble bug (~~#417~~#824) at the cost of requiring an extra method on edge and line types.
I am not convinced of my approach to naming the methods because, as it stands (the two versions here), either a type assertion is needed for lines, or edges and lines are not interchangeable without wrapping. I think that probably the method names should be `ReversedEdge` and `ReversedLine` to avoid this collision.

graph: make edges and lines reversible

---

.travis/check-generate.sh
go.mod
go.sum

Including netlib since the tests can be run with it and it now tests correctly.
go.sum included since that appears to be preferred practice.

modules: add gonum.org/v1/netlib to go.mod and commit go.sum

---

graph/community/k_communities_test.go
graph/graphs/gen/batagelj_brandes_test.go
graph/internal/set/set.go
graph/internal/set/set_test.go
graph/topo/bron_kerbosch.go
graph/topo/bron_kerbosch_test.go
graph/topo/clique_graph.go
graph/topo/clique_graph_test.go

Looking at the benchmarks for this approach, we have a better outcome than the original code for `community.KCliqueCommunities` and a better outcome than the pointer approach in #900 for `topo.BronKerbosch` and `topo.CliqueGraph`.
<table class='benchstat'>
<tr><th>name</th><th>original time/op</th><th>pure function time/op</th><th>delta</th>
<tr><td>KCliqueCommunities/simple-k=3-8</td><td>76.1µs ± 2%</td><td>61.1µs ± 3%</td><td>-19.81%</td><td>(p=0.000 n=17+20)</td>
<tr><td>KCliqueCommunities/Batagelj-Zaversnik_Graph-k=3-8</td><td>230µs ± 3%</td><td>184µs ± 1%</td><td>-19.83%</td><td>(p=0.000 n=20+17)</td>
<tr><td>KCliqueCommunities/Batagelj-Zaversnik_Graph-k=4-8</td><td>229µs ± 2%</td><td>183µs ± 1%</td><td>-20.02%</td><td>(p=0.000 n=19+18)</td> …

 graph/internal/set: make complex set operations pure functions 

---

unit/unit_test.go
unit/unittype.go

unit: make printing of units concurrently safe and unicode-aware

---

unit/doc.go

A note for why the slide example was changed from area to volume: cell counting is a volumetric measurement using an engineered slide called a hemocytometer with a precisely defined height (usually 0.1mm). The area for counting is generally the 1mm^2 finely divided centre square.
Fixes #730.

unit: fix up package docs

---

mat/eigen.go
mat/eigen_example_test.go
mat/symmetric.go
stat/mds/mds.go

This is in line with the other factorization extraction methods.
Fixes #847.

Move EigenvectorsSym to VectorsTo

---

graph/community/k_communities.go
graph/traverse/traverse.go
graph/traverse/traverse_test.go

It could be argued that the `Visit` could go away completely, since the `until` parameter can now be used to do the same thing. However, `until` differs between `BreadthFirst` and `DepthFirst` so that BF can stop after a certain depth. This means that a visitors for `BreadthFirst` and `DepthFirst` would not be interchangeable. For this reason I have kept it.
Fixes #913.

graph/traverse: reduce edge confusion

---

lapack/lapack64/lapack64.go
mat/eigen.go
mat/svd.go

This comes from the recent rework of parameter checks in `lapack/gonum` and `lapack/netlib`. The idea is that these two packages should follow the reference in that the leading dimension is always at least 1, even if the matrix is not referenced. This is inconvenient for Go and our `mat` and their zero default values. I think that `lapack64` is the right place where to do this zero-to-one translation.

lapack/lapack64: call lapack functions with stride always at least 1

---

mat/cholesky.go
mat/cholesky_example_test.go
mat/cholesky_test.go
mat/hogsvd.go
mat/lq.go
mat/lq_test.go
mat/lu.go
mat/lu_test.go
mat/qr.go
mat/qr_test.go
mat/solve.go
optimize/newton.go
stat/distmat/wishart.go
stat/distmv/normal.go
stat/distmv/statdist.go
stat/distmv/studentst.go
stat/statmat.go

mat: Rename Solve(Vec) to Solve(Vec)To

---

graph/community/louvain_common.go
graph/encoding/dot/encode.go
graph/encoding/graphql/decode.go
graph/traverse/traverse.go
lapack/gonum/dlaqr04.go
lapack/gonum/dsytd2.go
optimize/functions/functions.go

At a couple of places I also moved the article from the end of a line to the beginning of the next one.

all: fix "the the" typo in comments

---

fourier/fourier.go
graph/network/page.go
integrate/quad/hermite.go
lapack/gonum/dlaqr5.go
lapack/gonum/dlatrs.go
lapack/gonum/doc.go
mat/format.go
mat/hogsvd_test.go
stat/distuv/categorical.go
stat/sampleuv/weighted.go
stat/spatial/spatial.go

Prompted by #930.
This was done on `fix-the-the` and then cherry picked to here to avoid conflicts.

all: fix repeated word typos in comments

---

graph/encoding/digraph6/digraph6.go
graph/encoding/digraph6/digraph6_test.go
graph/encoding/graph6/graph6.go
graph/encoding/graph6/graph6_example_test.go
graph/encoding/graph6/graph6_test.go

Note that the copyright date is last year because that's when it was written.

 graph/encoding/{,di}graph6: add support for digraph6- and graph6-encoded graphs

---

mat/cholesky_test.go
mat/symmetric.go
mat/symmetric_test.go
stat/distmv/dirichlet.go

The `Sym` suffix implies the square, and allows the `Tri` and banded API extensions when they are needed. It's also shorter.
Closes #174.

mat: rename SliceSquare=>SliceSym and GrowSquare=>GrowSym and return Symmetric

---

lapack/testlapack/dgesvd.go

A single higher precision `tol` is replaced with `tol/10`. The rest are retained as they are.

lapack/testlapack: replace all literal constants in dgesvdTest with tol expressions

---

AUTHORS
CONTRIBUTORS
mat/dense_test.go
mat/matrix.go
mat/symmetric_test.go
mat/triangular_test.go
mat/vector_test.go

Please take a look. Should be #946 committed correctly.

mat: add fast paths to matrix sum function

---

stat/roc.go
stat/roc_example_test.go
stat/roc_test.go

Closes #708.
Fixes #316.
Closes #960.

stat: define ROC cutoffs instead of using number of cutoffs

---

mat/diagonal_test.go
mat/triangular.go
mat/triangular_test.go

optimize the paths for diagonal matrices in MulTri.  there was a TODO and i use tri*diag a lot.
add benchmarks for multri
the performance improvement is pretty ridiculous as it cuts 1 or 2 dimensions out of the problem.
<table class='benchstat oldnew'>
<tr class='configs'><th><th>old.txt<th>new.txt
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta
<tr class='unchanged'><td>TriMul1000-4<td>2.77s ± 6%<td>2.79s ± 3%<td class='nodelta'>~<td class='note'>(p=0.549 n=10&#43;9)
<tr class='better'><td>TriMulDiag1000-4<td>1.71s ± 6%<td>0.01s ± 3%<td class='delta'>−99.53%<td class='note'>(p=0.000 n=9&#43;9)
<tr class='better'><td>TriMul2Diag1000-4<td>1.30s ± 2%<td>0.00s ±15%<td class='delta'>−99.96%<td class='note'>(p=0.000 n=9&#43;10)
<tr><td>&nbsp;
</tbody>
</table>

mat: optimize multri

---

bound/bound.go
bound/bound_test.go

Add Union helper for bound package
Updates: #939

bound: Add Union helper for bound package

---

bound/bound.go
bound/bound_test.go

bound: rewrite tests to use tables and fix unsorted input handling for Union

---

spatial/barneshut/barneshut2.go
spatial/barneshut/barneshut2_test.go
spatial/barneshut/barneshut3.go
spatial/barneshut/barneshut3_test.go
spatial/barneshut/bounds.go
spatial/barneshut/doc.go
spatial/barneshut/galaxy_example_test.go
spatial/barneshut/no_bounds.go
spatial/r2/doc.go
spatial/r2/vector.go
spatial/r3/doc.go
spatial/r3/vector.go

The initial commit is essentially the same as the code that was merged into exp (barring grammatical fixes). The two later commits address the [comment](https://github.com/gonum/exp/pull/27#discussion_r279701191) that the vectors could go into their own packages.

spatial/barneshut: add Barnes-Hut force approximation package and R2/R3 helpers

---

spatial/kdtree/doc.go
spatial/kdtree/kdtree.go
spatial/kdtree/kdtree_simple_example_test.go
spatial/kdtree/kdtree_test.go
spatial/kdtree/kdtree_user_type_example_test.go
spatial/kdtree/medians.go
spatial/kdtree/medians_test.go
spatial/kdtree/nbpoints_test.go
spatial/kdtree/points.go

This is a reworking of the bíogo kdtree implemented in 2012. I was the only author on the files in that package, so it can be brought into Gonum without any additional licensing.
I have polished up some of the more glaring gotchas (sentinels are now removed from sets filled by the nearest neighbour search for example) and removed gocheck from the tests. One issue that needs consideration is the iteration termination signal. I use a boolean to indicate when the iteration has been completed. This has the advantage that an empty return means continue, but I'm open to discussion on this (an error return could be a possibility - similar to `filepath.Walk`).
See https://github.com/gonum/exp/pull/27#issuecomment-484435947

spatial/kdtree: new package implementing k-d tree storage

---

go.mod

I don't see any documentation about this, but the change here fixes the problem. Confirming that this is a fix requires that the reviewer check the "Allowed Failures" master branch tests on travis.
See golang/go#32147.

modules: prevent go tool mutating go.mod to add a go version line

---

spatial/r1/bound.go
spatial/r1/doc.go
spatial/r1/interval.go
stat/distmv/statdist.go
stat/distmv/statdist_test.go
stat/distmv/uniform.go
stat/distmv/uniform_test.go
stat/samplemv/sample_test.go

Mechanically generated with:
```
$> gomvpkg -from gonum.org/v1/gonum/bound -to gonum.org/v1/gonum/spatial/r1 -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
```
Fixes gonum/gonum#956.

spatial/r1: import and rename from bound

---

spatial/barneshut/barneshut2.go
spatial/barneshut/barneshut3.go
spatial/vptree/vptree.go

spatial/{barneshut,vptree}: refuse points at infinity

---

spatial/barneshut/barneshut2.go
spatial/barneshut/barneshut2_test.go
spatial/barneshut/barneshut3.go
spatial/barneshut/barneshut3_test.go

It turns out the previous check was not strict enough. When the quadrants and octants are being subdeivided, if the box is large enough the midpoint will be numerically identical to one of the bounds. This results in an infinite recursion down the tree, overflowing the stack.
The approach here is to restrict the area/volume to within sqrt(maxfloat) of the origin as a heuristic and then check for non-progression during tree construction.

spatial/barneshut: catch finitely too far points

---

spatial/vptree/vptree.go
spatial/vptree/vptree_simple_example_test.go
spatial/vptree/vptree_test.go
spatial/vptree/vptree_user_type_example_test.go

Addresses https://github.com/gonum/gonum/pull/1009#issuecomment-506244683.

spatial/vptree: return error rather than panic

---

mat/vector.go
mat/vector_test.go

Please take a look. New tests fail without the change in `CopyVec`.
Fixes #1012.
/cc @xiegeo

mat: ensure number of elements to be copied is sanitised for blas64

---

graph/iterator/nodes_unordered.go
graph/iterator/nodes_unordered_test.go

This is mainly a reminder for me to ensure that I implement the remainder and the unsafe version when I can. In the meantime it can be used by clients using go1.12+ in their implementations.
Updates #1019.

graph/iterator: add unordered node iterator

---

graph/iterator/edges_test.go
graph/iterator/lines_test.go
graph/iterator/nodes_test.go

Noticed in #1020 that the tests don't actually test the exercise of the `Reset` method.

graph/iterator: properly test iterator reset

---

graph/iterator/nodes_unordered.go
graph/iterator/nodes_unordered_test.go

graph/iterator: guard against iteration panic

---

.travis/script.d/test-coverage.sh

This got lost in the multi-os testing system.
TBR

travis: only run coverage when secure and on master

---

graph/multi/directed.go
graph/multi/weighted_directed.go
graph/simple/directed.go
graph/simple/weighted_directed.go

This fixes an incorrect optimisation in the directed graph implementations found by @yinyanghu.
Closes #1026.

graph/{multi,simple}: fix empty To optimisation

---

stat/combin/combin.go

It's confusing to say that Combination generates the next combination, when really it generates the current one with Next doing the advancing.

stat/combin: Fix CombinationGenerator comment

---

mat/dense_arithmetic.go

Alternative to #989 
There still needs more paths to be "fully compliant" but this at least simplifies the code.

mat: Use untransposeExtract in Dense.Mul

---

graph/testgraph/testcases.go
graph/testgraph/testgraph.go

It turns out the implementations were correctly behaving, but I think this was more fortuitous than by design.
I'm interested to know how @yinyanghu found the bug. I don't think it was from the behaviour, but if it was, can you show me the case that was failing and I will add it here.
Fixes #1030.

graph/testgraph: test for missing From and To paths

---

lapack/gonum/dlatbs.go
lapack/gonum/lapack_test.go
lapack/testlapack/dlatbs.go
lapack/testlapack/matgen.go

This is one of the uglier lapack routines, especially in combination with the band storage.
The coverage is almost complete, so hopefully this translation is also correct.
There are some differences from the Fortran version that I'll be happy to explain. Almost all are done to make the code clearer. I left one `goto` to not increase the indentation further.

lapack/gonum: add Dlatbs

---

lapack/gonum/dlatbs.go
lapack/gonum/dpbtf2.go
lapack/gonum/dpbtrf.go
lapack/gonum/dpbtrs.go
lapack/testlapack/dlatbs.go
lapack/testlapack/general.go

lapack/gonum: fix matrix slice length checks in banded functions

---

graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go
graph/simple/directed.go
graph/simple/undirected.go
graph/simple/weighted_directed.go
graph/simple/weighted_undirected.go

graph/{multi,simple}: don't allocate edge maps before they are needed

---

mat/shadow_test.go

This should have been removed in b525d7913dd261918ae034cec2be3add20e32f63 when the code was switched to rectangular.

mat: remove dead code in overlap testing

---

mat/cdense.go
mat/cmatrix.go
mat/offset.go
mat/offset_appengine.go
mat/shadow.go
mat/shadow_common.go
mat/shadow_complex.go

This is initial bootstrapping work to allow generation of CDense from Dense.
I'm not sure of `RawCMatrix`. Is this what we want?

mat: add minimal shadow detection for complex matrices

---

.travis/run-parts

At the moment, it's printing file names for missing headers, but not failing.

travis: make sure checks exit non-zero if they fail

---

lapack/testlapack/dgecon.go
lapack/testlapack/dpbcon.go

* Now that we understand that a mismatch between the exact and estimated condition number is normal, the logging of the mismatch can be removed.
* In general in lapack I prefer randomized tests.
* I don't know what I was thinking when I wrote the Dpbcon test.

lapack/testlapack: rewrite and extend test for Dgecon

---

graph/path/bellman_ford_moore.go
graph/path/bench_test.go

Hey there,
I started working on the _todo_ left in the [bellman_ford_moore-file](https://github.com/gonum/gonum/blob/master/graph/path/bellman_ford_moore.go): "Consider adding further optimisations"
This semester I finished an algorithm course at my university. We learned based on [Sedgewick & Wayne](https://books.google.de/books?id=MTpsAQAAQBAJ&pg=PA672&lpg=PA672&dq=Sedgewick+%26+Wayne+queue+bellman+ford&source=bl&ots=QfpHzOG8nZ&sig=ACfU3U32xLZKnJsvoSeKNpQzY_6oTm-GJg&hl=en&sa=X&ved=2ahUKEwjYodKmha3kAhVCKVAKHflyCqwQ6AEwC3oECAkQAQ#v=onepage&q=Sedgewick%20%26%20Wayne%20queue%20bellman%20ford&f=false) suggestion a queue approach is to be preferred since we only have to relax those nodes whose vertex distance changed in the previous iteration.
While the worst case complexity is still **O(|V| …

graph/path: Adjusted bellman ford algorithm to use queue.

---

mat/dense_arithmetic.go
mat/errors.go

mat: use "mat" prefix for all errors and panics

---

mat/cholesky.go
mat/eigen.go
mat/gsvd.go
mat/hogsvd.go
mat/lu.go
mat/svd.go

Should the documentation of other *To functions like `Cholesky.InverseTo`, `Cholesky.SolveTo` or `LU.SolveTo` be also adapted to describe the behavior w.r.t. `dst` parameter?

mat: clean up docs

---

stat/distmat/wishart.go
stat/distmat/wishart_test.go

At the moment, `RandCholTo` doesn't care about sizes. Do we want it to?
Updates #1081.

stat/distmat: change methods to accept empty instead of nil matrices

---

mathext/airy.go
mathext/internal/amos/amos.go
mathext/internal/amos/amos_test.go
mathext/internal/amos/origcode_test.go

This also suggests that there should be consideration about the error status returns here.

mathext/amos/internal/amos: clean up linter warnings

---

mathext/internal/cephes/incbi.go

mathext/internal/cephes: remove redundant zero assignment

---

graph/path/dynamic/dstarlite.go
graph/path/dynamic/dumper_test.go

dynamic: clarify use of inequality with float-based keys

---

mathext/internal/amos/amos.go
mathext/internal/amos/amos_test.go

mathext/internal/amos: remove overwrite before first use and non-used

---

spatial/kdtree/kdtree_test.go
spatial/vptree/vptree_test.go

spatial/{kdtree,vptree}: fix lint warnings

---

graph/path/a_star.go

This is an alternative to #1113 that gives the full benefits of the change to lazy addition to the shortest path tree during `AStar` execution, while also retaining the implied semantics of `graph.Graph` (that the graph does not change under the callee's feet).
This reduces total volume of allocations, particularly in the case where there is a heuristic provided at the cost of allocating more often in general. In the same situation, the time taken is dramatically improved. It also reduces the requirement of the input graph's method set (to match now what `Dijkstra` needs).
Closes #1113.
/cc @phyrwork
<details>
<table class='benchstat oldnew'>
<tr class='configs'><th><th>old<th>new
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta
<tr …

graph/path: add nodes to shortest path tree lazily

---

AUTHORS
CONTRIBUTORS
integrate/romberg.go
integrate/romberg_test.go

This PR implements the Romberg integration scheme. There are two methods: `Romberg` and `RombergHL`. The latter is simply a convenience function, which can be useful for cases where users don't want to allocate a `work` array themselves.

Integrate: Add Romberg integration

---

blas/gonum/level1float32.go
blas/gonum/level1float64.go
blas/gonum/single_precision.bash
floats/floats.go
floats/floats_test.go
internal/asm/f32/l2norm.go
internal/asm/f32/l2norm_test.go
internal/asm/f64/l2norm.go
internal/asm/f64/l2norm_test.go

This brings a significant improvement to `floats.Norm(x, 2)` call performance at the cost of a disagreement with `floats.Distance(s, t, 2)` beyond 1e-15. This disagreement could be reconciled by adding a two-parameter `L2Norm` to asm that matches the one-parameter version here. If we want to go ahead with this, I'll do that.
<details>
<table class='benchstat oldnew'>
<tr class='configs'><th><th>old.bench<th>new.bench
<tbody>
<tr><th><th colspan='2' class='metric'>time/op<th>delta
<tr class='better'><td>Norm2Small-8<td>106ns ± 1%<td>29ns ± 4%<td class='delta'>−73.08%<td class='note'>(p=0.000 n=10&#43;10)
<tr class='better'><td>Norm2Medium-8<td>18.1µs ± 1%<td>2.1µs ± 3%<td class='delta'>−88.40%<td class='note'>(p=0.000 n=10&#43;10)
<tr …

internal/asm,blas,floats: move level 2 norm to asm

---

lapack/testlapack/dlantr.go

Not strictly necessary but would have hinted probably much earlier at the root cause of the issue fixed in https://github.com/gonum/netlib/pull/67

testlapack: allocate work only for MaxColumnSum in DlantrTest

---

graph/encoding/digraph6/digraph6.go
graph/encoding/dot/encode_test.go
graph/encoding/graph6/graph6.go
graph/layout/eades_test.go
graph/layout/isomap_test.go
graph/path/bench_test.go
graph/simple/weighted_directed_test.go
graph/topo/bench_test.go
graph/traverse/traverse_test.go

These were all identified by golangci-lint. The remaining two lint issues are false positives:
```
encoding/dot/decode.go:152:2: `graphAttr` is unused (structcheck)
graphAttr, nodeAttr, edgeAttr encoding.AttributeSetter
^
topo/2sat_example_test.go:177:1: tests: ExampleTarjanSCC_2sat refers to unknown field or method: TarjanSCC.2sat (govet)
func ExampleTarjanSCC_2sat() {
^
```
The first is golangci/golangci-lint#826 and the second is golang/go#23864.

graph: clean up lint

---

blas/blas64/blas64_test.go
blas/cblas128/cblas128.go
blas/cblas128/cblas128_test.go
blas/cblas64/cblas64.go

Running through this, I identified a discordance in the APIs of blas64 and cblas128 in how level 1 operations (or other operations with vectors) are performed. These should be made concordant (#1156).
Fixes #1156.

blas/{blas64,cblas128}: test wrapping of blas interfaces

---

.travis.yml
.travis/script.d/test-coverage.sh

This was just added to travis. There is no documentation for it yet.

travis: remove windows autocrlf workaround and use .travis.yml configuration

---

blas/blas32/blas32.go
blas/blas64/blas64.go
blas/cblas128/cblas128.go
blas/cblas64/cblas64.go

So it turns out we partially did this already in blas64, and I left out blas32 with the vector length fields. Things are now harmonised.
Closes #1158.

blas: fix up length handling

---

floats/floats_test.go
internal/asm/f64/l2norm.go
internal/asm/f64/l2norm_amd64.s
internal/asm/f64/l2norm_noasm.go
internal/asm/f64/l2norm_test.go
internal/asm/f64/stubs_amd64.go

Netlib algorithm reduces overflow while calculating the l2norm of a
vector.
Translated to asm while reducing branches in NaN and Inf checks.
Overflow protection is equivalent to the Netlib standard implementation.
Builds upon #1134 to further speed up L2Norm operations.
<details>
<summary>Speedup ~-33%</summary>
```
name                                 old time/op    new time/op    delta
L2NormNetlib/L2NormUnitary-1-8         5.08ns ± 2%    5.20ns ± 3%   +2.36%  (p=0.019 n=10+10)
L2NormNetlib/L2NormUnitary-3-8         9.00ns ± 2%    8.64ns ± 3%   -3.95%  (p=0.000 n=10+10)
L2NormNetlib/L2NormUnitary-10-8        27.6ns ± 4%    22.1ns ± 1%  -19.84%  (p=0.000 n=10+9)
L2NormNetlib/L2NormUnitary-30-8        89.5ns ± 6%    61.8ns ± 1%  -31.00%  (p=0.000 n=10+10)
L2NormNetlib/L2NormUnitary-100-8 …
```

translate netlib l2norm algorithm to asm and remove branches

---

lapack/gonum/lapack_test.go

I have run the tests with `-race` locally and there is no problem (except taking 10 times longer than without `-race`).
Closes #1170.

lapack/gonum: run tests in parallel

---

internal/asm/f64/l2norminc_amd64.s

This is the minimal change required to fix the issue. I can replicate the bug on my work workstation, so presumably it only presenting on macOS at travis is down to CPU execution ordering differences.
The changes that are in asm/f64_l2norm_zeroing which are presumably performance oriented (from my reading around PXOR/XORPS differences) can go in in another PR.
Fixes #1181.

internal/asm/f64: zero out ZERO even for zero-length input to L2NormInc

---

graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go
graph/simple/directed.go
graph/simple/undirected.go
graph/simple/weighted_directed.go
graph/simple/weighted_undirected.go

graph/{multi,simple}: don't return pointer values from NewEdge/NewLine

---

graph/encoding/dot/weighted_example_test.go

This adds the example (cleaned up) I recently posted to gonum-dev.

graph/encoding/dot: add example for decoding a weighted graph

---

unit/constant/atomicmass.go
unit/constant/avogadro.go
unit/constant/avogadro_test.go
unit/constant/boltzmann.go
unit/constant/boltzmann_test.go
unit/constant/electricconstant.go
unit/constant/elementarycharge.go
unit/constant/faraday.go
unit/constant/faraday_test.go
unit/constant/finestructure.go
unit/constant/generate_constants.go
unit/constant/gravitational.go
unit/constant/gravitational_test.go
unit/constant/magneticconstant.go
unit/constant/magneticconstant_test.go
unit/constant/planck.go
unit/constant/planck_test.go

Complete table of values at https://physics.nist.gov/cuu/Constants/Table/allascii.txt.
Updates #916.

unit/constant: update the values and uncertainties for 2018 CODATA

---

lapack/testlapack/dlantr.go

The current Dlantr failures in our netlib repository are caused by out-of-bounds write in the Fortran reference LAPACK when computing the inf-norm of wide lower-triangular matrices with "tight" `work`. I will submit a PR to the reference and OpenBLAS to lift this restriction (which is documented but unnecessary in my opinion and to top it off DLANTR doesn't check the input parameters) but it cannot be relied upon anyway.

lapack/testlapack: don't test unsupported matrix sizes in DlantrTest

---

stat/card/card.go
stat/card/hll32.go
stat/card/hll64.go

This matches the approach used in gob.

stat/card: use more conventional type encoding

---

blas/gonum/level1float32.go
blas/gonum/level1float64.go

This change prevents the compiler from emitting FMA instructions during Drotmg and Drotm which would otherwise cause the arm64 build to fail.
Updates #1218.

blas/gonum: make drotmg test pass

---

mathext/prng/prng_di_unimi.go

mathext/prng: use bits package for rotate left

---

lapack/testlapack/dlaexc.go
lapack/testlapack/dtrexc.go

The tests now use "bad" matrices.

testlapack: rework test for Dlaexc and clean up test for Dtrexc

---

optimize/unconstrained_test.go

This avoids arm64 failures in (L)BFGS, Cases 31 and 51. Case 32 will probably require extending the testing code, the other cases I haven't checked in detail yet.

optimize: relax gradient tolerance in two tests

---

optimize/unconstrained_test.go

Relaxing the gradient tolerance on the equivalent test case for BFGS and LBFGS does not resolve those failures (as noted in #1243).
Updates #1218.

optimize: relax gradient tolerance for Newton test

---

lapack/testlapack/dgesvd.go
lapack/testlapack/dorg2l.go
lapack/testlapack/general.go

testlapack: use residualOrthogonal helper in Dorg2lTest and DgesvdTest

---

internal/math32/sqrt_arm64.go
internal/math32/sqrt_arm64.s

math32: add arm64 assembly implementation for Sqrt

---

mat/band.go
mat/matrix_test.go
mat/symband.go

This is adding the `MulVecTo` method to two matrix types which I think that it makes most sense to support natively in `linsolve`. However, seeing the function signature in the context of `mat` it doesn't seem to fit because of the slices, so I'm wondering whether it should take `*mat.VecDense` instead. This would of course require revisiting `linsolve` and changing the implementation to be more mat-like.
Just a draft at the moment.

mat: add MulVecTo method to BandDense and SymBandDense

---

blas/gonum/dgemm.go
blas/gonum/gonum.go
blas/gonum/sgemm.go

This simplifies the code a bit and also improves the performance.
```
name                  old time/op  new time/op  delta
DgemmSmSmSm-32         820ns ± 1%   823ns ± 0%     ~     (p=0.127 n=5+5)
DgemmMedMedMed-32      137µs ± 1%   139µs ± 0%   +1.12%  (p=0.008 n=5+5)
DgemmMedLgMed-32       463µs ± 0%   450µs ± 0%   -2.88%  (p=0.008 n=5+5)
DgemmLgLgLg-32        25.0ms ± 1%  24.9ms ± 0%     ~     (p=1.000 n=5+5)
DgemmLgSmLg-32         685µs ± 1%   694µs ± 1%   +1.40%  (p=0.008 n=5+5)
DgemmLgLgSm-32         808µs ± 1%   761µs ± 0%   -5.77%  (p=0.008 n=5+5)
DgemmHgHgSm-32        71.7ms ± 0%  68.5ms ± 0%   -4.40%  (p=0.008 n=5+5)
DgemmMedMedMedTNT-32   345µs ±10%   228µs ± 1%  -33.97%  (p=0.008 n=5+5)
DgemmMedMedMedNTT-32   142µs ± 0%   149µs ± 1%   +5.05%  (p=0.008 n=5+5) …
```

blas/gonum: improve dgemmParallel performance

---

lapack/lapack.go
lapack/testlapack/dpbcon.go
lapack/testlapack/general.go

Also remove the dependence of DpbconTest on Dlansber (and Dlanger) interfaces because the netlib package doesn't provide Dlansb.

lapack: add Dpb* functions to Float64 interface

---

.travis/run.d/linux/02-check-lint.sh
.travis/script.d/check-lint.sh
.travis/script.d/deps.sh

The golangci.com linting service is [going away next month](https://medium.com/golangci/golangci-com-is-closing-d1fc1bd30e0e), so this replaces that with work done on travis. It is a little harsher since it will actually fail a build that fails a lint check, but we can adjust that if needed, and lint checks can be tuned or turned off with [`//nolint` directives](https://github.com/golangci/golangci-lint#nolint).
[Currently linting cannot be done on arm64](https://travis-ci.community/t/git-fetch-shallow-exclude-does-not-work-on-arm64-architecture/7583), so asm lint won't be checked on that arch for now.

travis: replace golangci.com service with travis-local golangci-lint

---

.travis/script.d/check-lint.sh

This fixes the issue seen [here](https://github.com/gonum/gonum/pull/1301#issuecomment-606239235). It only runs golangci-lint on pull requests, so not on a push, and allows people contributing changes from outside the gonum/gonum repo to have their code linted and not fail.

travis: use github PR number for obtaining branch

---

spatial/r2/vector.go
spatial/r2/vector_test.go
spatial/r3/vector.go
spatial/r3/vector_test.go

This CL adds the ability to compute the cosine of the opening angle between 2 vectors (in `r2` and `r3`) and to normalize a vector (ditto).

spatial/{r2,r3}: add costheta, normalize

---

mat/cholesky.go

use CopyVec per a TODO, references long-resolved issue [#167](https://github.com/gonum/gonum/issues/167)
in Cholesky.SymRankOne don't modify receiver if singular

mat: address two small TODOs

---

mathext/internal/amos/amos_fortran_test.go

amos: add bug note to failing Fortran/Go comparison tests

---

graph/flow/control_flow_test.go

This prepares for the coming default cmd/vet behaviour that disallows `string(T)` conversions where T is not `rune` (or `byte`?).

graph/flow: avoid non-rune to string conversion

---

.github/workflows/golangci-lint.yml

When golangci.com went away we lost annotation within the PR, depending on golangci-lint to find errors in the travis build log. This is an experiment to use GitHub actions to do essentially the same thing.
Currently, it makes annotations on the code changes rather than sending comments to the PR conversation (which I would prefer), but that is a feature request on the action. If we don't like this was can revert it, but I'd like to try it out for a bit; it is running the action on this PR, though nothing should be found since there are no Go changes here.

ci: make golangci-linting a github action

---

.github/workflows/golangci-lint.yml

This otherwise causes a failure because of the logic in new issues. We don't need the comments and the travis-based linting already catches things that this would.

ci: don't lint on merge into master

---

AUTHORS
CONTRIBUTORS
mat/errors.go
mat/matrix.go

This is a minor change, that fixes typos for the word 'inaccurate' in a couple of documentation-visible locations in the 'mat' package.

mat: fix typos

---

floats/floats.go
floats/floats_test.go

This change modifies Gonum to increase test coverage of package `float`. I did not reach 100% coverage because some statements seem to be unreachable. In one case (line 580 in `floats.go`) I am not sure if the value returned is correct - why not return `n-1`?

float: Improve test coverage.

---

stat/distuv/beta_test.go
stat/distuv/chisquared_test.go
stat/distuv/distribution_test.go

This change tests all distributions which are tested using `checkQuantileCDFSurvival` for Quantile rejecting arguments which are out of range.

stat/distuv: Test Quantile with out of range arguments inside the common test function

---

stat/distuv/exponential.go
stat/distuv/exponential_test.go

This changes the way the CDF is calculated for exponential distribution from
```
1 - math.Exp(-e.Rate * x)
```
to
```
- math.Expm1(-e.Rate * x)
```
giving higher accuracy for very small x.

stat/distuv: use math.Expm1 when calculating Exponential.CDF to improve accuracy for small x

---

stat/distuv/distribution_test.go
stat/distuv/gamma.go
stat/distuv/gamma_test.go
stat/distuv/pareto_test.go

- Full test coverage
- Removed redundant calculations in the small alpha version of Rand()
- Lowered the threshold for small alpha to 0.2 in accordance with https://www4.stat.ncsu.edu/~rmartin/Codes/rgamss.R
- Added the option to pass integration bounds to PDF normalisation check
- Other small fixes

stat/distuv: Provide full test coverage for Gamma distribution and small fixes

---

stat/distuv/beta_test.go
stat/distuv/chisquared_test.go
stat/distuv/distribution_test.go
stat/distuv/exponential_test.go
stat/distuv/f_test.go
stat/distuv/gamma_test.go
stat/distuv/gumbel_test.go
stat/distuv/inversegamma_test.go
stat/distuv/laplace_test.go
stat/distuv/lognormal_test.go
stat/distuv/norm_test.go
stat/distuv/pareto_test.go
stat/distuv/studentst_test.go
stat/distuv/triangle_test.go
stat/distuv/uniform_test.go
stat/distuv/weibull_test.go

stat/distuv: Add integration bounds to PDF normalisation checks and tighten tolerances where possible

---

stat/distuv/general_test.go
stat/distuv/weibull.go
stat/distuv/weibull_test.go

Modifies absEq to catch cases when one or both arguments is NaN.

stat/distuv: fix Weibull LogProb and test function absEq

---

stat/distuv/general_test.go
stat/distuv/laplace.go
stat/distuv/laplace_test.go
stat/distuv/triangle.go
stat/distuv/triangle_test.go
stat/distuv/uniform.go
stat/distuv/uniform_test.go

Also fixes a bug in Laplace ScoreInput, and tests existing ScoreInput implementations.

stat/distuv: add ScoreInput implementations for Uniform and Triangle

---

stat/distuv/beta.go
stat/distuv/beta_test.go

stat/distuv: Fix Beta.Prob and Beta.LogProb for alpha = 1 and x = 0 or beta = 1 and x = 1

---

graph/path/bellman_ford_moore.go
graph/path/bellman_ford_moore_test.go
graph/path/internal/testgraphs/shortest.go
graph/path/shortest.go

This actually does fix the issue with reporting negative cycles (within reason - Weight will still refuse to be definitive). The previous change adding the negative cycles did nothing since the test rejected them early.

graph/path: properly report negative cycles in Shortest.To

---

stat/distuv/poisson.go
stat/distuv/poisson_test.go

Also uses mathext.GammaIncReg to implement Poisson Survival.

stat/distuv: provide complete test coverage for Poisson

---

graph/path/bellman_ford_moore.go
graph/path/bellman_ford_moore_test.go
graph/path/dijkstra.go
graph/path/dijkstra_test.go
graph/path/internal/testgraphs/shortest.go
graph/path/shortest.go

graph/path: add option to retain all paths from single-source path finding routines

---

graph/path/bellman_ford_moore.go
graph/path/shortest.go

This should be the last bit of fiddling here for some time.
The first change improves the clarity of the logic in the negCost keying and the second adds a comment that I missed in the doc comment clean up before.

graph/path: improve documentation

---

.github/workflows/golangci-lint.yml

We reasonably often see linter action timeouts, so increase the timeout limit.

ci: try to avoid linter timeouts

---

mat/format.go

mat: clarify that prefix is only added after the first line

---

interp/interp.go
interp/interp_test.go

For now all code is in interp.go, but the file starts getting rather large. Should I split it?

interp: add Akima splines and generic piecewise cubic interpolators

---

interp/interp.go
interp/interp_test.go

interp: add a DerivativePredictor interface and implement it in AkimaSpline and PiecewiseCubic

---

lapack/gonum/bench_test.go
lapack/gonum/dcombssq.go
lapack/gonum/dlantb.go
lapack/gonum/lapack_test.go
lapack/lapack.go
lapack/lapack64/lapack64.go
lapack/testlapack/dcombssq.go
lapack/testlapack/dlantb.go
lapack/testlapack/dlantb_bench.go
lapack/testlapack/general.go

My intention was to use Dlantb and Dlansb in the banded Cholesky factorization that I've been preparing (for quite some time now). However, I've just noticed that LAPACKE provides neither Dlansb nor Dlantb, which means we can't add these functions to the lapack.Float64 interface and so can't use them in mat. This is utterly disappointing. On top of that, writing a randomized test for Dlantb, which is not it's re-implementation, is surprisingly not easy and is not much fun.

lapack/gonum: add Dlantb

---

lapack/lapack.go
lapack/lapack64/lapack64.go

These two routines are not provided by LAPACKE and therefore
should not be part of the Float64 interface.
Closes #1428

lapack,lapack64: remove Dlansb and Dlantb from Float64

---

graph/encoding/digraph6/digraph6.go
graph/encoding/graph6/graph6.go

graph/encoding/{digraph6,graph6}: allow packages to build on 32-bit arches

---

stat/combin/combin_test.go

stat/combin: allow Binomial tests to pass on GOARCH=386

---

stat/distuv/beta_test.go
stat/distuv/gamma.go
stat/distuv/gamma_test.go
stat/distuv/inversegamma_test.go
stat/distuv/studentst_test.go

Fixes #1453.
benchstat (from the new GammaRand benchmark):
```
name              old time/op  new time/op  delta
GammaRand/case_0  90.3ns ± 5%  91.1ns ± 3%     ~     (p=0.152 n=10+8)
GammaRand/case_1   215ns ± 4%   213ns ± 3%     ~     (p=0.238 n=10+10)
GammaRand/case_2  25.5ns ± 3%  25.7ns ± 3%     ~     (p=0.534 n=9+10)
GammaRand/case_3  72.4ns ± 4%  48.5ns ± 5%  -32.97%  (p=0.000 n=9+10)
GammaRand/case_4  72.0ns ± 6%  47.1ns ± 6%  -34.50%  (p=0.000 n=10+10)
```

stat/distuv: Improve Gamma.Rand performance in alpha >1 case

---

dsp/fourier/fourier_test.go
dsp/fourier/internal/fftpack/array_bounds_checks.go
dsp/fourier/internal/fftpack/array_no_bounds_checks.go
dsp/fourier/internal/fftpack/cfft.go
dsp/fourier/internal/fftpack/fftpack_test.go
dsp/fourier/internal/fftpack/helpers.go
dsp/fourier/internal/fftpack/rfft.go

It's not often that optimisations improve the legibility of the code, but these changes do.
I've made the changes in two steps, the first groups each of the complex operations together and the second then replaces the real/imag float64 operations into a single complex operation. I would recommend reviewing both of these commits rather than the change as a whole. There's a lot of change here, so please be on the look out for minor indexing errors.

dsp/fourier/internal/fftpack: use explicit complex arithmetic

---

stat/distuv/poisson.go
stat/distuv/poisson_test.go

benchstat:
```
name                old time/op  new time/op  delta
PoissonRand/case_0   297ns ± 5%    76ns ±10%  -74.56%  (p=0.000 n=10+10)
PoissonRand/case_1   284ns ± 6%   107ns ± 7%  -62.21%  (p=0.000 n=10+10)
PoissonRand/case_2   284ns ± 6%   118ns ± 4%  -58.34%  (p=0.000 n=10+10)
PoissonRand/case_3   236ns ± 3%   239ns ± 6%     ~     (p=0.381 n=10+10)
PoissonRand/case_4   105ns ± 6%   107ns ± 8%     ~     (p=0.236 n=10+10)
PoissonRand/case_5  73.8ns ± 4%  75.1ns ± 4%     ~     (p=0.148 n=10+10)
PoissonRand/case_6  60.3ns ± 5%  60.9ns ± 5%     ~     (p=0.307 n=10+10)
```

stat/distuv: improve Poisson.Rand performance for Lambda >= 10

---

mat/symmetric.go
mat/symmetric_test.go
stat/statmat_test.go

Also fix CovarianceMatrix benchmarks in stat that found this.

mat: fix GrowSym behaviour for Reset matrices

---

dsp/fourier/fourier_test.go
dsp/fourier/radix24.go
dsp/fourier/radix24_test.go

The comments in #1456 about FFT packages was what spurred me to look at cleaning up dsp/internal/fftpack, but I also spent some time thinking about my comment https://github.com/gonum/gonum/pull/1456#issuecomment-693677437 regarding the desire to have a non-radix constrained implementation. I still think this is true since it makes life easier for the general user, but it doesn't preclude us from providing radix-2 and radix-4 FFTs.
These are faster than the current implementation (even with the improvements made in #1463), and they don't allocate, but they do behave the same way as the `Coefficients` and `Sequence` methods on the FFT types we have which the exception that they are less numerically precise (this comes from the approach used to generate the twiddle factors by successive …

dsp/fourier: add radix-2 and radix-4 in-place FFTs

---

mat/dense_test.go
mat/list_test.go
mat/matrix_test.go
mat/mul_test.go
mat/triband.go
mat/triband_test.go

I also cleaned up the `basicVector` type a bit so that the tests for `SolveTo` and `SolveVecTo` are basically identical.
Closes #1471 
cc @romanwerpachowski

mat: add TriBandDense.SolveTo and SolveVecTo

---

graph/community/louvain_common.go
graph/community/louvain_directed.go
graph/community/louvain_directed_multiplex.go
graph/community/louvain_undirected.go
graph/community/louvain_undirected_multiplex.go

Added modularityEpsilon constant and using it in all "localMovingHeuristic" implementations.
Addresses issue https://github.com/gonum/gonum/issues/1488

graph/community: add threshold for modularity gain

---

stat/distuv/exponential_test.go

stat/distuv: don't use global rand state for test

---

lapack/gonum/dlangt.go
lapack/gonum/errors.go
lapack/gonum/lapack_test.go
lapack/lapack64/lapack64.go
lapack/testlapack/dlangt.go
lapack/testlapack/dlantb.go

A first step towards adding a solver for tridiagonal matrices.
cc @romanwerpachowski

lapack: add Dlangt

---

lapack/gonum/dlagtm.go
lapack/gonum/lapack_test.go
lapack/lapack64/lapack64.go
lapack/testlapack/dlagtm.go

This is just a draft for now because:
* `Dlagtm` takes a `trans` parameter but with the tridiagonal matrices the caller can easily handle tranposes by swapping the arguments for `dl` and `du`. This is actually what the solve/factorization calls like `Dgtsv` et al. do, they don't take a `trans` parameter. Since Lapacke doesn't wrap this call anyway, we have more freedom of departing from the Lapack interface for tridiagonal matrices (which feels like it didn't receive much attention anyway) and remove the parameter here.
* Lapack's `DLAGTM` assumes that `alpha` and `beta` are in `{-1,0,1}` but I don't see a reason to not support any values. This would be another deviation from the reference Lapack. I think we should do it but would like to check first.

lapack: add Dlagtm

---

mat/matrix.go

The Frobenius norm is not induced but the docs suggested it is.

mat: remove mention of "induced" from mat.Norm docs

---

.github/workflows/golangci-lint.yml
graph/encoding/dot/decode.go
graph/encoding/dot/decode_test.go

This is a counter proposal for #1503 
Closes #1503

graph/encoding/dot: don't propagate edge setting panics when unmarshaling DOT

---

dsp/fourier/radix24_test.go
stat/samplemv/halton.go

The Halton fix is pretty hacky, but I've spent a fair bit of time looking through the Halton code and the R original and I'm not completely happy with my understanding of the relationship between the two (input from @btracey would be helpful here). I also think that the behaviour of the R code depends on R's sloppy behaviour in implicitly converting between `double` and `integer` types and allowing the use of `double` values to index into arrays.
Updates #1444

dsp/fourier,stat/samplemv: fix 32 bit architecture bugs

---

cmplxs/cmplxs_test.go
floats/floats_test.go
internal/asm/c128/asm_test.go
internal/asm/c128/l2norm_test.go
internal/asm/c64/asm_test.go
internal/asm/c64/l2norm_test.go

Random constant used in internal/asm taken from published value.
Closes #1299.

cmplxs,floats,internal/asm: don't use global rand state

---

spatial/r2/vector_test.go
spatial/r3/vector_test.go

as discussed in https://github.com/gonum/gonum/pull/1516#discussion_r532921011.

spatial/{r2,r3}: drop use of subtests

---

.codecov.yml

The reports can't link to the source code because that have `src/gonum.org/v1/gonum/` prefix. This should fix that.

codecov: make coverage report relative to root of the repo

---

graph/multi/directed.go
graph/multi/directed_test.go
graph/multi/undirected.go
graph/multi/undirected_test.go
graph/multi/weighted_directed.go
graph/multi/weighted_directed_test.go
graph/multi/weighted_undirected.go
graph/multi/weighted_undirected_test.go
graph/simple/densegraph_test.go
graph/simple/directed_test.go
graph/simple/undirected_test.go
graph/simple/weighted_directed_test.go
graph/simple/weighted_undirected_test.go
graph/testgraph/testgraph.go

See https://github.com/gonum/gonum/pull/1519#discussion_r533874263 for context behind optional relaxation of edge reversal.
See https://github.com/gonum/gonum/issues/1517 for the background behind line ID allocation.

graph/{multi,simple,testgraph}: fix edge reversal tests and multi.WeightUndirected

---

.github/workflows/codecov.yml

We have been missing base reports since the migration from travis since GitHub Actions (per default) don't run on merge. This and the rebase/squash merge policy that we use means that the reports that have been uploaded to Codecov are never relevant to future reports since they are always off the master branch. This does a run of coverage only when a PR is closed and the closure was a merge. It only does this for the tags and only for ubuntu, but the infrastructure for extension is left in in case we want to extend to macOS later.
No change will be visible in the pre-merge stage of this PR (unfortunately).

ci: add action for uploading coverage report on PR merge

---

.github/workflows/codecov.yml

This is another leap into the darkness.

ci: lie to codecov action about the origin of the report

---

.github/workflows/codecov.yml

Hopefully this is going to work. Again, we won't know until it's merged.
The [new API](https://github.com/codecov/codecov-action#arguments) was added at least in part to address the issue we have been having, so thanks to Codecov for that.

ci: use new codecov action API to fix coverage report issues

---

.github/workflows/codecov.yml

The released action is now v1.2.0, so v1, should be enough to specify the correct version.

ci: back up on version specification

---

graph/path/bellman_ford_moore.go
graph/path/bellman_ford_moore_test.go
graph/path/bench_test.go

This completes something that I had intended to do a couple of years ago (#486), but thought wasn't efficiently feasible. It is.
This makes time limited Bellman-Ford searches a possibility (this is used for example in routing decisions where there is a limited amount of time allocated to finding the best route).
\<thinks\>Maybe A* is possible\</thinks\>

graph/path: allow incremental Bellman-Ford search

---

mat/dense_arithmetic.go

mat: only use workspace for element-wise operation when transposed

---

graph/layout/eades.go
spatial/barneshut/barneshut2.go
spatial/barneshut/barneshut2_test.go
spatial/r2/deprecated.go
spatial/r2/vector.go
spatial/r2/vector_test.go
spatial/r3/deprecated.go
spatial/r3/vector.go
spatial/r3/vector_test.go

Migration to the new API can be achieved with this rsc.io/rf script:
```
rf ex {
import "gonum.org/v1/gonum/spatial/r3";
var p,q r3.Vec;
var f float64;
p.Add(q) -> r3.Add(p, q);
p.Sub(q) -> r3.Sub(p, q);
p.Scale(f) -> r3.Scale(f, p);
p.Dot(q) -> r3.Dot(p, q);
p.Cross(q) -> r3.Cross(p, q);
p.Rotate(f, q) -> r3.Rotate(p, f, q);
}
```
and, similarly, for `r2`:
```
rf ex {
import "gonum.org/v1/gonum/spatial/r2";
var p,q r2.Vec;
var f float64;
p.Add(q) -> r2.Add(p, q);
p.Sub(q) -> r2.Sub(p, q);
p.Scale(f) -> r2.Scale(f, p);
p.Dot(q) -> r2.Dot(p, q);
p.Cross(q) -> r2.Cross(p, q);
p.Rotate(f, q) -> r2.Rotate(p, f, q);
}
```
Fixes gonum/gonum#1553.

spatial/r3: harmonize Vec API with num/quat.Number

---

.travis.yml

Travis have been entirely non-responsive to support requests to follow up on their promise to provide us with either hold-over credits to allow tests to continue or provide OSS plans. If they do eventually get around to it the cost of testing is pretty high (we burned through 10,000 in a few weeks), so this change is to direct what they give us where it will be most useful, arm64 which is not currently supported by GitHub actions.
After this is merged (based on faith rather than testing), I'll reorganise the files in .travis/ so that it's more obvious that they are shared with other CI service configurations.

travis: remove all non-arm64 targets

---

lapack/gonum/doc.go

lapack/gonum: fix link to gonum/mat in package doc

---

stat/roc.go
stat/roc_example_test.go
stat/roc_test.go

The main change is when cutoffs is not nil, returned thresholds are now cutoffs (sorted in decreasing order), and the fpr and tpr values are such that they are correct for these thresholds. 
This: 
- maintains the parity convention decision made in #316 and documented in the ROC description.
- is (I believe) closer to the original intent of #708
- should resolve #1557 and #1559 (although changes the expected output)
- includes extra test case from #1557 as per #1558

stat: ROC revert functionality when cutoffs is not nil, code readability improvements, and bug fixes

---

lapack/gonum/ilaenv.go

An unimportant changed done in the reference in https://github.com/Reference-LAPACK/lapack/pull/498

lapack/gonum: clarify Ilaenv doc comment

---

graph/graph.go
graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go
graph/simple/directed.go
graph/simple/undirected.go
graph/simple/weighted_directed.go
graph/simple/weighted_undirected.go
graph/testgraph/testgraph.go

I'm not sure about the placement of the `NodeWithIDer` interface. Given that we need to have it in testgraph, I'm thinking that maybe it *should* just go in graph.
Updates #1582.
/cc @mattConn

graph/{multi,simple,testgraph}: add support for ID-specified node addition

---

internal/asm/f64/stubs_test.go
internal/asm/f64/sum_amd64.s

The code was jumping to end when tail == 0, but the correct thing is to jump when `LEN` is zero. `TAIL == 0` means we can start the summing pipeline. We also don't need to decrement the TAIL since we overwrite it at start of `no_trim`
This was not caught by the tests (they pass before and now). I am curious if anyone has an idea for a test case that would catch this.
I've also made the register names consistent.

 internal/asm/f64: fix bug and clean up variable names

---

internal/asm/f32/stubs_amd64.go
internal/asm/f32/stubs_noasm.go
internal/asm/f32/stubs_test.go
internal/asm/f32/sum_amd64.s

Tests pass, implementation based on https://github.com/gonum/gonum/blob/master/internal/asm/f64/sum_amd64.s (including taking over the respective tests).
I know `f32` isn't really exposed, but I hope that in the future maybe it will be. At the moment I simply copy it over ("vendor") and noticed this functionality was missing.

 internal/asm/f32: add assembly Sum implementation

---

graph/traverse/traverse.go
graph/traverse/traverse_test.go

The Batagelj-Zaversnik graph traversal from 13 is removed due to the number of potential valid orderings.
Fixes #1595.

graph/traverse: fix depth first traversal order and tighten tests

---

mat/band.go
mat/basictypes_test.go
mat/index_bound_checks.go
mat/index_no_bound_checks.go
mat/matrix.go
mat/matrix_test.go
mat/tridiag.go
mat/tridiag_test.go

After a short hiatus I'm trying to pick up my effort to support tridiagonal matrices in `mat`. At the moment this is just a draft because there are not tests yet but please take a look and leave comments.

mat: add support for tridiagonal matrices

---

lapack/gonum/dtgsja.go

I don't have a failing test case for this change but it was done in the reference in https://github.com/Reference-LAPACK/lapack/pull/502 and looks like a safe change to make. The PR references a test case for CGGSVD3 which does trigger a failure but it looks like a deficiency of our test (too strict by not taking into account the norm of the input matrices).

lapack/gonum: check for overflow in Dtgsja

---

stat/roc.go

This formula is simpler, has the ntp[0] included in the series and has the additional advantage of being correct.

stat: fix TOC formula in documentation

---

.github/workflows/codecov.yml

This is to investigate the recent failure to upload coverage reports (failure starts after March 23) after merging into master as the master branch. This is required due to the model codecov uses to calculate coverage changes.
The change here was suggested by codecov support as an experiment.
It will make no difference to the outcome of the PR coverage, but may make a difference to the merged coverage report and so we won't know until this is merged.

codecov: change override branch to master

---

graph/iterator/nodes.go
graph/iterator/nodes_test.go

graph/iterator: fix Len for depleted ImplicitNodesIterator

---

graph/graphs/gen/gen.go
graph/graphs/gen/gen_example_test.go
graph/graphs/gen/gen_test.go

This incurs a greater cost for well-behaved code, but prevents subtle errors that would otherwise not be caught, for example  cycle(1,2,3,4,5,3) not being a single cycle.
Closes #1614.

graph/graphs/gen: check for all node id collisions

---

lapack/gonum/dlangb.go
lapack/gonum/errors.go
lapack/gonum/lapack_test.go
lapack/lapack64/lapack64.go
lapack/testlapack/dlangb.go

Preparation for adding `mat.Normer` and using it in `mat.Norm` similarly to `mat.Trace`.

lapack/{gonum,testlapack}: add Dlangb and its test

---

graph/encoding/digraph6/digraph6.go
graph/encoding/digraph6/digraph6_test.go
graph/encoding/graph6/graph6.go
graph/encoding/graph6/graph6_test.go

graph/encoding/{,di}graph6: fix bit handling for graph size encoding

---

.github/workflows/codecov.yml

This is to investigate the recent failure to upload coverage reports after
merging into master as the master branch. This is required due to the model
codecov uses to calculate coverage changes.
The change here was suggested by codecov support as an experiment.
Please approve.

codecov: remove override_pr

---

lapack/gonum/bench_test.go
lapack/testlapack/dlangb_bench.go

Comparison between Dlangb implemented with work slice and without work slice:
```
» benchstat dlangb-bench-with-work.txt dlangb-bench-without-work.txt 
name                              old time/op  new time/op   delta
Dlangb/MaxColSum_N=1000_K=0-4     5.57µs ± 5%   9.80µs ± 1%  +75.91%  (p=0.008 n=5+5)
Dlangb/MaxColSum_N=1000_K=1-4     8.08µs ± 0%  13.15µs ± 2%  +62.71%  (p=0.008 n=5+5)
Dlangb/MaxColSum_N=1000_K=2-4     10.4µs ± 0%   16.3µs ± 0%  +56.56%  (p=0.029 n=4+4)
Dlangb/MaxColSum_N=1000_K=30-4    71.6µs ± 0%   44.4µs ± 2%  -37.95%  (p=0.016 n=4+5)
Dlangb/MaxColSum_N=10000_K=0-4    48.5µs ± 3%   79.8µs ± 0%  +64.74%  (p=0.008 n=5+5)
Dlangb/MaxColSum_N=10000_K=1-4    71.5µs ± 3%  117.3µs ± 2%  +64.17%  (p=0.008 n=5+5)
Dlangb/MaxColSum_N=10000_K=2-4    92.8µs ± 0%  153.3µs ± 0% …
```

lapack/testlapack: add benchmark for Dlangb

---

mat/eigen.go

Document that `EigenSym.Values` gives eigenvalues in ascending order.
Closes #461 

mat: clarify docs for EigenSym.Values

---

lapack/testlapack/dgeev.go
lapack/testlapack/dgesvd.go
lapack/testlapack/dlangb_bench.go
lapack/testlapack/dlartg.go
lapack/testlapack/dlassq.go
lapack/testlapack/dlatbs.go
lapack/testlapack/dlatrs.go
lapack/testlapack/general.go
lapack/testlapack/matgen.go

I prefer the more descriptive names than the `dlamch*` names and I think it's useful to have them at package level instead of scattered around in functions.

testlapack: consolidate floating-point constants

---

graph/graphs/gen/gen.go
graph/graphs/gen/gen_example_test.go
graph/graphs/gen/gen_test.go

This adds a tree constructor per #1582. I made the decision to have the tree build breadth-first based on a specified uniform fanout, and allowed for it to be partially full, as in missing leaves. My method for calculating depth based on number of nodes required the use of a logarithm and so `math` is imported.

graph/graphs/gen: Added breadth-first tree constructor

---

graph/encoding/dot/decode_test.go
graph/encoding/dot/encode_test.go
graph/encoding/encoding.go
graph/encoding/encoding_test.go

This makes node and edge attribute handling much easier for users, in most cases making it possible to just embed an `encoding.Attributes` in the type. For graphs it's a little more involved, for example for dot, an extra method is needed, but it is still simpler than the current situation.

graph/encoding: provide attribute handling out of the box

---

lapack/gonum/dlasy2.go

Please take a look at the line I changed. The following operation:
```go
scale = 1 / 8 / maxbtmp
```
always yields zero. I added decimal points to `1` and `8` to fix this undesired behavior.

lapack/gonum: prevent division of untyped ints always yielding zero in Dlasy2

---

lapack/gonum/dormbr.go

lapack/gonum: don't multiply by 1

---

lapack/testlapack/dgesc2.go

lapack/testlapack: fix typo in test for Dgesc2

---

spatial/r3/vector.go
spatial/r3/vector_test.go

I have not added the matrix→quat function as this requires more thought in terms of what we should accept and is arguably less valuable; the quat→mat operation means that large sets of points can be operated on with a single matrix multiply while it's not entirely clear what you get from being able to convert a mat to a quat, and the code is more complex.

spatial/r3: add method to obtain a rotation matrix

---

lapack/gonum/dgesv.go
lapack/gonum/lapack_test.go
lapack/testlapack/dgesv.go

More for completeness than utility because Dgesv doesn't have a trans parameter to solve `A^T*X = B`.

lapack/gonum: add Dgesv

---

spatial/r3/vector.go

I'm not completely convinced that this is worth doing yet, but it is here.

spatial/r3: use lightweight matrix for rotations

---

spatial/r3/euler_example_test.go

spatial/r3: add example for why not to use Euler angles

---

graph/iterator/lines_map.go
graph/iterator/lines_map_safe.go
graph/iterator/lines_test.go
graph/iterator/map.go
graph/iterator/nodes_map.go
graph/iterator/nodes_map_safe.go
graph/multi/directed.go
graph/multi/undirected.go
graph/multi/weighted_directed.go
graph/multi/weighted_undirected.go

graph/{iterator,multi}: use map iterators for lines and weighted lines

---

graph/flow/control_flow_bench_test.go
graph/formats/cytoscapejs/cytoscapejs_test.go
graph/formats/dot/ast/ast_test.go
graph/formats/dot/dot.go
graph/formats/dot/internal/astx/astx_test.go
graph/formats/dot/internal/lexer/lexer_test.go
graph/formats/dot/internal/parser/parser_test.go
graph/formats/dot/internal/paste_copyright.go
graph/formats/gexf12/gexf_test.go
graph/formats/rdf/urna_test.go
graph/formats/sigmajs/sigmajs_test.go
graph/layout/layout_test.go
mat/io_test.go
unit/constant/generate_defined_types.go

This is ready to apply when Go1.15 is no longer supported.

all: replace uses of deprecated ioutil functions

---

.github/workflows/ci.yml
README.md

The link looks like an off-by-one, but is not; it points to the line "Versions of Go that..." and the version list.

README: fix link to supported versions

---

stat/distuv/pareto.go
stat/distuv/pareto_test.go

Just removes an unnecessary math.Log call.
benchstat:
```
name        old time/op  new time/op  delta
ParetoRand  38.0ns ± 8%  24.4ns ± 2%  -35.72%  (p=0.000 n=9+10)
```

stat/distuv: improve Pareto.Rand performance, also adding Pareto.Rand benchmark

---

.github/workflows/ci.yml
.github/workflows/codecov.yml

The path is a multiline string, which includes comments in its value. This
means that the caching was not working at all, because it would include
the comment in the path. Here I'm moving the comments, which fixes the
caching so it works.

ci: make cache works by removing comments

---

lapack/gonum/dlag2.go
lapack/gonum/lapack_test.go
lapack/testlapack/dlag2.go

Please take a look. Process of solving #1651.
Dlag2 solves a 2x2 eigenvalue problem of the form `|A-xB| = 0` where `B` is upper triangular.

lapack: add Dlag2 subroutine

---

graph/formats/rdf/equi_canonical.go
graph/formats/rdf/equi_canonical_example_test.go
graph/formats/rdf/equi_canonical_test.go
graph/formats/rdf/rdf.go

This implementation does not have any of the optimisations mentioned in the paper beyond those required for ergonomics in Go. I intend to add these in a later PR. This intention is the reason for having the methods on the `dfs` pointer type.
/cc and thanks @aidhog

graph/formats/rdf: add equi-canonicalisation function

---

lapack/gonum/dlaswp.go

Also, simplify checks of row indices k1 and k2.

lapack/gonum: fix length check in Dlaswp

---

lapack/gonum/dtrexc.go
lapack/testlapack/dtrexc.go

Please take a look. See https://github.com/dgryski/semgrep-go.
I did not apply many of the other `Odd comparison` semgrep go suggestions because they seemed to detract from readability. Worth looking into some of the `MarshalJSON` suggestions though:
<details><summary>semgrep-go output</summary>
```
/gonum$ semgrep -f ~/src/misc/semgrep-go/ .
Running 45 rules...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|45/45
blas/gonum/level2cmplx128.go
severity:error rule:home.pato.src.misc.semgrep-go.odd-comparison: Odd comparison
2070:					if n-i-1 > 0 {
--------------------------------------------------------------------------------
2081:					if …
```

lapack/{gonum,testlapack}: apply semgrep-go suggestions

---

spatial/r3/mat.go
spatial/r3/mat_test.go

Please take a look. Resolves  #1754.
Sidenote: if we switched `Mat`s data field to `data[3*3]` `RawMatrix` could be implemented more easily if that were of interest.

spatial/r3: add Mat type

---

spatial/r3/mat.go
spatial/r3/mat_safe.go
spatial/r3/mat_test.go
spatial/r3/mat_unsafe.go

Ideally there should be some more testing here, but only the trivial things are now not tested.
At some point we may also want to have det and inverse added.

spatial/r3: provide safe option for Mat operations

---

graph/coloring/coloring.go

This is a replay of #1705, now onto the merged coloring package. I had originally intended to wait until I had improved the base performance of the `DsaturExact` implementation before I applied this change, but I suspect that I won't have time to address that for a while (my initial investigations suggest that it's both subtle and extensive to improve the way that the color accounting is currently done), so rather than wait with a poorly performing exact coloring implementation I think this should go in, and the work to formally examine the impact of this change can happen after the base improvements are made with minor alterations of code added here.
The algorithmic addition is quite straightforward and I think the implications on run time are reasonably clear. I have some rough notes …

graph/coloring: allow warm start for DsaturExact

---

spatial/r3/mat.go
spatial/r3/mat_safe.go
spatial/r3/mat_test.go
spatial/r3/mat_unsafe.go
spatial/r3/rotation.go
spatial/r3/vector.go
spatial/r3/vector_test.go

Mainly colour and movement. The `Matrix` method is deleted as extraneous, and it never got into a release, so it's not breaking; everything else otherwise just works the same way that it did and the new tests in #1774 are hooked into the old code.

spatial/r3: remove duplicated API

---

graph/formats/rdf/graph_example_test.go
graph/formats/rdf/query.go
graph/formats/rdf/query_test.go

graph/formats/rdf: add Has{All,Any}{Out,In} and Repeat query methods

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/golangci-lint.yml
appveyor.yml
go.mod
spatial/r3/mat_safe.go
spatial/r3/mat_unsafe.go

This is the only Go version dependent change that needs to be made prior to the next release. Sadly, the unsafe conversion needs to remain in the unsafe path, otherwise we could have collapsed it back to a single file.

spatial/r3: use array conversion in safe code

---

.github/workflows/ci.yml
.github/workflows/script.d/deps.sh

This will be v0.11.0 when it is merged, with the release text posted at [gonum-dev](https://groups.google.com/g/gonum-dev/c/hdYiSkcH9Q8/m/H9p1Y1sjAgAJ); make suggestions for change to that text at gonum-dev.

ci: add go1.18 go version

---

num/quat/exp.go
num/quat/exp_test.go

This brings the quat package into line with the others in num, which already have `PowReal`. See https://github.com/gonum/gonum/pull/1805#discussion_r878771435 for motivation.

num/quat: add PowReal function

---

spatial/r3/mat.go
spatial/r3/mat_safe.go
spatial/r3/mat_test.go
spatial/r3/mat_unsafe.go

I understand this has not been talked about, but it's clearly bad API design in my eyes. What do y'all think?
Changes:
* deprecate Skew package level function in favor of method to prevent heap allocations

spatial/r3: Skew is now method

---

graph/graph_test.go
graph/layout/eades_test.go
graph/layout/isomap_test.go
graph/nodes_edges_test.go
stat/samplemv/sample_test.go
unit/unit_test.go

Tests run repeatedly do not reinitialise state, meaning that a second run
of the tests will have leftover state from the previous run. This ensures
that repeated runs are identical with the exception of map iteration order.
Review recommendation is to ignore whitespace.
Fixes #1824

all: make tests pass when -count is greater than 1

---

spatial/r3/mat_safe.go
spatial/r3/mat_unsafe.go

spatial/r3: fix deprecation syntax so it is recognised by pkgsite

---

stat/combin/combin.go

The four functions explained by the modified comments panic if n or k of parameters are "negative", not "non-negative".
I'm not good at writing in English. If the commit messages is strange, please tell me that.

stat/combin: fix typos

---

mat/solve.go

It seems the extra `A` here is unintended.

mat: fixed typo in mat.Solve/mat.SolveVec

---

graph/path/yen_ksp.go
graph/path/yen_ksp_test.go

Previously the code was not removing nodes on the root of the search path, resulting in searches that could re-enter previously searched nodes. In addition to this, the logic for making edges was incorrectly making both directions for digraphs and only one direction for undirected graphs.
Finally, the range of nodes to include in the spur-node set was off-by-one. This is now clarified by including the comment from the wiki article since the pseudo-code is less clear than the English due to choice of range indexing convention.
Fixes #1778

graph/path: fix yen k-shortest path with root cycles

---

graph/encoding/graphql/decode.go

The spanning tree walk sets nodes' IDs using the SetIDFromString method so note that nodes returned by the destination's NewNode method must satisfy StringIDSetter.

graph/encoding/graphql: note requirement of dst parameter

---

AUTHORS
CONTRIBUTING.md
CONTRIBUTORS
README.md
blas/README.md
cmplxs/README.md
diff/README.md
floats/README.md
graph/README.md
integrate/README.md
internal/README.md
interp/README.md
lapack/README.md
lapack/gonum/doc.go
mat/README.md
mathext/README.md
optimize/README.md
stat/README.md

This pull request does the following:
- replace all godoc.org README badges godocs.io ones
- replace remaining (non-badge) godoc.org links with pkg.go.dev ones
- fix a link to the `blas64` docs in the `doc.go` of `lapack/gonum`, that had "golang.org" instead of "gonum.org" in the package path
- add pkg.go.dev reference README badges to all packages that have the godocs.io ones
What caught my eye initially was that the main README had two seemingly identical "go reference" badges. It turned out that one of them was the legacy godoc.org reference which has been redirecting to pkg.go.dev since early 2021 (see https://github.com/golang/go/issues/43178)

all: replace godoc.org with pkg.go.dev in badges and links

---

stat/sampleuv/weighted.go
stat/sampleuv/weighted_test.go

Take is divided into 2 steps index search and after that Reweight with 0.
1. I added checks for heap over bounds during tree traversal.
2. I removed last and left because in each iteration of the loop we always make a move to either the left or right subtree and this branch never reached.
3. Instead of two implementations of reweight in the `Take` and `Reweight` functions, I left only one.
4. Instead of calling reset - O(n) when you check a negative weight, I do a weight calculation as in reset, but through sift up only the desired nodes for O(log(n)). It also removed the `scalar.EqualWithinAbsOrRel` check, since we are now summing up zeros instead of accumulating a float error.
https://github.com/gonum/gonum/issues/1866

Fix Weighted panic

---

graph/path/yen_ksp.go
graph/path/yen_ksp_test.go

This adds an additional constraint onto YenKShortestPaths to consider the paths' cost as well as the number of paths, enabling search within a constrained distance.
This is a breaking change.

graph/path: allow cost-based Yen shortest path calculation

---

lapack/gonum/dlassq.go

A small change that makes our implementation identical with the Reference. It avoids using the result of squaring a square root which could lead to a loss of precision.

lapack/gonum: avoid using square of sqrt in Dlassq

---

lapack/gonum/bench_test.go
lapack/gonum/dhseqr.go
lapack/gonum/dlaqr04.go
lapack/gonum/dlaqr5.go
lapack/testlapack/dlaqr5.go
lapack/testlapack/dlaqr5_bench.go

...and update workspace sizes in Dhseqr and Dlaqr04.
See https://github.com/Reference-LAPACK/lapack/pull/480 for the same change in the Reference.
This is another item from my unattended backlog accumulated over the past couple of years. The diff here is useless, it's practically a rewrite. The test coverage of Dlaqr5 is almost complete, which gives me some confidence the indices are correct. The result is a quite nice runtime improvement for non-tiny matrices:
```
goos: linux
goarch: amd64
pkg: gonum.org/v1/gonum/lapack/gonum
cpu: 12th Gen Intel(R) Core(TM) i7-12800H
│    old.txt    │               new.txt               │
│    sec/op     │    sec/op     vs base               │
Dgeev/AntisymRandom3-20           2.187µ ± ∞ ¹   2.219µ ± ∞ ¹        ~ (p=0.421 n=5)
Dgeev/AntisymRandom4-20 …
```

lapack/gonum: implement optimal packing in Dlaqr5 

---

lapack/testlapack/dlapy2.go

This is done to avoid test failure in the netlib repo on remote build infrastructure.

lapack/testlapack: relax tolerance in Dlapy2 test

---

unit/constant/generate_defined_types.go

Maybe it's not worth an issue.

unit/constant: use log.Fatalf when there are verbs

---

AUTHORS
CONTRIBUTORS
unit/doc.go

Fixed a grammatical from "a run time" to "at run time"

Fixed a grammatical error in Unit docs

---

blas/blas64/blas64.go
lapack/gonum/dgghrd.go
lapack/gonum/errors.go
lapack/gonum/lapack_test.go
lapack/lapack.go
lapack/testlapack/dgghrd.go
lapack/testlapack/general.go

Part of #1651. Test not added since it is not readily apparent to me how to go about testing these functions. My background is not in linear algebra. 
- Added `Dgghrd` with following signature:
```go
func (Implementation) Dgghrd(compq, compz lapack.OrthoComp, n, ilo, ihi int, a []float64, lda int, b []float64, ldb int, q []float64, ldq int, z []float64, ldz int)
```
- Added `lapack.OrthoComp` type and `badOrthoComp` panic string.

lapack: add `Dgghrd`

---

AUTHORS
CONTRIBUTORS
graph/formats/gexf12/gexf.go
graph/graphs/gen/gen.go
graph/internal/set/set.go
graph/iterator/lines.go
graph/iterator/nodes.go
graph/nodes_edges.go
graph/path/internal/testgraphs/limited.go
graph/simple/simple.go
graph/topo/johnson_cycles.go

According to [Comment Sentences at github.com/golang](https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences), it is a convention to begin a comment with the name of the exported element.

graph: fix comment of exported elements

---

mat/lu.go
mat/lu_test.go

mat: add LU.RowPivots and deprecate LU.Pivot

---

lapack/lapack.go
lapack/lapack64/lapack64.go
mat/qr.go
mat/qr_test.go

Making QR satisfy Matrix is more difficult compared to the other factorization types because the matrix Q is represented only implicitly and recovering it is expensive. I opted for computing it explicitly together with the factorization at the expense of memory.
I also switched from Dormqr (prepare the identity matrix and multiply Q into it) to Dorgqr which exists for exactly this purpose.
Updates #926

mat: make QR satisfy Matrix

---

mat/cholesky.go

Just a minor cleanup change to make the Matrix methods of the various Cholesky types behave as the other "normal" matrix types do: return 0,0 when Dims is called on a zero value and panic with the same error in case of At. 
I'll do QR next.

mat: don't panic in Dims on zero Cholesky types

---

mat/vector.go
mat/vector_test.go

I'm wondering whether it wouldn't be more `mat`-like to have signatures
```
// v = P*x or v = P^T*x
func (v *VecDense) Permute(p []int, trans bool, x Vector)
// M = P*A or M = P^T*A
func (m *Dense) PermuteRows(p []int, trans bool, a Matrix)
// M = A*P or M = A*P^T
func (m *Dense) PermuteCols(a Matrix, p []int, trans bool)
```
It complicates the implementation (special-casing on the type of A and whether it's transposed; do we care about orientation of x?) and I'm not sure if the greater flexibility is a benefit for the user. What do you think?

mat: add VecDense.Permute

---

graph/path/yen_ksp.go
graph/path/yen_ksp_test.go

Fixes #1920.
Previously the code is not ignoring spur path that has already been added into the list of potential paths. This can cause the search to return duplicate paths for certain graphs.
/cc @kortschak @vladimir-ch This is an urgent bug fix.
--- 
`YenKShortestPaths` was implemented in PR https://github.com/gonum/gonum/pull/565 and merged on 22 August 2018. On 13 February 2020, the Wikipedia page for Yen's algorithm was updated [^1] to include the conditional to check if the spur path has already been added into the potential paths.
[^1]: https://en.wikipedia.org/w/index.php?title=Yen%27s_algorithm&diff=prev&oldid=940584176

graph/path: do not keep duplicate paths in YenKShortestPaths

---

internal/asm/f32/bench_test.go
internal/asm/f64/benchAxpy_test.go

f64 contains larger benchmarks than f32 and other packages. Make the test data large enough to pass benchmarks.

internal/asm/*: use correct test len

---

.github/workflows/staticcheck.yml
go.mod

This PR is a prerequisite for a few others I intend to raise that will better prepare `graph` and other packages for generics and other modernization, as described in https://github.com/gonum/gonum/issues/617.

ci: update to go1.21

---

spatial/curve/doc.go
spatial/curve/hilbert.go
spatial/curve/hilbert_test.go

See #1695 - this is the same code with minor modifications as per comments on the original PR.
<details><summary>Benchmarks</summary><pre>
Running tool: /usr/local/go/bin/go test -benchmem -run=^$ -bench ^BenchmarkHilbert$ gonum.org/v1/gonum/spatial/curve -v -count=1
goos: darwin
goarch: amd64
pkg: gonum.org/v1/gonum/spatial/curve
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
BenchmarkHilbert
BenchmarkHilbert/2D/Pos
BenchmarkHilbert/2D/Pos/Order_1
BenchmarkHilbert/2D/Pos/Order_1-8       100000000                11.84 ns/op            0 B/op           0 allocs/op
BenchmarkHilbert/2D/Pos/Order_2
BenchmarkHilbert/2D/Pos/Order_2-8       76892733         16.06 ns/op            0 B/op           0 allocs/op
BenchmarkHilbert/2D/Pos/Order_3
BenchmarkHilbert/2D/Pos/Order_3-8       55760536 …

spatial/curve: Hilbert curves, take 2

---

graph/internal/ordered/sort.go
graph/topo/bron_kerbosch_test.go
graph/topo/tarjan_test.go
graph/topo/topo_test.go
graph/traverse/traverse_test.go

graph: replace ordered.Int64s with slices.Sort

---

blas/blas32/conv.go
blas/blas64/conv.go
blas/cblas128/conv.go
blas/cblas64/conv.go
blas/gonum/gonum.go
blas/testblas/common.go
graph/formats/rdf/iso_canonical.go
graph/topo/tarjan.go
lapack/gonum/lapack.go
lapack/lapack64/lapack64.go
lapack/testlapack/general.go
mat/matrix.go
mathext/internal/amos/amos.go
mathext/internal/amos/origcode_test.go
optimize/minimize.go
spatial/kdtree/medians.go
stat/card/card.go
stat/pca_cca.go
stat/samplemv/samplemv.go
stat/sampleuv/sample.go

Closes https://github.com/gonum/gonum/issues/1904.
We support minimum Go 1.21 since v0.15.0 (https://github.com/gonum/gonum/pull/1935).

all: replace min/max helpers with min/max builtins

---

graph/coloring/coloring.go
graph/coloring/coloring_test.go
graph/community/louvain_common.go
graph/community/louvain_directed.go
graph/community/louvain_directed_multiplex.go
graph/community/louvain_directed_multiplex_test.go
graph/community/louvain_undirected.go
graph/community/louvain_undirected_multiplex.go
graph/community/louvain_undirected_multiplex_test.go
graph/encoding/dot/bench_test.go
graph/encoding/dot/decode.go
graph/internal/set/same.go
graph/internal/set/same_appengine.go
graph/internal/set/set.go
graph/internal/set/set_test.go
graph/path/a_star.go
graph/path/shortest.go
graph/set/uid/uid.go
graph/testgraph/testgraph.go
graph/topo/bench_test.go
graph/topo/johnson_cycles.go
graph/topo/paton_cycles.go
graph/topo/tarjan.go
graph/traverse/traverse.go

graph: merge set.Ints and set.Int64s into one generic set

---

spatial/kdtree/kdtree_test.go
spatial/vptree/vptree_test.go

spatial: replace custom reverse logic with slices.Reverse

---

dsp/window/window_complex.go
floats/floats.go
graph/formats/dot/internal/errors/doc.go
graph/path/internal/testgraphs/doc.go
integrate/quad/quad.go
lapack/lapack.go
lapack/testlapack/dgesc2.go
mat/lu.go
optimize/convex/lp/simplex.go
spatial/r2/box.go
spatial/r3/box.go

All complaints in mathext/internal are ignored, and an unfortunate naming of methods in spatial/{r2,r3} is now permanent.
Fixes #1973 

all: fix doc comments identified by staticcheck

---

graph/community/louvain_directed_multiplex_test.go
graph/community/louvain_directed_test.go
graph/community/louvain_test.go
graph/community/louvain_undirected_multiplex_test.go
graph/community/louvain_undirected_test.go
graph/internal/ordered/sort.go
graph/path/shortest.go
graph/path/shortest_test.go
graph/topo/bench_test.go
graph/topo/bron_kerbosch.go
graph/topo/paton_cycles_test.go
graph/topo/tarjan.go

graph: replace custom reverse logic with slices.Reverse

---

unit/unit_test.go
unit/unittype.go

This PR introduces a modernization change that is not necessarily related to #617 but which was spun out from my attempts at generifying the leaves of `graph`. Benchmarks to follow.

unit: use more efficient sort routine

---

cmplxs/cmplxs.go
cmplxs/cmplxs_test.go

cmplxs: replace custom reverse logic with slices.Reverse

---

stat/moments_bench_test.go
stat/roc.go
stat/roc_test.go

stat: replace custom reverse logic with slices.Reverse 

---

graph/iterator/lines_map_safe.go
graph/iterator/nodes_map_safe.go

```
goos: linux
goarch: amd64
pkg: gonum.org/v1/gonum/graph/traverse
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
│  old.bench  │             new.bench              │
│   sec/op    │   sec/op     vs base               │
WalkAllBreadthFirstGnp_10_tenth-8     3.797µ ± 2%   3.609µ ± 3%  -4.95% (p=0.002 n=10)
WalkAllBreadthFirstGnp_100_tenth-8    149.9µ ± 2%   147.8µ ± 3%       ~ (p=0.579 n=10)
WalkAllBreadthFirstGnp_1000_tenth-8   13.12m ± 4%   12.75m ± 2%  -2.76% (p=0.019 n=10)
WalkAllBreadthFirstGnp_10_half-8      8.758µ ± 2%   8.530µ ± 1%  -2.61% (p=0.000 n=10)
WalkAllBreadthFirstGnp_100_half-8     624.3µ ± 2%   618.2µ ± 2%       ~ (p=0.143 n=10)
WalkAllBreadthFirstGnp_1000_half-8    60.83m ± 3%   58.88m ± 6%       ~ (p=0.052 n=10)
WalkAllDepthFirstGnp_10_tenth-8       3.763µ ± 2% …
```

graph/iterator: allocate reflect map iterator inline

---

graph/iterator/lines_map_safe.go
graph/iterator/nodes_map_safe.go

```
goos: linux
goarch: amd64
pkg: gonum.org/v1/gonum/graph/traverse
cpu: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
│  old.bench  │              new.bench              │
│   sec/op    │   sec/op     vs base                │
WalkAllBreadthFirstGnp_10_tenth-8     3.575µ ± 2%   2.961µ ± 2%  -17.18% (p=0.000 n=20)
WalkAllBreadthFirstGnp_100_tenth-8    144.4µ ± 1%   132.4µ ± 1%   -8.33% (p=0.000 n=20)
WalkAllBreadthFirstGnp_1000_tenth-8   12.66m ± 2%   12.00m ± 2%   -5.20% (p=0.000 n=20)
WalkAllBreadthFirstGnp_10_half-8      8.415µ ± 1%   7.615µ ± 1%   -9.51% (p=0.000 n=20)
WalkAllBreadthFirstGnp_100_half-8     628.0µ ± 1%   580.7µ ± 1%   -7.54% (p=0.000 n=20)
WalkAllBreadthFirstGnp_1000_half-8    58.74m ± 1%   55.79m ± 2%   -5.03% (p=0.000 n=20)
WalkAllDepthFirstGnp_10_tenth-8       3.539µ ± …
```

graph/iterator: improve reflect-based iterators

---

stat/distuv/gamma.go
stat/distuv/gamma_test.go

The mode of the Gamma distribution should be 0 for alpha < 1, not NaN. There's a singularity in the pdf, but it's still a valid mode.
Similarly, Prob(0) should be +Inf for alpha<1, and beta for alpha=1

stat/distuv: Correct Gamma Mode() and LogProb(0)/Prob(0) for alpha <= 1

---

interp/interp.go
interp/interp_test.go

Using `slices.BinarySearch` instead of `sort.Search` increases the speed of `findSegment` by a factor of two and overall performance by about 30%.
```
goos: linux
goarch: amd64
pkg: gonum.org/v1/gonum/interp
cpu: AMD Ryzen 7 5800 8-Core Processor
│  old.bench   │              new.bench              │
│    sec/op    │   sec/op     vs base                │
FindSegment-16                104.60n ± 1%   50.78n ± 1%  -51.45% (p=0.000 n=10)
NewPiecewiseLinear-16          114.5n ± 5%   112.2n ± 2%        ~ (p=0.109 n=10)
PiecewiseLinearPredict-16     116.00n ± 1%   84.44n ± 2%  -27.21% (p=0.000 n=10)
PiecewiseConstantPredict-16    87.95n ± 2%   63.93n ± 1%  -27.31% (p=0.000 n=10)
geomean                        105.2n        74.47n       -29.18%
```
Edit: Markdown formatting.

interp: increase speed of findSegment

---

AUTHORS
CONTRIBUTORS
mat/qr.go
mat/qr_test.go

Fixes #1968.
Builds upon #1970 initial proposal.
- mat: fix dst matrix shape check in QR.RTo
> When a matrix is very tall, calculating Q will currently allocate a large Q at the end of the factorisation, even if it is not going to be used, and a large Q matrix can lead to out of memory issues.
> 
> For this reason, Q is never eagerly computed unless explicitly required to by the user, with QR.ToQ.
To keep fulfilling the Matrix interface, the QR.At method will compute the requested element only, which only require computing a single row of Q.
Small typo found and fixed:
- mat: calculate Q elements lazily when calling QR.At
> Fixed a typo in row/column size check, the expected row size was incorrectly checked against the column size.

mat: calculate Q elements lazily when calling QR.At

---

graph/coloring/coloring.go
graph/community/louvain_common.go
graph/community/louvain_directed.go
graph/community/louvain_directed_multiplex_test.go
graph/community/louvain_directed_test.go
graph/community/louvain_undirected.go
graph/community/louvain_undirected_multiplex_test.go
graph/community/louvain_undirected_test.go
graph/encoding/graphql/decode_test.go
graph/formats/rdf/debug.go
graph/formats/rdf/graph_test.go
graph/formats/rdf/iso_canonical.go
graph/formats/rdf/iso_canonical_example_test.go
graph/formats/rdf/iso_canonical_test.go
graph/formats/rdf/query.go
graph/formats/rdf/query_test.go
graph/formats/rdf/urna.go
graph/iterator/lines_test.go
graph/network/betweenness_test.go
graph/network/hits_test.go
graph/network/page_test.go
graph/path/dynamic/dumper_test.go
graph/path/spanning_tree.go
graph/path/yen_ksp.go
graph/path/yen_ksp_test.go
graph/product/product_example_test.go
graph/testgraph/testgraph.go
graph/topo/2sat_example_test.go
internal/order/order.go

This PR introduces a modernization change that is not necessarily related to #617 but which was spun out from my attempts at generifying the leaves of `graph`. Benchmarks to follow.
Blocked by https://github.com/gonum/gonum/pull/1940 and https://github.com/gonum/gonum/pull/1953.

graph: use slices package for sorting and reversing slices

---

graph/path/dijkstra.go
graph/path/dijkstra_test.go
graph/path/yen_ksp.go

`YenKShortestPaths`'s running time is dominated by calls to Dijkstra's shortest path algorithm, so it makes sense to focus on improvements there.
For Yen's algorithm, we are not interested in shortest path trees, but only _a_ shortest path between some source and target node. We can exploit this in Dijkstra's algorithm by terminating when the target is discovered.
Of course this does not improve the worst-case complexity, but it should be a worthwhile optimization for many practical uses.

graph/path: Improve performance of `YenKShortestPaths`

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
.github/workflows/staticcheck.yml
blas/testblas/level1double.go
go.mod
optimize/unconstrained_test.go

all: use Go-1.24, drop Go-1.22

---

lapack/testlapack/dtrevc3.go

In the residualEVNormalization function, there was an error in the final return statement where both arguments to math.Max used enrmin . The correct calculation should compare deviations of both minimum and maximum norms from 1.

lapack: fix eigenvector normalization residual calculation

---

stat/stat_example_test.go

This CL adds an example showing how to compute the confidence interval of the mean for a small sample.

stat: add an example to compute a confidence interval

---

stat/stat.go
stat/stat_test.go

This PR focuses on implementing the Wasserstein Distance (also known as Earth Mover's Distance) for both 1-d and n-d distributions. The implementation was heavily inspired by Scipy - some test cases were taken from there.
The functions include:
- optional weights: if nil, uniform weights are used
- weight normalization
- extensive validity checks
- comments to document and explain the steps taken
- tests
This is my first contribution to Gonum.
I apologize for any rules I may have missed and would welcome suggestions. Some brackets in the stat package were removed as a result to an auto-refactor.

stat: implement Wasserstein distance calculation
